pkp/ojs

- pages/manager/PluginManagementHandler.inc.php
I'll need to more fully test this but it's a first crack at a fix.
> *9020* Removing code that moves plugin lib folders to the PKP WAL.

- plugins/generic/dataverse/classes/form/DataverseAuthForm.inc.php
- plugins/generic/dataverse/locale/en_US/locale.xml
pkp/pkp-lib#271 Allow API token to be submitted in place of username/password.
> Allow Dataverse plugin to connect via API token

- plugins/generic/dataverse/DataversePlugin.inc.php
- plugins/generic/dataverse/classes/form/DataverseAuthForm.inc.php
- plugins/generic/dataverse/classes/form/DataverseSelectForm.inc.php
Add API version to plugin settings & build service doc request. Check service doc for deprecation warnings & update API version if newer version available.
> pkp/pkp-lib#284 Check API response for plugin settings

- plugins/generic/dataverse/locale/ru_RU/locale.xml
> Update ru_RU locale for Dataverse plugin

- plugins/importexport/crossref/classes/CrossRefExportDom.inc.php
> pkp/pkp-lib#267 Fix cross-journal CrossRef URL generation

- plugins/generic/pln/classes/DepositPackage.inc.php
Adds publisher institution and url to deposit, and fixes one typo.
Fixes pkp/pkp-lib#290
> Add publisher info to sword deposit

- plugins/generic/pln/PLNGatewayPlugin.inc.php
- plugins/generic/pln/PLNPlugin.inc.php
- plugins/generic/pln/classes/Deposit.inc.php
- plugins/generic/pln/classes/DepositDAO.inc.php
- plugins/generic/pln/classes/DepositObject.inc.php
- plugins/generic/pln/classes/DepositObjectDAO.inc.php
- plugins/generic/pln/classes/DepositPackage.inc.php
- plugins/generic/pln/classes/form/PLNSettingsForm.inc.php
- plugins/generic/pln/classes/form/PLNStatusForm.inc.php
- plugins/generic/pln/classes/tasks/Depositor.inc.php
- plugins/generic/pln/index.php
- plugins/generic/pln/locale/de_DE/locale.xml
- plugins/generic/pln/locale/en_US/locale.xml
- plugins/generic/pln/locale/ru_RU/locale.xml
- plugins/generic/pln/pages/PLNHandler.inc.php
- plugins/generic/pln/templates/settings.tpl
- plugins/generic/pln/templates/setup.tpl
- plugins/generic/pln/templates/status.tpl
- plugins/generic/pln/version.xml
- plugins/generic/pln/xml/scheduledTasks.xml
- plugins/generic/pln/xml/schema.xml
- plugins/generic/pln/xml/settings.xml
Update the version number and copyright years.
> Update version number to 1.0.1 and all copyrights to 2015.

- plugins/generic/dataverse/DataversePlugin.inc.php
Publish draft Dataverses via API, if supported.
Added null check on study creation if request fails.
> pkp/pkp-lib#286 Dataverse plugin: publish Dataverses via API

- plugins/generic/pln/PLNPlugin.inc.php
> Include language in sword service document request.

- classes/article/AuthorDAO.inc.php
- pages/editor/IssueManagementHandler.inc.php
> pkp/pkp-lib#309 Don't send duplicated emails to authors in /editor/notifyUsers

- plugins/generic/referral/referralForm.tpl
http://pkp.sfu.ca/support/forum/viewtopic.php?f=8&t=13690&p=52415#p52415
> pkp/pkp-lib#313: Match refback size limit in form to size limit in database

- plugins/importexport/quickSubmit/QuickSubmitForm.inc.php
- plugins/importexport/quickSubmit/index.tpl
- templates/author/submit/step3.tpl
See http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=9051
> *9051* Add ORCiD field to QuickSubmit plugin

- classes/article/Article.inc.php
- classes/issue/IssueAction.inc.php
- controllers/tab/issueEntry/form/IssueEntryPublicationMetadataForm.inc.php
- controllers/tab/settings/DistributionSettingsTabHandler.inc.php
- controllers/tab/settings/permissions/form/OJSPermissionSettingsForm.inc.php
- js/controllers/tab/issueEntry/form/IssueEntryPublicationMetadataFormHandler.js
- locale/en_US/manager.xml
- pages/article/ArticleHandler.inc.php
- pages/management/SettingsHandler.inc.php
- plugins/generic/webFeed/templates/atom.tpl
- plugins/generic/webFeed/templates/rss.tpl
- plugins/generic/webFeed/templates/rss2.tpl
- plugins/oaiMetadataFormats/marc/OAIMetadataFormat_MARC.inc.php
- plugins/oaiMetadataFormats/marc/record.tpl
- plugins/oaiMetadataFormats/marcxml/OAIMetadataFormat_MARC21.inc.php
- plugins/oaiMetadataFormats/marcxml/record.tpl
- plugins/oaiMetadataFormats/nlm/OAIMetadataFormat_NLM.inc.php
- templates/article/footer.tpl
- templates/common/minifiedScripts.tpl
- templates/controllers/tab/issueEntry/form/publicationMetadataFormFields.tpl
- templates/controllers/tab/settings/access/form/accessForm.tpl
- templates/controllers/tab/settings/identifiers/form/identifiersForm.tpl
- templates/controllers/tab/settings/permissions/form/permissionSettingsForm.tpl
- templates/management/settings/distribution.tpl
> pkp/pkp-lib#278 Forward-port permissions improvements to OJS 3.0/OMP 1.2

- plugins/generic/pln/classes/form/PLNSettingsForm.inc.php
- plugins/generic/pln/locale/en_US/locale.xml
- plugins/generic/pln/templates/settings.tpl
Require journal managers to provide an ISSN before allowing them to agree to the terms of use. 
Fixes pkp/pkp-lib#365
> #365 Require ISSN early in the PLN setup process

- classes/file/ArticleFileManager.inc.php
- classes/submission/form/ArticleGalleyForm.inc.php
When an EPUB file is uploaded, the correct mime type (application/epub+zip) is set.
> EPUB galley article files recognized as EPUB files

- locale/cs_CZ/admin.xml
- locale/cs_CZ/author.xml
- locale/cs_CZ/default.xml
- locale/cs_CZ/editor.xml
- locale/cs_CZ/emailTemplates.xml
- locale/cs_CZ/locale.xml
- locale/cs_CZ/manager.xml
- registry/locales.xml
* updated cs_CZ locale 
* header repaired
* unified name "Čeština"
> updated cs_CZ locale

- plugins/generic/googleAnalytics/pageTagUrchin.tpl
- templates/article/footer.tpl
- templates/article/header.tpl
- templates/rt/header.tpl
- templates/submission/comment/header.tpl
> pkp/pkp-lib#449 Fix loading scripts from https

- plugins/generic/alm/locale/pt_BR/locale.xml
> pkp/pkp-lib#451 ALM plugin translation to pt_BR

- templates/article/footer.tpl
S. https://github.com/pkp/pkp-lib/issues/472
Please cherry-pick to other branches if necessary... :-)
> pkp/pkp-lib#472 present other license URL on the article page

- pages/manager/EmailHandler.inc.php
- pages/manager/index.php
- templates/manager/emails/emails.tpl
Email templates can be exported as XML file and edited all at once.
> pkp/pkp-lib#427 Bulk editing for email templates

- plugins/importexport/native/native.dtd
S. https://github.com/pkp/pkp-lib/issues/486
Please, cherry-pich to other branches... :-)
> copyright_holder fix for native DTD

- plugins/generic/referral/ReferralPlugin.inc.php
please cherry-pick to other branches if necessary...
> a small locale fix in referral plugin

- classes/article/ArticleDAO.inc.php
> pkp/pkp-lib#497 Use array_merge instead of + for merging arrays

- classes/author/form/submit/AuthorSubmitStep3Form.inc.php
- classes/manager/form/LanguageSettingsForm.inc.php
- classes/manager/form/UserManagementForm.inc.php
- classes/sectionEditor/form/CreateReviewerForm.inc.php
- classes/submission/form/MetadataForm.inc.php
- classes/subscription/form/SubscriptionForm.inc.php
- classes/user/UserDAO.inc.php
- classes/user/form/ProfileForm.inc.php
- classes/user/form/RegistrationForm.inc.php
> pkp/pkp-lib#499 Call superclass when overriding methods in Form and DAO subclasses

- locale/en_US/locale.xml
- pages/about/AboutHandler.inc.php
- templates/about/editorialPolicies.tpl
- templates/about/index.tpl
Hi Alec, follow-up PR with improved indentation/readability.
> pkp/pkp-lib#448 Reader fees not included in About ##mfelczak/ojs-dev-2_4##

- plugins/generic/objectsForReview/pages/ReviewObjectTypesEditorHandler.inc.php
> Fix call-time pass by reference ##mfelczak/ojs-dev-2_4##

- plugins/generic/objectsForReview/pages/ReviewObjectTypesEditorHandler.inc.php
> Fix call-time pass by reference ##mfelczak/ojs-stable-2_4_6##

- locale/it_IT/locale.xml
I added the words "IMPORTANTE" and registrat* (which wasn't included because of a typo), because many users often duplicate their account instead of merging an existing one.
> A few additions in Italian translation of locale.xml

- classes/submission/author/AuthorAction.inc.php
Remove author signature from revised article upload notification email.
Fix pkp/pkp-lib#521
> pkp/pkp-lib#521 Remove author signature from revised article upload notification email

- classes/journal/Journal.inc.php
- classes/journal/JournalDAO.inc.php
I'm looking for this getBySetting() function in 2.x for the forthcoming SUSHI-Lite plugin.
> pkp/pkp-lib#526 Backport ContextDAO::getBySetting() to JournalDAO

- templates/search/authorIndex.tpl
The same of https://github.com/pkp/ojs/pull/504 but in ojs-dev-2_4 branch
> Author country in authors list

- plugins/generic/translator/TranslatorHandler.inc.php
https://github.com/pkp/pkp-lib/issues/546
http://forum.pkp.sfu.ca/t/missing-key-disappears-from-list-of-missing-keys-although-it-is-not-translated/1125/10
> pkp/pkp-lib#546 Create empty locale files via the Translator plugin

- plugins/generic/pln/locale/en_US/locale.xml
Add the plugins.generic.pln.notifications.tar_missing locale key.
> Add one missing locale key.

- plugins/pubIds/urn/templates/urnSuffixEdit.tpl
S. https://github.com/pkp/pkp-lib/issues/560
Please cherry-pick to other branches if necessary...
> pkp/pkp-lib#560 fix for the single step exclusion of URNs

- plugins/citationFormats/abnt/AbntCitationPlugin.inc.php
- plugins/citationFormats/abnt/citation.tpl
> pkp/pkp-lib#551 Months with 4 or less letters are not abbreviated in ABNT citation

- plugins/generic/pln/ping.dtd
- plugins/generic/pln/templates/ping.tpl
> Remove pln plugin install date from the gateway output.

- plugins/generic/pln/locale/en_US/locale.xml
> Add missing PLNGateway locale keys.

- plugins/generic/referral/locale/pt_PT/locale.xml
cherry-picked from ojs-stable-2_4_6 (#534)
> updated pt_PT locale, referral plugin

- plugins/importexport/doaj/DOAJPlugin.inc.php
I fixed a bug in plugins/importexport/doaj/DOAJPlugin.inc.php - the pagination didn't work correctly (by the way - this bug occurs also in the 2.4.6 stable version).
> pkp/pkp-lib#589 Bug fix for DOAJ pagination problem

- plugins/generic/pln/PLNGatewayPlugin.inc.php
- plugins/generic/pln/ping.dtd
- plugins/generic/pln/templates/ping.tpl
Report the terms of use, date updated, and date accepted in the PLN gateway.
fixes pkp/pkp-lib#583
> Add terms of use to PLN gateway

- templates/article/article.tpl
- templates/rt/metadata.tpl
S. https://github.com/pkp/pkp-lib/issues/577
Please cherry-pick to other branches, if necessary...
> pkp/pkp-lib#577 Display galleys pubIds

- plugins/generic/pln/locale/de_DE/locale.xml
- plugins/generic/pln/locale/en_US/locale.xml
* updated de_DE locale to recent en_US updates
* minor whitespace issues in en_US locale
> updated locale for PLN plugin

- plugins/generic/pln/PLNGatewayPlugin.inc.php
- plugins/generic/pln/PLNPlugin.inc.php
- plugins/generic/pln/README
- plugins/generic/pln/classes/DepositDAO.inc.php
- plugins/generic/pln/classes/DepositPackage.inc.php
- plugins/generic/pln/classes/form/PLNSettingsForm.inc.php
- plugins/generic/pln/css/pln.css
- plugins/generic/pln/locale/en_US/locale.xml
- plugins/generic/pln/ping.dtd
- plugins/generic/pln/templates/settings.tpl
- plugins/generic/pln/version.xml
- plugins/generic/pln/xml/settings.xml
The network URL defaults to a value defined in the code, and can be overridden in on defined in config.inc.php. Journal managers can also set a value for the network URL.
Closes pkp/pkp-lib#586
> Add network URL to the PLN plugin settings page.

- locale/sv_SE/admin.xml
- locale/sv_SE/author.xml
- locale/sv_SE/editor.xml
- locale/sv_SE/locale.xml
- locale/sv_SE/manager.xml
- plugins/blocks/navigation/locale/sv_SE/locale.xml
- plugins/blocks/readingTools/locale/sv_SE/locale.xml
- plugins/blocks/subscription/locale/sv_SE/locale.xml
- plugins/citationFormats/mla/locale/sv_SE/locale.xml
- plugins/generic/counter/locale/sv_SE/locale.xml
- plugins/generic/referral/locale/sv_SE/locale.xml
- plugins/importexport/quickSubmit/locale/sv_SE/locale.xml
Initial commit of updating the sv_SE locale with translation work done at Lund University Library.
> Reviewed sv_SE locale files

- .gitignore
> Limit files directory exclusion in .gitignore to top-level directory

- plugins/themes/default/styles/components.less
- plugins/themes/default/styles/index.less
- plugins/themes/default/styles/pages/login.less
- plugins/themes/default/styles/pages/lostPassword.less
- plugins/themes/default/styles/pages/register.less
Lots of stuff here that can be improved toi prevent code duplication. But let's save it for when I have time to think of a good approach.
> Pkp/pkp lib#639 style register and login pages

- plugins/themes/default/styles/main.less
- templates/frontend/pages/article.tpl
Fix is in getLocalizeName(). The rest is just styling the galley.
> Fix article galley file names and improve style

- classes/manager/form/UserManagementForm.inc.php
Fix  pkp/pkp-lib#691 by filling the form if the user can be managed by the current logged in user.
>  pkp/pkp-lib#691 Fill UserManagementForm if the user can be managed by logged in user

- plugins/blocks/user/UserBlockPlugin.inc.php
- plugins/blocks/user/block.tpl
- plugins/blocks/user/locale/en_US/locale.xml
See https://github.com/pkp/pkp-lib/issues/690
Also, move hardcoded English string to locale key.
> pkp/pkp-lib#690: user login block should not expose a form via http if force_login_ssl is set

- templates/frontend/pages/about.tpl
> Fix documentation on about page template

- templates/header/primaryNavMenu.tpl
Here's the template for OJS related to pkp/pkp-lib#706. I'll role the OMP one into the general work being done to bring it in line with pkp-lib.
> Use app-specific template for frontend primary navigation menu

- locale/de_DE/emailTemplates.xml
- locale/de_DE/manager.xml
- locale/it_IT/locale.xml
* cherry-picked update to it_IT locale
* minor corrections in de_DE locale
> locale updates (it_IT, de_DE)

- templates/frontend/components/searchForm_simple.tpl
See [this PR](https://github.com/pkp/pkp-lib/pull/718)
> Move search template into frontend template directory

- classes/template/TemplateManager.inc.php
See [this PR](https://github.com/pkp/pkp-lib/pull/713).
> Pass  to templates for use in primary nav in header.tpl

- plugins/generic/googleAnalytics/settingsForm.tpl
C.f. https://github.com/pkp/ojs/pull/599/files#r39314902
> pkp/pkp-lib#741: Apply field labels and data sanitization to new Google Analytics options.

- locale/ru_RU/locale.xml
- plugins/blocks/user/locale/de_DE/locale.xml
- plugins/generic/objectsForReview/locale/es_ES/locale.xml
- plugins/generic/pln/locale/de_DE/locale.xml
- plugins/generic/usageStats/locale/de_DE/locale.xml
- plugins/generic/usageStats/locale/en_US/locale.xml
- plugins/generic/usageStats/locale/pt_PT/locale.xml
- plugins/importexport/crossref/locale/de_DE/locale.xml
- registry/locales.xml
* de_DE locale: updated
* es_ES locale: minor update from translation server
* pt_PT locale: manually updated plugin translation, see #533
* ru_RU locale: manually updated key, see #579
* usageStats plugin: updated locales (en_US, de_DE)
* locales.xml in registry: sorted alphabetically
> OJS locales updated

- locale/fr_CA/locale.xml
- locale/fr_FR/locale.xml
see: http://forum.pkp.sfu.ca/t/small-typo-in-the-french-fr-locale/4353
> updated French locales

- plugins/paymethod/manual/locale/id_ID/locale.xml
> fixed broken id_ID locale file

- plugins/importexport/datacite/DataciteExportPlugin.inc.php
- plugins/importexport/datacite/DataciteInfoSender.inc.php
- plugins/importexport/datacite/classes/DOIExportPlugin.inc.php
- plugins/importexport/datacite/classes/form/DataciteSettingsForm.inc.php
- plugins/importexport/datacite/locale/en_US/locale.xml
- plugins/importexport/datacite/scheduledTasks.xml
- plugins/importexport/datacite/templates/settings.tpl
S. https://github.com/pkp/pkp-lib/issues/730
> pkp/pkp-lib#730 automatic DOI registration to DataCite

- plugins/importexport/crossref/CrossrefInfoSender.inc.php
- plugins/importexport/datacite/DataciteInfoSender.inc.php
S. https://github.com/pkp/pkp-lib/issues/799
> Fix DataCite and CrossRef scheduled tasks error e-mails

- pages/editor/IssueManagementHandler.inc.php
Fix pkp/pkp-lib#791 when publishing new issue.
> pkp/pkp-lib#791 Do not send published issue notification emails to disabled users

- locale/ar_IQ/default.xml
- locale/ar_IQ/locale.xml
Changes have been made to few words to improve translation
> Minor updates to the translation

- plugins/reports/articles/ArticleReportPlugin.inc.php
Import the several undefined submission editor decision constants.
> Import submission editor decision constants

- plugins/generic/piwik/PiwikPlugin.inc.php
Resolves https://github.com/pkp/pkp-lib/issues/819
> pkp/pkp-lib#819: change piwik plugin output to append rather than overwrite footer

- plugins/importexport/crossref/classes/CrossRefExportDom.inc.php
- plugins/importexport/datacite/DataciteExportPlugin.inc.php
- plugins/importexport/medra/classes/O4DOIExportDom.inc.php
S. https://github.com/pkp/pkp-lib/issues/822
S. http://forum.pkp.sfu.ca/t/doi-registration-not-working-via-command-line/4585
Could this be chery-picked to ojs-dev-2_4?
> pkp/pkp-lib#822 fix wrong URL for CLI DOI export and registration

- templates/user/registerSite.tpl
Resolves https://github.com/pkp/pkp-lib/issues/842
> pkp/pkp-lib#842: Add page title to Site Registration.

- plugins/generic/usageStats/UsageStatsReportPlugin.inc.php
Resolves https://github.com/pkp/pkp-lib/issues/848
> pkp/pkp-lib#848: Add $request parameter to UsageStatsReportPlugin::display()

- plugins/importexport/datacite/locale/de_DE/common.xml
- plugins/importexport/datacite/locale/de_DE/locale.xml
- plugins/importexport/datacite/locale/en_US/common.xml
- plugins/importexport/datacite/locale/en_US/locale.xml
> pkp/pkp-lib#872 updated DOI plugins

- plugins/importexport/datacite/locale/de_DE/common.xml
- plugins/importexport/datacite/locale/de_DE/locale.xml
- plugins/importexport/datacite/locale/en_US/common.xml
- plugins/importexport/datacite/locale/en_US/locale.xml
* fixes pkp/pkp-lib#872 
* updated de_DE locale (thanks @uwords)
> updated DOI plugins pkp/pkp-lib#872

- classes/journal/JournalStatisticsDAO.inc.php
Resolves https://github.com/pkp/pkp-lib/issues/856
> Replace JournalStatisticsDAO cross product with two queries

- plugins/importexport/datacite/templates/issues.tpl
S. https://github.com/pkp/pkp-lib/issues/855
Could it be cherry-picked to ojs-dev-2_4?
> pkp/pkp-lib#855 fix DataCite export link for issues

- plugins/generic/pln/locale/en_US/locale.xml
The terms of use preamble needs to be more legalish.
> Update the terms of use preamble

- pages/sectionEditor/SubmissionEditHandler.inc.php
- templates/submission/metadata/metadataEdit.tpl
Resolves https://github.com/pkp/pkp-lib/issues/889
> pkp/pkp-lib#889: Check for unset section when editor is managing submission summary and editing metadata

- plugins/generic/thesisFeed/ThesisFeedPlugin.inc.php
Resolves https://github.com/pkp/pkp-lib/issues/897 ala https://github.com/pkp/ojs/pull/606
> pkp/pkp-lib#897: Ensure ThesisFeedPlugin callbacks only affect page requests.

- plugins/generic/googleAnalytics/GoogleAnalyticsSettingsForm.inc.php
Resolves https://github.com/pkp/pkp-lib/issues/899
> pkp/pkp-lib#899: Fix Google Analytics enableSite setting type.

- pages/editor/IssueManagementHandler.inc.php
Fix pkp/pkp-lib#919 by checking if the recipient is a User before verifying if he was disabled.
> pkp/pkp-lib#919 Fix notify "All published authors"

- plugins/generic/lucene/README
- plugins/generic/lucene/embedded/etc/jetty.xml
S. https://github.com/pkp/pkp-lib/issues/917
Could this commit be cherry-picked to ojs-stable-2_4_7, if necessary? Else, I can make a new PR for that branch too...
> pkp/pkp-lib#917 remove references to codehaus.org

- locale/pt_BR/locale.xml
- locale/pt_PT/locale.xml
Add missing preposition and space between text and <a> tag.
@mtub I believe you're the guy that reviews this.
PS.: This should be cherry picked to ojs-dev-2_4.
> Add missing preposition and space

- locale/pt_BR/locale.xml
- locale/pt_PT/locale.xml
cherry-picked from master (see https://github.com/pkp/ojs/pull/680)
> Updated pt locales

- plugins/importexport/crossref/locale/de_DE/locale.xml
- plugins/importexport/crossref/locale/en_US/locale.xml
- plugins/importexport/datacite/locale/de_DE/locale.xml
- plugins/importexport/datacite/locale/en_US/locale.xml
* renamed an option in CrossRef plugin (see https://github.com/pkp/pkp-lib/issues/872#issuecomment-156455947)
* renamed task name in CrossRef and DataCite plugins as discussed with @beghelli and @bozana
> updated locale of crossRef plugin

- pages/manager/StatisticsHandler.inc.php
Resolves https://github.com/pkp/pkp-lib/issues/1007
> pkp/pkp-lib#1007: Load the EDITOR locale file to translate editor.issues.galley when generating a custom report on Issue Galleys.

- plugins/generic/usageStats/locale/es_ES/locale.xml
> removed a line from es_ES locale of usageStats plugin

- locale/de_DE/locale.xml
- plugins/generic/googleAnalytics/locale/de_DE/locale.xml
- plugins/generic/pln/locale/de_DE/locale.xml
- plugins/generic/usageStats/locale/de_DE/locale.xml
- plugins/generic/usageStats/locale/en_US/locale.xml
- plugins/pubIds/doi/locale/de_DE/locale.xml
* updated the de_DE locale according to changes and additions in en_US locale
* minor change in en_US locale of usageStats plugin
> updated de_DE locale

- .gitmodules
- plugins/reports/counter/CounterReportPlugin.inc.php
- plugins/reports/counter/classes/CounterReport.inc.php
- plugins/reports/counter/classes/LegacyJR1.inc.php
- plugins/reports/counter/classes/reports/CounterReportAR1.inc.php
- plugins/reports/counter/classes/reports/CounterReportJR1.inc.php
- plugins/reports/counter/index.php
- plugins/reports/counter/locale/en_US/ar1.xml
- plugins/reports/counter/locale/en_US/jr1.xml
- plugins/reports/counter/locale/en_US/locale.xml
- plugins/reports/counter/templates/index.tpl
- plugins/reports/counter/version.xml
This abstracts the counter plugin to allow multiple COUNTER releases and reports.  Release 4.1 of JR1 and AR1 are provided as examples.
This provides the foundation for SUSHI-Lite calls via the forthcoming SUSHI-Lite plugin:
https://github.com/ulsdevteam/ojs-sushiLite-plugin
> pkp/pkp-lib#739 Create new Release/Report class structure in Counter plugin; Add COUNTER class.

- plugins/generic/pln/classes/DepositObjectDAO.inc.php
When finding deposits to update, skip deposits that are not fully and completely processed and synchronized in LOCKSS.
Fixes pkp/pkp-lib#1042
> Make sure a deposit is fully synched with LOCKSS before updating it

- config.TEMPLATE.inc.php
- docs/release-notes/README-2.4.8
- plugins/generic/pln/PLNPlugin.inc.php
- plugins/generic/pln/classes/form/PLNSettingsForm.inc.php
- plugins/generic/pln/css/pln.css
- plugins/generic/pln/locale/ar_IQ/locale.xml
- plugins/generic/pln/locale/de_DE/locale.xml
- plugins/generic/pln/locale/en_US/locale.xml
- plugins/generic/pln/locale/ru_RU/locale.xml
- plugins/generic/pln/templates/settings.tpl
- plugins/generic/pln/xml/settings.xml
It isn't necessary and it causes quite a bit of confusion for the journal managers. Also removes the pln_network* locale keys and settings.xml config. 
Fixes pkp/pkp-lib#1043
> Remove the UI elements for the pln_url config variable.

- plugins/generic/usageStats/locale/es_ES/locale.xml
updated usageStats es_ES locale with string provided by @marcbria
> pkp/pkp-lib#959 updated es_ES locale

- templates/issue/issue.tpl
S. https://github.com/pkp/pkp-lib/issues/1062
> pkp/pkp-lib#1062: localized article cover images

- plugins/generic/pln/classes/DepositPackage.inc.php
> Add licensing terms to the deposit XML.

- controllers/grid/admin/journal/form/JournalSiteSettingsForm.inc.php
There is a typo in the fix for pkp/pkp-lib#617
> Fix typo in pkp/pkp-lib#617 fix

- plugins/importexport/crossref/CrossRefExportPlugin.inc.php
- plugins/importexport/crossref/templates/issues.tpl
- plugins/importexport/datacite/classes/DOIExportPlugin.inc.php
- plugins/importexport/datacite/templates/issues.tpl
- plugins/importexport/medra/templates/issues.tpl
S. https://github.com/pkp/pkp-lib/issues/1088
> fix issue paging for the doi export/registration plugins 

- locale/ar_IQ/locale.xml
- locale/ar_IQ/manager.xml
- plugins/generic/pln/locale/ar_IQ/locale.xml
- plugins/generic/usageStats/locale/ar_IQ/locale.xml
- plugins/importexport/crossref/locale/ar_IQ/locale.xml
- plugins/importexport/datacite/locale/ar_IQ/common.xml
- plugins/importexport/datacite/locale/ar_IQ/locale.xml
- plugins/pubIds/doi/locale/ar_IQ/locale.xml
- plugins/reports/counter/locale/ar_IQ/locale.xml
Some minor updates to the development branch dev-2_4 after OJS 2.4.7 was
released.
> Updates in Arabic locale before the release of OJS 2.4.8

- plugins/generic/pln/locale/de_DE/locale.xml
Updating according to changes of en_US locale of PLN plugin merged yesterday.
> de_DE: updated PLN plugin locale

- plugins/themes/default/styles/body.less
- plugins/themes/default/styles/components.less
- plugins/themes/default/styles/footer.less
- plugins/themes/default/styles/head.less
- plugins/themes/default/styles/helpers.less
- plugins/themes/default/styles/objects/announcement_full.less
- plugins/themes/default/styles/objects/announcement_summary.less
- plugins/themes/default/styles/variables.less
See https://github.com/pkp/pkp-lib/pull/1117
> New frontend design

- pages/user/UserHandler.inc.php
Resolves https://github.com/pkp/pkp-lib/issues/1116
> pkp/pkp-lib#1116: prioritize source parameter over HTTP_REFERER in setLocale action.

- classes/submission/sectionEditor/SectionEditorAction.inc.php
- plugins/reports/reviews/ReviewReportDAO.inc.php
- plugins/reports/reviews/ReviewReportPlugin.inc.php
Ported to ojs-dev-2_4 and tested.
> pkp/pkp-lib#1050 Add review form responses to reviews report

- docs/dev/ojs2.doxygen
- plugins/generic/counter/CounterHandler.inc.php
- plugins/generic/externalFeed/simplepie/SimplePie.inc.php
- plugins/generic/lucene/LucenePlugin.inc.php
- plugins/generic/lucene/classes/SolrWebService.inc.php
- plugins/implicitAuth/shibboleth/ShibAuthPlugin.inc.php
- plugins/importexport/pubIds/templates/importResults.tpl
- plugins/pubIds/urn/URNPubIdPlugin.inc.php
- plugins/pubIds/urn/js/checkNumber.js
- tests/functional/plugins/block/mostRead/FunctionalMostReadBlockPluginTestCase.php
All of them were found and fixed by codespell.
> Fix some typos in code comments

- classes/submission/form/SubmissionSubmitStep4Form.inc.php
The email signature will be appended by `MailTemplate`
> Remove extra email signature

- plugins/generic/booksForReview/pages/BooksForReviewAuthorHandler.inc.php
- plugins/generic/booksForReview/pages/BooksForReviewHandler.inc.php
http://forum.pkp.sfu.ca/t/problems-with-books-for-review/8259/11
> Missing 'else' in booksForReview plugin

- plugins/generic/lucene/LucenePlugin.inc.php
- plugins/generic/lucene/classes/SolrWebService.inc.php
- plugins/generic/lucene/classes/form/LuceneSettingsForm.inc.php
- plugins/generic/lucene/locale/en_US/locale.xml
- plugins/generic/lucene/templates/settingsForm.tpl
S. #1183
I am not sure if this PR should go to the OJS stable or dev branch :-\ I believe it solves a bug in the stable branch, thus here... :-)
> proxy option for solr web service requests

- robots.txt
Robots.txt big issue http://forum.pkp.sfu.ca/t/robots-txt-big-issue/8787
> Better compliance with standard

- dbscripts/xml/upgrade.xml
- registry/emailTemplates.xml
S. https://github.com/pkp/pkp-lib/issues/1054#issuecomment-190095972
Is the maxversion in the upgrade script correct?
> fix the wrong email template name

- dbscripts/xml/ojs_schema.xml
- plugins/generic/booksForReview/xml/schema.xml
- plugins/generic/externalFeed/schema.xml
- plugins/generic/referral/schema.xml
S. https://github.com/pkp/pkp-lib/issues/1209
I should not consider the ojs_schema_stage1.xml, right?
> pkp/pkp-lib#1209 increase the size of the URL database fields

- locale/pt_BR/emailTemplates.xml
Could you please cherrypick this to ojs_dev_2-4 too?
I can make another PR against that branch if its needed.
> Add missing words in emailTemplates

- plugins/pubIds/doi/locale/pt_PT/locale.xml
cherry-picked from #785 (@josekarvalho)
> pt_PT locale for doi plugin

- plugins/importexport/crossref/classes/CrossRefExportDom.inc.php
S. https://github.com/pkp/pkp-lib/issues/1204
> pkp/pkp-lib#1204 no mime_type for remote galleys in crossref export

- plugins/importexport/native/filter/ArticleGalleyNativeXmlFilter.inc.php
- plugins/importexport/native/filter/NativeXmlArticleGalleyFilter.inc.php
- plugins/importexport/native/native.xsd
- tests/data/60-content/issue.xml
S. d) and g) here: https://github.com/pkp/pkp-lib/issues/1263
> pkp/pkp-lib#1263 port OMP native export changes to OJS

- plugins/importexport/native/filter/NativeXmlArticleGalleyFilter.inc.php
S. c) here: https://github.com/pkp/pkp-lib/issues/1295
> pkp/pkp-lib#1295 consider submission_file_ref for OJS native import

- classes/article/ArticleGalleyDAO.inc.php
- classes/article/PublishedArticle.inc.php
- classes/article/PublishedArticleDAO.inc.php
- controllers/grid/toc/TocGridHandler.inc.php
- controllers/tab/issueEntry/form/IssueEntryPublicationMetadataForm.inc.php
- plugins/generic/externalFeed/ExternalFeed.inc.php
- plugins/generic/externalFeed/ExternalFeedDAO.inc.php
- plugins/generic/externalFeed/ExternalFeedForm.inc.php
- plugins/generic/externalFeed/ExternalFeedPlugin.inc.php
- plugins/importexport/medra/classes/O4DOIExportDom.inc.php
- plugins/importexport/native/filter/ArticleNativeXmlFilter.inc.php
- plugins/importexport/native/filter/NativeXmlArticleFilter.inc.php
- plugins/oaiMetadataFormats/nlm/OAIMetadataFormat_NLM.inc.php
Addresses pkp/pkp-lib#1342 by normalizing usage throughout all `DataObject` subclasses.
> pkp/pkp-lib#1342 standardizes all DataObject subclasses on getSequence()/setSequence()

- plugins/generic/usageStats/UsageStatsPlugin.inc.php
S. https://github.com/pkp/pkp-lib/issues/1417
> introduce usage stats visualization app specifics

- plugins/themes/default/styles/head.less
> pkp/pkp-lib#1390 Tidy borders in header search bar

- dbscripts/xml/upgrade/3.0.0_update.xml
in fixing the original report in the issue:
> pkp/pkp-lib#1514 fix re-map of file constants during upgrade

- plugins/generic/tinymce/TinyMCEPlugin.inc.php
> pkp/pkp-lib#1522: Add TinyMCE to address and bio for Manager's edit of user profiles.

- plugins/generic/pln/PLNPlugin.inc.php
> Provide a default object_type setting for the PLN plugin.

- classes/security/authorization/OjsIssueRequiredPolicy.inc.php
S. https://github.com/pkp/pkp-lib/issues/1537
> pkp/pkp-lib#1537 consider public URL identifier in issue required policy

- plugins/generic/pln/PLNPlugin.inc.php
Resolves https://github.com/pkp/pkp-lib/issues/1401
> pkp/pkp-lib#1401: Add section parameter to getVar() call.

- plugins/importexport/datacite/DataciteInfoSender.inc.php
- plugins/importexport/datacite/classes/DataciteExportDom.inc.php
- plugins/importexport/datacite/locale/en_US/common.xml
S. https://github.com/pkp/pkp-lib/issues/1543
> Datacite DOI automatic registration

- plugins/importexport/datacite/classes/DOIExportPlugin.inc.php
S. https://github.com/pkp/pkp-lib/issues/1558
> pkp/pkp-lib#1558 multiple DOI XML file registrations

- .gitignore
- plugins/blocks/authorBios/locale/sv_SE/locale.xml
- plugins/blocks/information/locale/sv_SE/locale.xml
- plugins/blocks/languageToggle/locale/sv_SE/locale.xml
- plugins/blocks/navigation/locale/sv_SE/locale.xml
- plugins/blocks/notification/locale/sv_SE/locale.xml
- plugins/blocks/readingTools/locale/sv_SE/locale.xml
- plugins/blocks/relatedItems/locale/sv_SE/locale.xml
- plugins/blocks/role/locale/sv_SE/locale.xml
- plugins/blocks/subscription/locale/sv_SE/locale.xml
- plugins/blocks/user/locale/sv_SE/locale.xml
More consistant phrasing and added a few new strings.
> Updated Swedish (sv_SE) translation

- plugins/importexport/medra/MedraExportPlugin.inc.php
- plugins/importexport/medra/MedraInfoSender.inc.php
- plugins/importexport/medra/classes/form/MedraSettingsForm.inc.php
- plugins/importexport/medra/locale/it_IT/locale.xml
- plugins/importexport/medra/scheduledTasks.xml
- plugins/importexport/medra/templates/settings.tpl
This PR supersedes #888 and #865
> Automatic DOI registration fro mEDRA plugin - updates

- plugins/importexport/medra/MedraInfoSender.inc.php
S. https://github.com/pkp/ojs/pull/891#discussion_r68659329
> fix indentation

- locale/it_IT/admin.xml
- locale/it_IT/default.xml
- locale/it_IT/editor.xml
- locale/it_IT/locale.xml
- locale/it_IT/manager.xml
- plugins/generic/dataverse/locale/it_IT/locale.xml
- plugins/generic/pln/locale/it_IT/locale.xml
- plugins/generic/stopForumSpam/locale/it_IT/locale.xml
- plugins/generic/usageStats/locale/it_IT/locale.xml
- plugins/reports/counter/locale/it_IT/ar1.xml
- plugins/reports/counter/locale/it_IT/jr1.xml
- plugins/reports/counter/locale/it_IT/locale.xml
in ojs/locale and in various plugins
> Italian translation update

- templates/about/index.tpl
Added id for better styling if it is necessary
> Added link id to editorialTeam page in about/index.tpl

- classes/article/ArticleGalleyDAO.inc.php
- classes/plugins/PubIdPlugin.inc.php
- controllers/tab/pubIds/form/PublicIdentifiersForm.inc.php
- locale/en_US/editor.xml
- plugins/oaiMetadataFormats/dc/tests/OAIMetadataFormat_DCTest.php
- plugins/pubIds/doi/DOIPubIdPlugin.inc.php
- plugins/pubIds/doi/classes/form/DOISettingsForm.inc.php
- plugins/pubIds/doi/js/DOISettingsFormHandler.js
- plugins/pubIds/doi/locale/en_US/locale.xml
- plugins/pubIds/doi/templates/doiAssign.tpl
- plugins/pubIds/doi/templates/doiSuffixEdit.tpl
- plugins/pubIds/doi/templates/settingsForm.tpl
- plugins/pubIds/urn/URNPubIdPlugin.inc.php
- plugins/pubIds/urn/classes/form/URNSettingsForm.inc.php
- plugins/pubIds/urn/js/URNSettingsFormHandler.js
- plugins/pubIds/urn/locale/en_US/locale.xml
- plugins/pubIds/urn/templates/settingsForm.tpl
- plugins/pubIds/urn/templates/urnAssign.tpl
- plugins/pubIds/urn/templates/urnSuffixEdit.tpl
After implementing the pub ids for OMP, some more code could be extracted into the library. Here the changed for OJS...
> Public identifiers refactoring

- classes/plugins/DOIPubIdExportPlugin.inc.php
- classes/template/TemplateManager.inc.php
- controllers/tab/settings/citations/form/CitationsForm.inc.php
- pages/issue/IssueHandler.inc.php
- pages/manager/SubscriptionHandler.inc.php
- pages/search/SearchHandler.inc.php
- plugins/generic/announcementFeed/AnnouncementFeedPlugin.inc.php
- plugins/generic/externalFeed/ExternalFeedPlugin.inc.php
- plugins/generic/lucene/LucenePlugin.inc.php
- plugins/generic/usageStats/UsageStatsPlugin.inc.php
- plugins/generic/webFeed/WebFeedPlugin.inc.php
- plugins/themes/default/DefaultThemePlugin.inc.php
- plugins/themes/default/js/main.js
- plugins/themes/default/styles/head.less
- plugins/themes/default/styles/helpers.less
- plugins/themes/default/styles/variables.less
- plugins/themes/default/version.xml
- styles/citationEditor.less
- templates/common/minifiedScripts.tpl
- templates/frontend/components/primaryNavMenu.tpl
- templates/frontend/pages/issueInterstitial.tpl
- templates/frontend/pages/search.tpl
Replaces https://github.com/pkp/ojs/pull/899
> pkp/pkp-lib#1468 Theme API overhaul

- locale/fr_CA/locale.xml
* following ojs-dev-2_4 updates introduced in #907
> fr_CA locale tiny update

- locale/pt_BR/admin.xml
- locale/pt_BR/author.xml
- locale/pt_BR/default.xml
- locale/pt_BR/editor.xml
- locale/pt_BR/emailTemplates.xml
- locale/pt_BR/locale.xml
- locale/pt_BR/manager.xml
- locale/pt_BR/submission.xml
removed obsolete keys, added translations received from Ronnie
pkp/pkp-lib#1582
> pt_BR locale update

- js/controllers/form/DOIPubIdExportFormHandler.js
- templates/common/minifiedScripts.tpl
Sorry, I've forgotten to add this JS handler to my first commit :-(
> pkp/pkp-lib#383 forgotten JS handler

- plugins/importexport/crossref/templates/index.tpl
- plugins/pubIds/doi/DOIPubIdPlugin.inc.php
- plugins/pubIds/doi/locale/en_US/locale.xml
- plugins/pubIds/doi/templates/doiAssign.tpl
- plugins/pubIds/doi/templates/doiSuffixEdit.tpl
- plugins/pubIds/urn/URNPubIdPlugin.inc.php
- plugins/pubIds/urn/locale/en_US/locale.xml
- plugins/pubIds/urn/templates/urnAssign.tpl
- plugins/pubIds/urn/templates/urnSuffixEdit.tpl
> 1457 layout fixes

- plugins/pubIds/doi/DOIPubIdPlugin.inc.php
- plugins/pubIds/doi/templates/settingsForm.tpl
- plugins/pubIds/urn/URNPubIdPlugin.inc.php
- plugins/pubIds/urn/templates/settingsForm.tpl
- plugins/pubIds/urn/templates/urnSuffixEdit.tpl
changes for OJS according to the code review of this PR: https://github.com/pkp/omp/pull/306
> pub ids fixes

- classes/article/ArticleGalleyDAO.inc.php
> sql quote sign fix

- plugins/importexport/native/NativeImportDom.inc.php
Resolves https://github.com/pkp/pkp-lib/issues/1653
> pkp/pkp-lib#1653: Default locale for article copyright holder in NativeImportDOM

- plugins/generic/objectsForReview/styles/objectsForReview.css
> pkp/pkp-lib#1665 adaptable OFR cover image size

- plugins/metadata/dc11/filter/Dc11SchemaArticleAdapter.inc.php
s. https://github.com/pkp/pkp-lib/issues/1691
> pkp/pkp-lib#1691 OAI dc:rights

- classes/article/ArticleGalleyDAO.inc.php
- classes/article/PublishedArticleDAO.inc.php
- classes/issue/IssueDAO.inc.php
- plugins/importexport/crossref/templates/index.tpl
For some reason, in one query case it was important to have the 'i.published = 1' at the very beginning of WHERE clause... :-O
And a typo...
> SQL fixes to get only published objects with DOIs

- locale/en_US/manager.xml
- locale/en_US/submission.xml
> updated locale: en_US

- plugins/importexport/crossref/CrossRefExportPlugin.inc.php
S. https://github.com/pkp/pkp-lib/issues/1749
> remove PHP 5.3 code from OJS 2.4.8-1

- plugins/importexport/crossref/CrossRefExportPlugin.inc.php
S. https://github.com/pkp/pkp-lib/issues/1749 
This is commit for the ojs-dev-2_4 branch
> pkp/pkp-lib#1749 remove php 5.3 code

- controllers/tab/issueEntry/IssueEntryTabHandler.inc.php
@asmecher, could this fix be committed/merged like this, without an issue, when all these OJS tests start to work again... :-) Thanks a lot!
> fix article pub id assignment when scheduling

- controllers/grid/articleGalleys/ArticleGalleyGridHandler.inc.php
- controllers/tab/workflow/WorkflowTabHandler.inc.php
- locale/en_US/locale.xml
S. https://github.com/pkp/pkp-lib/issues/1710
> banner notifications

- plugins/generic/dataverse/DataversePlugin.inc.php
DataVerse plugin does not support proxy right now. Now it does.
Can someone review this and include this maybe? :)
> Proxy support for DataVerse

- templates/common/header.tpl
*ssshhhhhhh* I don't think anyone's notice. ;)
> Fix future issue link in primary nav menu

- plugins/importexport/doaj/classes/DOAJExportDom.inc.php
s. https://github.com/pkp/pkp-lib/issues/1690
> pkp/pkp-lib#1690 consider article locale for DOAJ export

- locale/ar_IQ/emailTemplates.xml
- rt/ar_IQ/Agriculture.xml
- rt/ar_IQ/Art_Architecture.xml
- rt/ar_IQ/Astrophysics.xml
- rt/ar_IQ/Biology.xml
- rt/ar_IQ/Business.xml
- rt/ar_IQ/Chemistry.xml
- rt/ar_IQ/Cognitive_Science.xml
- rt/ar_IQ/Computer_Science.xml
- rt/ar_IQ/Economics.xml
- rt/ar_IQ/Education.xml
- rt/ar_IQ/Environment.xml
- rt/ar_IQ/General_Science.xml
- rt/ar_IQ/Generic.xml
- rt/ar_IQ/Humanities.xml
- rt/ar_IQ/Life_Sciences.xml
- rt/ar_IQ/Mathematics.xml
- rt/ar_IQ/Music.xml
- rt/ar_IQ/Physics.xml
- rt/ar_IQ/Social_Sciences.xml
Retrieving reading tools for Arabic language after OJS 3.0.0.0 release.
> Adding reading tools for OJS3 Arabic locale

- classes/issue/IssueDAO.inc.php
- plugins/importexport/native/filter/ArticleNativeXmlFilter.inc.php
- plugins/importexport/native/filter/IssueNativeXmlFilter.inc.php
- plugins/importexport/native/filter/NativeFilterHelper.inc.php
- plugins/importexport/native/filter/NativeXmlArticleFilter.inc.php
- plugins/importexport/native/filter/NativeXmlIssueFilter.inc.php
- plugins/importexport/native/locale/en_US/locale.xml
- plugins/importexport/native/native.xsd
- tests/data/60-content/issue.xml
This is the cherry-pick of the issue_identification changes for native import/export to ojs-stable-3_0_0. S. d) here: https://github.com/pkp/pkp-lib/issues/1709
@asmecher, could you please just double check if the reference to the submodule lensGalley is correct for this branch?
> pkp/pkp-lib#1709 implement issue_identification element for native import/export

- locale/tr_TR/manager.xml
System has some lack of translates. When I use http://www.suhad.org/suhad , i will help the OJS 3.0 Turkish language package.
> Add tr_TR language

- plugins/importexport/datacite/classes/DataciteExportDom.inc.php
Resolves pkp/pkp-lib#1877 with preference suggested by DataCite's Technical Director.
> pkp/pkp-lib#1877: DataCite metadata uses Journal Title as the Publisher.

- plugins/importexport/native/filter/ArticleNativeXmlFilter.inc.php
- plugins/importexport/native/filter/NativeXmlArticleFilter.inc.php
- plugins/importexport/native/native.xsd
S. j) here: https://github.com/pkp/pkp-lib/issues/1709
> pkp/pkp-lib#1709 consider article pages in native import/export

- controllers/grid/articleGalleys/ArticleGalleyGridHandler.inc.php
https://github.com/pkp/pkp-lib/issues/1796
> ability to reorder galley display order #1796

- classes/plugins/DOIPubIdExportPlugin.inc.php
- classes/plugins/PubObjectsExportPlugin.inc.php
- plugins/importexport/crossref/CrossRefExportPlugin.inc.php
- plugins/importexport/crossref/CrossrefInfoSender.inc.php
- plugins/importexport/datacite/DataciteExportPlugin.inc.php
- plugins/importexport/datacite/DataciteInfoSender.inc.php
- plugins/importexport/doaj/DOAJExportPlugin.inc.php
- plugins/importexport/medra/MedraExportPlugin.inc.php
- plugins/importexport/medra/MedraInfoSender.inc.php
- plugins/importexport/native/NativeImportExportPlugin.inc.php
S. i) here: https://github.com/pkp/pkp-lib/issues/1709
(This PR considers also other export plugins)
> pkp/pkp-lib#1709 provide export XML for download

- classes/plugins/DOIPubIdExportPlugin.inc.php
- classes/plugins/PubObjectsExportPlugin.inc.php
- plugins/importexport/crossref/CrossRefExportPlugin.inc.php
- plugins/importexport/crossref/CrossrefInfoSender.inc.php
- plugins/importexport/datacite/DataciteExportPlugin.inc.php
- plugins/importexport/datacite/DataciteInfoSender.inc.php
- plugins/importexport/doaj/DOAJExportPlugin.inc.php
- plugins/importexport/medra/MedraExportPlugin.inc.php
- plugins/importexport/medra/MedraInfoSender.inc.php
- plugins/importexport/native/NativeImportExportPlugin.inc.php
s. i) here https://github.com/pkp/pkp-lib/issues/1709
this is a cherry-pick to ojs-stable-3_0_0
> 1709fix download xml stable

- plugins/generic/dataverse/DataversePlugin.inc.php
Resolves pkp/pkp-lib#1894, but the use of the new constant is a TODO,
> pkp/pkp-lib#1894: Define specific Dataverse error message to prevent hijacking of NOTIFICATION_TYPE_ERROR

- classes/plugins/PubObjectsExportPlugin.inc.php
s. https://github.com/pkp/pkp-lib/issues/1956
> pkp/pkp-lib#1956 XML export validation message encoding

- classes/article/Article.inc.php
- classes/article/ArticleDAO.inc.php
- classes/controllers/grid/issues/IssueGridHandler.inc.php
- classes/install/Upgrade.inc.php
- classes/issue/Issue.inc.php
- classes/issue/IssueDAO.inc.php
- controllers/grid/issues/form/IssueForm.inc.php
- controllers/modals/submissionMetadata/form/SubmissionMetadataViewForm.inc.php
- controllers/tab/issueEntry/IssueEntryTabHandler.inc.php
- dbscripts/xml/upgrade.xml
- dbscripts/xml/upgrade/3.0.0_issue_settings.xml
- dbscripts/xml/upgrade/3.0.0_submission_settings.xml
- plugins/importexport/native/filter/IssueNativeXmlFilter.inc.php
- plugins/importexport/native/filter/NativeXmlIssueFilter.inc.php
- plugins/importexport/native/native.xsd
- templates/frontend/objects/article_details.tpl
- templates/frontend/objects/article_summary.tpl
- templates/frontend/objects/issue_summary.tpl
- templates/frontend/objects/issue_toc.tpl
s. https://github.com/pkp/pkp-lib/issues/1934
> I1934 stable

- plugins/importexport/users/UserImportExportPlugin.inc.php
- plugins/importexport/users/locale/ar_IQ/locale.xml
- plugins/importexport/users/locale/de_DE/locale.xml
- plugins/importexport/users/locale/el_GR/locale.xml
- plugins/importexport/users/locale/en_US/locale.xml
- plugins/importexport/users/locale/es_ES/locale.xml
- plugins/importexport/users/locale/fa_IR/locale.xml
- plugins/importexport/users/locale/fr_CA/locale.xml
- plugins/importexport/users/locale/hr_HR/locale.xml
- plugins/importexport/users/locale/it_IT/locale.xml
- plugins/importexport/users/locale/ja_JP/locale.xml
- plugins/importexport/users/locale/pt_BR/locale.xml
- plugins/importexport/users/locale/tr_TR/locale.xml
- plugins/importexport/users/locale/vi_VN/locale.xml
- plugins/importexport/users/locale/zh_TW/locale.xml
s. https://github.com/pkp/pkp-lib/issues/1601
> pkp/pkp-lib#1601 CLI for UsersImportExportPlugin

- locale/pt_BR/editor.xml
- locale/pt_BR/locale.xml
- plugins/importexport/crossref/locale/pt_BR/locale.xml
- plugins/pubIds/doi/locale/pt_BR/locale.xml
- plugins/themes/default/locale/pt_BR/locale.xml
* updates received from Ronnie
> pt_BR locale updates

- tools/runScheduledTasks.php
> Fix the modern constructor sytnax call for ScheduledTaskTool

- classes/install/Upgrade.inc.php
- dbscripts/xml/upgrade/3.0.0_postupgrade_metrics.xml
- dbscripts/xml/upgrade/3.0.1_update.xml
This fixes two things:
1) s. https://github.com/pkp/pkp-lib/issues/1934#issuecomment-265501437
2) s. https://github.com/pkp/pkp-lib/issues/2062
> Fix SQL statements

- plugins/importexport/crossref/classes/CrossRefExportDom.inc.php
Resolves pkp/pkp-lib#333.
New `Submission::getPageArray()` is used to parse the pages into ranges.  The first range is placed in `first_page` / `last_page`, with any additional ranges put into `other_pages`.
> Improve CrossRef pages element to identify first page range and other pages

- plugins/importexport/crossref/filter/ArticleCrossrefXmlFilter.inc.php
- plugins/importexport/crossref/filter/IssueCrossrefXmlFilter.inc.php
- plugins/importexport/datacite/DataciteExportPlugin.inc.php
- plugins/importexport/datacite/filter/DataciteXmlFilter.inc.php
- plugins/importexport/doaj/filter/DOAJXmlFilter.inc.php
- plugins/importexport/medra/filter/ArticleMedraXmlFilter.inc.php
- plugins/importexport/medra/filter/IssueMedraXmlFilter.inc.php
- plugins/importexport/native/filter/NativeFilterHelper.inc.php
s. https://github.com/pkp/pkp-lib/issues/2074
> XML and URL escape

- plugins/importexport/crossref/filter/ArticleCrossrefXmlFilter.inc.php
- plugins/importexport/crossref/filter/IssueCrossrefXmlFilter.inc.php
- plugins/importexport/datacite/DataciteExportPlugin.inc.php
- plugins/importexport/datacite/filter/DataciteXmlFilter.inc.php
- plugins/importexport/doaj/filter/DOAJXmlFilter.inc.php
- plugins/importexport/medra/filter/ArticleMedraXmlFilter.inc.php
- plugins/importexport/medra/filter/IssueMedraXmlFilter.inc.php
- plugins/importexport/medra/filter/O4DOIXmlFilter.inc.php
- plugins/importexport/native/filter/ArticleNativeXmlFilter.inc.php
- plugins/importexport/native/filter/ArtworkFileNativeXmlFilter.inc.php
- plugins/importexport/native/filter/IssueGalleyNativeXmlFilter.inc.php
- plugins/importexport/native/filter/IssueNativeXmlFilter.inc.php
- plugins/importexport/native/filter/NativeFilterHelper.inc.php
- plugins/importexport/native/filter/SupplementaryFileNativeXmlFilter.inc.php
s. https://github.com/pkp/pkp-lib/issues/2074
> pkp/pkp-lib#2074 Update use of createElement and createElementNS

- locale/de_DE/locale.xml
a few updates, also closing pkp/pkp-lib#2081
> de_DE locale update

- plugins/importexport/medra/filter/ArticleMedraXmlFilter.inc.php
- plugins/importexport/medra/filter/IssueMedraXmlFilter.inc.php
s. https://github.com/pkp/pkp-lib/issues/2074
> pkp/pkp-lib#2074 remove double escape for mEDRA URLs

- plugins/citationFormats/abnt/citation.tpl
- plugins/pubIds/doi/DOIPubIdPlugin.inc.php
s. https://github.com/pkp/pkp-lib/issues/1901
> pkp/pkp-lib#1901 new DOI display guidelines

- templates/admin/contextSettings.tpl
- templates/controllers/grid/articleGalleys/form/articleGalleyForm.tpl
- templates/controllers/grid/issueGalleys/form/issueGalleyForm.tpl
- templates/controllers/grid/issues/form/issueForm.tpl
- templates/controllers/grid/settings/sections/form/sectionForm.tpl
- templates/controllers/tab/settings/masthead/form/mastheadForm.tpl
- templates/submission/form/section.tpl
s. https://github.com/pkp/ojs/pull/1080
Just to check if this will work...
> pkp/pkp-lib#1772 Add required and aria-required attributes to form fields

- plugins/themes/default/styles/index.less
- plugins/themes/default/styles/rtl.less
- registry/locales.xml
s. https://github.com/pkp/ojs/pull/1143
from issue: https://github.com/pkp/pkp-lib/issues/1906
> Add support for rtl locales

- plugins/citationFormats/bibtex/citation.tpl
> pkp/pkp-lib#2119: Add comma after pages in BibTeX citation.

- plugins/blocks/languageToggle/LanguageToggleBlockPlugin.inc.php
- templates/controllers/tab/settings/siteSetup/form/siteSetupForm.tpl
s. https://github.com/pkp/ojs/pull/1097
from issue: https://github.com/pkp/pkp-lib/issues/1859
> pkp/pkp-lib#1859 Fix site-wide sidebar control.

- classes/plugins/PubObjectsExportPlugin.inc.php
- plugins/importexport/native/NativeImportExportPlugin.inc.php
- plugins/importexport/native/filter/IssueGalleyNativeXmlFilter.inc.php
- plugins/importexport/native/filter/IssueNativeXmlFilter.inc.php
s. https://github.com/pkp/pkp-lib/issues/2117
> pkp/pkp-lib#2117 Display native export validation errors

- plugins/importexport/native/filter/IssueGalleyNativeXmlFilter.inc.php
- plugins/importexport/native/filter/IssueNativeXmlFilter.inc.php
s. https://github.com/pkp/pkp-lib/issues/2138
> pkp/pkp-lib#2138 Use %Y-%m-%d instead of %F in strftime

- docs/README
- docs/UPGRADE
Update README to note the GeoLiteCity database option.  Update UPGRADE to clarify the Full Package install process.
Resolves pkp/pkp-lib#2156 for master
> pkp/pkp-lib#2156: install/upgrade doc cleanup

- docs/README
- docs/UPGRADE
Update README to note the GeoLiteCity database option.  Update UPGRADE to clarify the Full Package install process.
Resolves pkp/pkp-lib#2156 for dev-2_4
> pkp/pkp-lib#2156: cleanup install/upgrade docs

- plugins/importexport/crossref/classes/form/CrossRefSettingsForm.inc.php
Resolves pkp/pkp-lib#2164 for 2.x dev
> pkp/pkp-lib#2164: Change CrossRef Settings Form unregistered articles link.

- classes/article/ArticleGalley.inc.php
s. https://github.com/pkp/pkp-lib/issues/2167
> pkp/pkp-lib#2167 fix assoc type in getViews for article galleys

- dbscripts/xml/upgrade.xml
- dbscripts/xml/upgrade/3.0.0_review_method.xml
s. https://github.com/pkp/pkp-lib/issues/2195
> pkp/pkp-lib#2195 set double-blind when review method is missing

- plugins/generic/htmlArticleGalley/locale/pt_BR/locale.xml
- plugins/generic/recommendByAuthor/locale/pt_BR/locale.xml
> translation to pt_BR

- classes/install/Upgrade.inc.php
- dbscripts/xml/upgrade/3.0.0_postupgrade_galley_files.xml
- dbscripts/xml/upgrade/3.0.0_postupgrade_metrics.xml
- dbscripts/xml/upgrade/3.0.0_update.xml
s. https://github.com/pkp/pkp-lib/issues/2208
> pkp/pkp-lib#2208 fix PostgreSQL UPDATE statements

- classes/install/Upgrade.inc.php
- classes/plugins/DOIPubIdExportPlugin.inc.php
- classes/plugins/PubObjectsExportPlugin.inc.php
- dbscripts/xml/upgrade.xml
- plugins/importexport/crossref/CrossRefExportPlugin.inc.php
- plugins/importexport/crossref/templates/index.tpl
- plugins/importexport/datacite/DataciteExportPlugin.inc.php
- plugins/importexport/datacite/templates/index.tpl
- plugins/importexport/doaj/DOAJExportPlugin.inc.php
- plugins/importexport/doaj/DOAJInfoSender.inc.php
- plugins/importexport/doaj/classes/form/DOAJSettingsForm.inc.php
- plugins/importexport/doaj/filter/DOAJJsonFilter.inc.php
- plugins/importexport/doaj/filter/filterConfig.xml
- plugins/importexport/doaj/locale/en_US/locale.xml
- plugins/importexport/doaj/scheduledTasks.xml
- plugins/importexport/doaj/templates/index.tpl
- plugins/importexport/doaj/templates/settingsForm.tpl
- plugins/importexport/medra/MedraExportPlugin.inc.php
- plugins/importexport/medra/templates/index.tpl
s. https://github.com/pkp/pkp-lib/issues/850
> DOAJ CRUD API

- plugins/pubIds/doi/locale/de_DE/locale.xml
Minimal change concerning language support
>  	geändert:       plugins/pubIds/doi/locale/de_DE/locale.xml

- templates/user/register.tpl
Resolves pkp/pkp-lib#2232 for OJS 2.4.x dev.
> pkp/pkp-lib#2232: Move static call to Validation::isLoggedIn() from Smarty if to Smarty variable assignment.

- locale/sv_SE/admin.xml
> Swedish translation of /locale/sv_SE/admin.xml

- classes/install/Upgrade.inc.php
- dbscripts/xml/upgrade.xml
- dbscripts/xml/upgrade/3.0.0_stage_assignments.xml
s. https://github.com/pkp/pkp-lib/issues/2201
> pkp/pkp-lib#2201 no reviewers into stage_assignments

- templates/controllers/modals/submissionMetadata/form/issueEntrySubmissionReviewForm.tpl
s. https://github.com/pkp/pkp-lib/issues/2083
> 2083 stable

- templates/controllers/modals/submissionMetadata/form/issueEntrySubmissionReviewForm.tpl
s. https://github.com/pkp/pkp-lib/issues/2083
> pkp/pkp-lib#2083 consider readOnly for cover image upload

- classes/article/ArticleDAO.inc.php
- classes/install/Upgrade.inc.php
- dbscripts/xml/ojs_schema.xml
- dbscripts/xml/upgrade.xml
- dbscripts/xml/upgrade/3.0.0_preupdate_commentsToEditor.xml
- plugins/importexport/native/sample.xml
s. https://github.com/pkp/pkp-lib/issues/1873
> migrate comments for the editor

- locale/da_DK/admin.xml
- locale/da_DK/author.xml
- locale/da_DK/default.xml
- locale/da_DK/editor.xml
- locale/da_DK/emailTemplates.xml
- locale/da_DK/locale.xml
- locale/da_DK/manager.xml
- locale/da_DK/submission.xml
- plugins/blocks/developedBy/locale/da_DK/locale.xml
- plugins/blocks/relatedItems/locale/da_DK/locale.xml
- plugins/citationFormats/abnt/locale/da_DK/locale.xml
- plugins/generic/browse/locale/da_DK/locale.xml
- plugins/generic/webFeed/locale/da_DK/locale.xml
- plugins/importexport/crossref/locale/da_DK/locale.xml
- plugins/importexport/medra/locale/da_DK/locale.xml
- plugins/importexport/pubIds/locale/da_DK/locale.xml
- plugins/importexport/users/locale/da_DK/locale.xml
- plugins/paymethod/manual/locale/da_DK/emailTemplates.xml
- plugins/paymethod/paypal/locale/da_DK/locale.xml
- plugins/pubIds/doi/locale/da_DK/locale.xml
- plugins/reports/articles/locale/da_DK/locale.xml
- plugins/themes/default/locale/da_DK/locale.xml
* update from Danish translator(s)
* removed untranslated elements and translations of independently hosted plugins
> da_DK locale update

- locale/da_DK/emailTemplates.xml
this was still left over from the last-minute commit during the 3.0.2 release
> da_DK locale: email update

- classes/install/Upgrade.inc.php
- dbscripts/xml/upgrade.xml
- dbscripts/xml/upgrade/3.0.0_reviewer_files.xml
s. https://github.com/pkp/pkp-lib/issues/2173
This fixes problem 2 -- reviewer files
> pkp/pkp-lib#2173 (2) fix migrated reviewer files

- classes/plugins/PubObjectsExportPlugin.inc.php
- locale/en_US/manager.xml
- plugins/importexport/crossref/CrossRefExportPlugin.inc.php
- plugins/importexport/crossref/templates/index.tpl
- plugins/importexport/datacite/DataciteExportPlugin.inc.php
- plugins/importexport/datacite/filter/DataciteXmlFilter.inc.php
- plugins/importexport/datacite/templates/index.tpl
- plugins/importexport/doaj/DOAJExportPlugin.inc.php
- plugins/importexport/doaj/templates/index.tpl
- plugins/importexport/medra/filter/IssueMedraXmlFilter.inc.php
- plugins/importexport/medra/templates/index.tpl
s. https://github.com/pkp/pkp-lib/issues/1955
> pkp/pkp-lib#1955 no XML validation option for the export plugins

- classes/install/Upgrade.inc.php
- dbscripts/xml/upgrade.xml
- dbscripts/xml/upgrade/3.0.0_reviewer_files.xml
s. number 2 here: https://github.com/pkp/pkp-lib/issues/2173
> Ojs stable 3 0 2

- locale/fr_CA/locale.xml
- plugins/pubIds/doi/locale/fr_CA/locale.xml
- plugins/themes/default/locale/fr_CA/locale.xml
> French locale (cherry-picked from #1243)

- .gitignore
Fixed the .gitignore rule so it doesn't ignore lib/pkp/classes/config/Config.inc.php.
> pkp/pkplib#2285 Fixed greedy .gitignore rule

- .gitignore
Fixed the .gitignore rule so it doesn't ignore lib/pkp/classes/config/Config.inc.php.
> pkp/pkp-lib#2285 Fixed greedy .gitignore rule

- classes/install/Upgrade.inc.php
- dbscripts/xml/upgrade.xml
s. https://github.com/pkp/pkp-lib/issues/2295
> pkp/pkp-lib#2295 upgrade of old statistics to 3.x

- locale/de_DE/manager.xml
thanks for reporting this, @CFanselow
> de_DE locale: updated translation, fixed error

- plugins/importexport/native/NativeImportExportPlugin.inc.php
s. https://github.com/pkp/pkp-lib/issues/2319
> pkp/pkp-lib#2319 fix CLI native import

- dbscripts/xml/upgrade/3.1.0_update.xml
s. 4) here: https://github.com/pkp/pkp-lib/issues/2173
> pkp/pkp-lib#2173 (4) migrate date_response_due

- classes/plugins/PubIdPlugin.inc.php
- plugins/pubIds/doi/classes/form/DOISettingsForm.inc.php
- plugins/pubIds/doi/locale/en_US/locale.xml
- plugins/pubIds/doi/templates/settingsForm.tpl
- plugins/pubIds/urn/templates/settingsForm.tpl
s. https://github.com/pkp/pkp-lib/issues/2342
> pkp/pkp-lib#2342 assign DOIs to all published objects button

- templates/comment/comments.tpl
> pkp/pkp-lib#2348: Fix public profile links from usernames in comments.

- plugins/importexport/crossref/classes/CrossRefExportDom.inc.php
This is a cherry-pick from ojs-dev-2_4, in order for this to be in the next ojs release...
> port fix for roman numerals in Crossref

- classes/plugins/PubObjectsExportPlugin.inc.php
- plugins/importexport/native/NativeImportExportPlugin.inc.php
s. last commits here: https://github.com/pkp/pkp-lib/issues/2101
> pkp/pkp-lib#2101 Clean up (partially) error handling in import/export plugins

- classes/install/Upgrade.inc.php
- classes/submission/reviewer/ReviewerSubmission.inc.php
- classes/submission/reviewer/ReviewerSubmissionDAO.inc.php
- dbscripts/xml/upgrade.xml
- dbscripts/xml/upgrade/3.1.0_preupdate_review_assignments.xml
- locale/ar_IQ/locale.xml
- locale/ca_ES/locale.xml
- locale/cs_CZ/locale.xml
- locale/da_DK/locale.xml
- locale/de_DE/locale.xml
- locale/en_US/locale.xml
- locale/es_ES/locale.xml
- locale/eu_ES/locale.xml
- locale/fi_FI/locale.xml
- locale/fr_CA/locale.xml
- locale/hr_HR/locale.xml
- locale/id_ID/locale.xml
- locale/it_IT/locale.xml
- locale/nb_NO/locale.xml
- locale/nl_NL/locale.xml
- locale/pt_BR/locale.xml
- locale/pt_PT/locale.xml
- locale/ru_RU/locale.xml
- locale/sr_SR/locale.xml
- locale/sv_SE/locale.xml
- locale/tr_TR/locale.xml
- locale/uk_UA/locale.xml
- locale/zh_CN/locale.xml
s. number 3) here: https://github.com/pkp/pkp-lib/issues/2173
> pkp/pkp-lib#2173 (3) remove review assignment cancel function and migrated cancelled review assignments

- plugins/themes/vanilla/vanilla.css
I noticed some inconsistency in the Vanilla theme, so here's a minor fix of the theme's CSS. (Don't know how many use this, but on our server we have several journals who use this theme.)
> Corrected some glitches affecting issue view in vanilla theme

- classes/install/Upgrade.inc.php
- dbscripts/xml/upgrade.xml
- dbscripts/xml/upgrade/3.0.2_update.xml
s. https://github.com/pkp/pkp-lib/issues/2392
> 2392 stable

- plugins/generic/tinymce/TinyMCEPlugin.inc.php
Resolves pkp/pkp-lib#2220 for 2.4.x dev.
> pkp/pkp-lib#2220: Block TinyMCE jbimages plugin if user is not logged in

- plugins/generic/tinymce/TinyMCEPlugin.inc.php
Resolves pkp/pkp-lib#2220 for 2.4.8 stable.
> pkp/pkp-lib#2220: Block TinyMCE jbimages plugin if user is not logged in.

- locale/ar_IQ/admin.xml
- locale/ar_IQ/editor.xml
- locale/ar_IQ/manager.xml
- plugins/pubIds/doi/locale/ar_IQ/locale.xml
Some minor updates to Arabic language files.
> Updates to Arabic locale before OJS3.1

- classes/journal/SectionDAO.inc.php
Part of cleanup for pkp/pkp-lib#2449.
> pkp/pkp-lib#2449: Document missing parameters and return types in SectionDAO

- plugins/importexport/native/NativeImportExportDeployment.inc.php
- plugins/importexport/native/NativeImportExportPlugin.inc.php
- plugins/importexport/native/filter/NativeXmlArticleFilter.inc.php
- plugins/importexport/native/filter/NativeXmlIssueFilter.inc.php
- plugins/importexport/native/templates/results.tpl
> pkp/pkp-lib#2523: Remove sections added by Native Import if error occurred

- plugins/importexport/native/filter/NativeXmlIssueFilter.inc.php
Fixes unset object problem introduced by pkp/ojs#1385 as part of pkp/pkp-lib#2526.
> pkp/pkp-lib#2526: Ensure $deployment is available for Native XML Issue import warnings

- classes/plugins/DOIPubIdExportPlugin.inc.php
- classes/plugins/PubObjectsExportPlugin.inc.php
- plugins/importexport/doaj/DOAJInfoSender.inc.php
- plugins/importexport/doaj/filter/DOAJJsonFilter.inc.php
- plugins/importexport/doaj/locale/en_US/locale.xml
s. https://github.com/pkp/pkp-lib/issues/2543
> pkp/pkp-lib#2543 AcronPlugin::parseCronTab for DOAJ plugin

- templates/sectionEditor/submissionEventLogEntry.tpl
s. https://github.com/pkp/pkp-lib/issues/2547
> pkp/pkp-lib#2547: translate event log message in event details page

- dbscripts/xml/upgrade.xml
s. https://github.com/pkp/pkp-lib/issues/2542
> pkp/pkp-lib#2542 update Password Reset e-mail template

- dbscripts/xml/upgrade/3.1.0_update.xml
s. https://github.com/pkp/pkp-lib/issues/2537
> pkp/pkp-lib#2537 article_galley_settings migration

- classes/security/authorization/ReviewStageAccessPolicy.inc.php
- pages/reviewer/ReviewerHandler.inc.php
s. https://github.com/pkp/pkp-lib/issues/2481
> pkp/pkp-lib#2481 Fix reviewer access to declined submissions

- classes/install/Upgrade.inc.php
- dbscripts/xml/upgrade.xml
s. https://github.com/pkp/pkp-lib/issues/2501
> pkp/pkp-lib#2501 subject and subjectClass migration

- plugins/blocks/developedBy/locale/fi_FI/locale.xml
- plugins/blocks/information/locale/fi_FI/locale.xml
- plugins/blocks/languageToggle/locale/fi_FI/locale.xml
- plugins/gateways/resolver/locale/fi_FI/locale.xml
- plugins/generic/dublinCoreMeta/locale/fi_FI/locale.xml
- plugins/generic/googleScholar/locale/fi_FI/locale.xml
@mtub finnish locales for multiple plugins...
> Finnish locales for multiple plugins

- classes/oai/ojs/OAIDAO.inc.php
s. https://github.com/pkp/pkp-lib/issues/2566
> pkp/pkp-lib#2569 OAI fixes

- classes/controllers/grid/issues/IssueGridHandler.inc.php
s. https://github.com/pkp/pkp-lib/issues/2572
> pkp/pkp-lib#2572 publishIssue and unpublishIssue hook for IssueGridHandler

- classes/oai/ojs/OAIDAO.inc.php
s. https://github.com/pkp/pkp-lib/issues/2566
> pkp/pkp-lib#2566 OAI fixes

- locale/de_DE/editor.xml
- locale/de_DE/locale.xml
- locale/de_DE/manager.xml
- plugins/generic/backup/locale/de_DE/locale.xml
- plugins/generic/backup/locale/en_US/locale.xml
- plugins/generic/dublinCoreMeta/locale/de_DE/locale.xml
- plugins/generic/dublinCoreMeta/locale/en_US/locale.xml
- plugins/generic/googleScholar/locale/de_DE/locale.xml
- plugins/generic/googleScholar/locale/en_US/locale.xml
- plugins/generic/lucene/locale/de_DE/locale.xml
- plugins/generic/openAIRE/locale/de_DE/locale.xml
- plugins/generic/openAIRE/locale/en_US/locale.xml
- plugins/generic/usageEvent/locale/de_DE/locale.xml
- plugins/generic/webFeed/locale/de_DE/locale.xml
- plugins/importexport/crossref/locale/de_DE/locale.xml
- plugins/importexport/datacite/locale/de_DE/locale.xml
- plugins/importexport/doaj/locale/de_DE/locale.xml
- plugins/importexport/medra/locale/de_DE/locale.xml
- plugins/importexport/native/locale/de_DE/locale.xml
- plugins/importexport/users/locale/de_DE/locale.xml
- plugins/pubIds/doi/locale/de_DE/locale.xml
- plugins/pubIds/doi/locale/en_US/locale.xml
- plugins/pubIds/urn/locale/de_DE/locale.xml
- plugins/themes/default/locale/de_DE/locale.xml
> pkp/pkp-lib#2585 update OJS 3 de_DE locale

- plugins/blocks/information/locale/fr_CA/locale.xml
- plugins/importexport/native/locale/fr_CA/locale.xml
-block/../../../locale.xml: wording
-importexport/../../../local.xml: all new file, adding 13 keys
> pkp/pkp-lib#2602 Small update for fr_CA translation plugins

- locale/en_US/submission.xml
Just a minor tidy up of XML syntax.
> Correcting whitespace between attribute and value in XML

- classes/user/UserAction.inc.php
It is not possible to merge users anymore since the renaming of methods in `classes/subscription/IndividualSubscriptionDAO.inc.php` (pkp/ojs@70ddecd).
Maybe a similar glitch on https://github.com/pkp/ojs/blob/master/classes/journal/JournalDAO.inc.php#L87 ?
> Fix user merge on master

- classes/comment/form/CommentForm.inc.php
- classes/user/form/RegistrationForm.inc.php
- config.TEMPLATE.inc.php
Resolves pkp/pkp-lib#2608, requires https://github.com/pkp/pkp-lib/pull/2609.
> pkp/pkp-lib#2608: Enable ReCAPTCHA v2 as an option 

- plugins/importexport/crossref/locale/es_ES/locale.xml
Requested here:
https://forum.pkp.sfu.ca/t/2-4-8-2-crossref-plugin-error/32368/8
Translation done by @jordilacruz
(original file https://pad.riseup.net/p/ojs01)
> Translation for import/export CrossRef plugin (2.4.8)

- classes/issue/Issue.inc.php
Think we're safe to remove this.
> Remove deprecated getAuthorString method from Issue.inc.php

- pages/article/ArticleHandler.inc.php
s. https://github.com/pkp/pkp-lib/issues/2634#issuecomment-316370448
> pkp/pkp-lib#2634 add fileId to the ArticleHandler::downloadFile hook

- locale/da_DK/manager.xml
- locale/es_ES/default.xml
- locale/es_ES/editor.xml
- locale/es_ES/emailTemplates.xml
- locale/es_ES/locale.xml
- locale/es_ES/manager.xml
- locale/es_ES/submission.xml
- locale/sr_RS@cyrillic/locale.xml
- locale/sr_RS@latin/locale.xml
- plugins/auth/ldap/locale/en_US/locale.xml
- plugins/auth/ldap/locale/es_ES/locale.xml
- plugins/citationFormats/abnt/locale/es_ES/locale.xml
- plugins/generic/backup/locale/es_ES/locale.xml
- plugins/generic/driver/locale/es_ES/locale.xml
- plugins/generic/dublinCoreMeta/locale/es_ES/locale.xml
- plugins/generic/externalFeed/locale/es_ES/locale.xml
- plugins/importexport/crossref/locale/es_ES/locale.xml
- plugins/importexport/datacite/locale/es_ES/locale.xml
- plugins/importexport/doaj/locale/es_ES/locale.xml
- plugins/importexport/medra/locale/es_ES/locale.xml
- plugins/importexport/native/locale/es_ES/locale.xml
- plugins/importexport/sample/locale/es_ES/locale.xml
- plugins/importexport/users/locale/es_ES/locale.xml
- plugins/paymethod/manual/locale/es_ES/locale.xml
- plugins/paymethod/paypal/locale/es_ES/locale.xml
updates received from Marc et al. at UAB for pkp/pkp-lib#2725 
see https://pkp.sfu.ca/wiki/index.php?title=OJS:_Spanish_(es_ES)
> pkp/pkp-lib#2725 es_ES locale update

- docs/dev/RELEASE
- tools/buildpkg.sh
@asmecher is this what you were looking for regarding building JS for release packages?
> Run webpack during build script

- dbscripts/xml/upgrade/3.1.0_update_a.xml
- plugins/importexport/datacite/DataciteExportPlugin.inc.php
- plugins/importexport/doaj/DOAJExportPlugin.inc.php
- plugins/importexport/doaj/DOAJInfoSender.inc.php
- plugins/importexport/doaj/filter/DOAJJsonFilter.inc.php
- plugins/importexport/doaj/filter/filterConfig.xml
s. https://github.com/pkp/pkp-lib/issues/2543#issuecomment-316775198
> article by article DOAJ registration

- classes/install/Upgrade.inc.php
s. https://github.com/pkp/pkp-lib/issues/2752
> pkp/pkp-lib#2753 fix enabledSitePlugins upgrade function

- templates/frontend/objects/article_details.tpl
- templates/frontend/objects/issue_toc.tpl
s. https://github.com/pkp/pkp-lib/issues/2770
> pkp/pkp-lib#2770 display only assigned DOIs in the preview

- pages/issue/IssueHandler.inc.php
> fix a parameter for subscribedUser function

- classes/install/Upgrade.inc.php
- dbscripts/xml/upgrade.xml
- dbscripts/xml/upgrade/3.0.0_postupdate.xml
- dbscripts/xml/upgrade/3.0.0_preupdate.xml
- dbscripts/xml/upgrade/3.0.0_update.xml
s. https://github.com/pkp/pkp-lib/issues/2758
> pkp/pkp-lib#2758 HTML galley CSS file migration

- controllers/grid/settings/sections/SectionGridHandler.inc.php
This is the not-holding-hands-fix to https://github.com/pkp/pkp-lib/issues/2415
> pkp/pkp-lib#2415 Check if section has articles before deleting

- dbscripts/xml/upgrade/3.0.0_update.xml
geändert:       dbscripts/xml/upgrade/3.0.0_update.xml
>     fixed small typo

- .babelrc
- .editorconfig
- .eslintignore
- .eslintrc.js
- .gitignore
- .gitmodules
- .postcssrc.js
- js/load.js
- package.json
- plugins/themes/default/DefaultThemePlugin.inc.php
- plugins/themes/default/styles/components.less
- plugins/themes/default/styles/head.less
- plugins/themes/default/styles/index.less
- plugins/themes/default/styles/objects/announcement_full.less
- plugins/themes/default/styles/objects/announcement_summary.less
- plugins/themes/default/styles/objects/galley_link.less
- plugins/themes/default/styles/pages/submissions.less
- plugins/themes/default/styles/pages/viewPdf.less
- tools/buildpkg.sh
- webpack.config.js
Replaces https://github.com/pkp/ojs/pull/1525
> pkp/pkp-lib#2771 Integrate ui-library

- classes/workflow/EditorDecisionActionsManager.inc.php
- tests/data/60-content/LkumiegaSubmissionTest.php
rebase from https://github.com/pkp/ojs/pull/1503 in order to be able to merge...
> pkp/pkp-lib#1144 and pkp/pkp-lib#1258 Editor decision forms

- plugins/themes/default/styles/objects/galley_link.less
@bozana would you mind giving this a once-over? It's just some very basic fixes for issues that cropped up with the ui-library integration, and a couple of user access issues with the new submissions list. Fixes include:
- Restore missing icons
- Re-collapse grid table border margins
- Ensure authors can see the View Submission button in lists
- Fix workflow link in View Submission button in lists.
> Minor fixes for the submission lists and ui-library integration

- locale/fr_CA/submission.xml
change wording for editor.submission.decision.decline
> Modifications to locale fr_CA

- locale/fi_FI/emailTemplates.xml
@mtub, missing template for fi_FI
> Add SUBMISSION_ACK_NOT_USER template to fi_FI locale

- pages/article/ArticleHandler.inc.php
- templates/frontend/objects/article_details.tpl
https://github.com/pkp/pkp-lib/issues/2832
> pkp/pkp-lib#2832 remove citationFormats in code

- docs/dev/swagger.yaml
> pkp/pkp-lib#1503 Proposal for OJS 3.1 API specification

- plugins/importexport/native/NativeImportDom.inc.php
> Fix import of article covers 

- README.md
Just a small step I had to complete creating a dev env on a machine that has never seen OJS before.
> Add citationStyleLanguage instructions to README

- config.TEMPLATE.inc.php
@asmecher this commit is a rebase of @samplet's work into master
> pkp/pkp-lib#2686 Add api_key_secret to config template

- plugins/generic/tinymce/locale/es_ES/locale.xml
s. https://github.com/pkp/pkp-lib/issues/2852
> pkp/pkp-lib#2852 fix spanish locale for TinyMCE plugin

- templates/author/submission/layout.tpl
- templates/copyeditor/submission/layout.tpl
- templates/layoutEditor/submission/layout.tpl
- templates/proofreader/submission/layout.tpl
s. https://github.com/pkp/pkp-lib/issues/2850
> pkp/pkp-lib#2850 remote galleys display in layout.tpl

- plugins/blocks/navigation/block.tpl
- plugins/generic/tinymce/locale/es_ES/locale.xml
- templates/author/submission/layout.tpl
- templates/copyeditor/submission/layout.tpl
- templates/layoutEditor/submission/layout.tpl
- templates/proofreader/submission/layout.tpl
> pkp/pkp-lib#2856, 2852, 2850

- locale/de_DE/manager.xml
> Update de_DE locale (add missing verb)

- plugins/generic/googleScholar/GoogleScholarPlugin.inc.php
See request here: https://forum.pkp.sfu.ca/t/include-abbreviation-of-journal-title-in-the-html-header/34172/2
Uses same logic as here: https://github.com/pkp/ojs/blob/master/plugins/importexport/crossref/filter/IssueCrossrefXmlFilter.inc.php#L152-L156
> Add citation_journal_abbrev meta to Google Scholar plugin

- classes/article/PublishedArticleDAO.inc.php
- classes/plugins/DOIPubIdExportPlugin.inc.php
- controllers/grid/settings/plugins/SettingsPluginGridHandler.inc.php
- controllers/tab/issueEntry/IssueEntryTabHandler.inc.php
- pages/sitemap/SitemapHandler.inc.php
- rt/en_US/Humanities.xml
- rt/en_US/Life_Sciences.xml
> Typo fixes (found by codespell)

- locale/da_DK/author.xml
- locale/da_DK/default.xml
- plugins/generic/recommendByAuthor/locale/da_DK/locale.xml
- plugins/importexport/crossref/locale/da_DK/locale.xml
- plugins/pubIds/doi/locale/da_DK/locale.xml
pkp/pkp-lib#2869 da_DK locale update
files updated by Niels Erik
> pkp/pkp-lib#2869 da_DK locale update

- controllers/tab/issueEntry/form/IssueEntryPublicationMetadataForm.inc.php
- plugins/paymethod/manual/ManualPaymentPlugin.inc.php
- templates/frontend/pages/purchaseIndividualSubscription.tpl
@asmecher Is the `completedPaymentDao` function change correct?
> A few fixes for pkp/pkp-lib#1816

- dbscripts/xml/upgrade/3.1.0_update.xml
s. https://github.com/pkp/pkp-lib/issues/2859
> pkp/pkp-lib#2859 remove citationOutput plugins minimal

- dbscripts/xml/upgrade/3.1.0_update.xml
- plugins/importexport/datacite/DataciteExportDeployment.inc.php
- plugins/importexport/datacite/filter/DataciteXmlFilter.inc.php
- plugins/importexport/datacite/filter/filterConfig.xml
s. https://github.com/pkp/pkp-lib/issues/2873
> support for DataCite metadata schema 4

- locale/en_US/locale.xml
- plugins/themes/default/styles/objects/galley_link.less
- templates/frontend/objects/article_details.tpl
- templates/frontend/objects/article_summary.tpl
- templates/frontend/objects/galley_link.tpl
- templates/frontend/objects/issue_toc.tpl
- templates/frontend/pages/search.tpl
@asmecher I've got a bit to do on the Bootstrap theme but I think this covers the template/style needs.
> pkp/pkp-lib#1816 Indicate restricted galleys in issue and article templates

- .eslintrc.js
- .postcssrc.js
- webpack.config.js
PhpStorm fixed some missing semicolons.
> Clean code with PhpStorm

- plugins/paymethod/paypal/locale/de_DE/locale.xml
> Add German translation for PayPal plugin

- plugins/oaiMetadataFormats/jats/locale/de_DE/locale.xml
> Add German translation for JATS plugin

- plugins/generic/webFeed/locale/de_DE/locale.xml
> Fix German string for webfeed.settings.issue

- registry/locales.xml
completing translation updates for OJS 3.1 :-)
> update locale registry

- classes/install/Upgrade.inc.php
- dbscripts/xml/upgrade/3.0.0_postupdate.xml
s. https://github.com/pkp/pkp-lib/issues/2582
> pkp/pkp-lib#2582 fix repairImageAssociations

- .gitignore
> Ignore vendor/ directory in paypal plugin

- controllers/grid/settings/sections/form/SectionForm.inc.php
- plugins/themes/default/styles/components.less
- plugins/themes/default/styles/index.less
- plugins/themes/default/styles/objects/issue_toc.less
- plugins/themes/default/styles/pages/section.less
- templates/frontend/objects/issue_toc.tpl
Related comments in https://github.com/pkp/pkp-lib/issues/2714
> pkp/pkp-lib#2174 Support browsing by section plugin

- locale/sv_SE/author.xml
- locale/sv_SE/manager.xml
- plugins/blocks/languageToggle/locale/sv_SE/locale.xml
- plugins/importexport/doaj/locale/sv_SE/locale.xml
- plugins/pubIds/doi/locale/sv_SE/locale.xml
- plugins/reports/counter/locale/sv_SE/locale.xml
- plugins/reports/subscriptions/locale/sv_SE/locale.xml
- plugins/reports/views/locale/sv_SE/locale.xml
- plugins/themes/default/locale/sv_SE/locale.xml
Hi! Please find a few corrections and additions to the sv_SE locale. Cherry-picking to 3.1 is greatly appreciated if possible.
> Corrections and additions to sv_SE locale

- classes/oai/ojs/OAIDAO.inc.php
Issue here: https://github.com/pkp/pkp-lib/issues/3026
> Check for publishingMode when fetching OAI results

- pages/layoutEditor/index.php
Resolves pkp/pkp-lib#2538 by granting the permissions in question, despite reservations about whether Layout Editors really should be interacting with Issue Galleys.
> pkp/pkp-lib#2538: Add handlers for Issue Galleys to Layout Editor

- controllers/api/file/ManageFileApiHandler.inc.php
s. https://github.com/pkp/pkp-lib/issues/2922
> pkp/pkp-lib#2922 detach dependent entities at file upload cancel 

- plugins/oaiMetadataFormats/marc/record.tpl
s. https://github.com/pkp/pkp-lib/issues/3062
> pkp/pkp-lib#3062 fix oai_marc

- plugins/oaiMetadataFormats/marc/record.tpl
cherry-pick to ojs-stable-2_4_8
> Fix oai_marc template for schema compliance in ojs-stable-2_4_8

- dbscripts/xml/upgrade/3.0.0_postupgrade_metrics.xml
- dbscripts/xml/upgrade/3.1.1_update.xml
s. https://github.com/pkp/pkp-lib/issues/3087
> pkp/pkp-lib#3087 fix metrics assoc_type for supp files

- classes/article/ArticleDAO.inc.php
- dbscripts/xml/upgrade.xml
- dbscripts/xml/upgrade/3.1.1_preupdate_citations.xml
- pages/article/ArticleHandler.inc.php
- templates/controllers/modals/submissionMetadata/issueEntryTabs.tpl
- templates/frontend/objects/article_details.tpl
s. https://github.com/pkp/pkp-lib/issues/3028
> pkp/pkp-lib#3028 parse and save citations 

- classes/oai/ojs/OAIDAO.inc.php
s. https://github.com/pkp/pkp-lib/issues/3051
> pkp/pkp-lib#3051 use GRATEST for OAI until date

- locale/de_DE/locale.xml
- locale/de_DE/manager.xml
- plugins/blocks/subscription/locale/de_DE/locale.xml
- plugins/generic/usageStats/locale/de_DE/locale.xml
- plugins/importexport/native/locale/de_DE/locale.xml
- plugins/importexport/users/locale/de_DE/locale.xml
> Update German translations and add missing ones

- plugins/gateways/resolver/locale/sv_SE/locale.xml
- plugins/generic/announcementFeed/locale/sv_SE/locale.xml
- plugins/generic/backup/locale/sv_SE/locale.xml
- plugins/generic/browse/locale/sv_SE/locale.xml
- plugins/importexport/datacite/locale/sv_SE/locale.xml
- plugins/importexport/native/locale/sv_SE/locale.xml
- plugins/importexport/pubmed/locale/sv_SE/locale.xml
- plugins/importexport/users/locale/sv_SE/locale.xml
- plugins/pubIds/urn/locale/sv_SE/locale.xml
Adding more plugin translations.
> More sv_SE plugin translations

- locale/fr_CA/emailTemplates.xml
Missing string in emailTemplate.xml for PASSWORD_RESET:
"Mot de passe : {$password}<br />"
> update fr-CA local

- plugins/generic/driver/locale/sv_SE/locale.xml
- plugins/generic/dublinCoreMeta/locale/sv_SE/locale.xml
- plugins/generic/externalFeed/locale/sv_SE/locale.xml
- plugins/generic/googleScholar/locale/sv_SE/locale.xml
- plugins/generic/htmlArticleGalley/locale/sv_SE/locale.xml
- plugins/generic/openAIRE/locale/sv_SE/locale.xml
- plugins/generic/phpMyVisites/locale/sv_SE/locale.xml
- plugins/generic/recommendByAuthor/locale/sv_SE/locale.xml
- plugins/generic/recommendBySimilarity/locale/sv_SE/locale.xml
- plugins/generic/usageEvent/locale/sv_SE/locale.xml
- plugins/generic/usageStats/locale/sv_SE/locale.xml
- plugins/generic/webFeed/locale/sv_SE/locale.xml
- plugins/oaiMetadataFormats/dc/locale/sv_SE/locale.xml
- plugins/oaiMetadataFormats/marc/locale/sv_SE/locale.xml
- plugins/oaiMetadataFormats/marcxml/locale/sv_SE/locale.xml
- plugins/oaiMetadataFormats/rfc1807/locale/sv_SE/locale.xml
More plugin translations in Swedish.
> sv_SE plugin translations

- classes/submission/SubmissionMetadataFormImplementation.inc.php
- classes/submission/form/SubmissionSubmitStep3Form.inc.php
- controllers/modals/submissionMetadata/form/SubmissionMetadataViewForm.inc.php
- locale/en_US/submission.xml
s. https://github.com/pkp/pkp-lib/issues/2571
> pkp/pkp-lib#2571 consider abstract word count limit 

- locale/pt_BR/locale.xml
pkp/pkp-lib#3216 pt_BR locale fix
> pkp/pkp-lib#3216 pt_BR locale fix

- locale/de_DE/manager.xml
> Fix German string resetPermissions.confirm

- locale/es_ES/manager.xml
@mtub 
Still fixing missing chains, not translated in 3.1.0-1.
> Translation [es_ES]: Missing chains for PKP PN

- plugins/auth/ldap/locale/es_ES/locale.xml
- plugins/blocks/developedBy/locale/es_ES/locale.xml
- plugins/blocks/information/locale/es_ES/locale.xml
- plugins/blocks/languageToggle/locale/es_ES/locale.xml
- plugins/blocks/relatedItems/locale/es_ES/locale.xml
- plugins/gateways/resolver/locale/es_ES/locale.xml
- plugins/generic/announcementFeed/locale/es_ES/locale.xml
- plugins/generic/googleScholar/locale/es_ES/locale.xml
- plugins/generic/htmlArticleGalley/locale/es_ES/locale.xml
- plugins/generic/openAIRE/locale/es_ES/locale.xml
- plugins/generic/phpMyVisites/locale/es_ES/locale.xml
- plugins/generic/recommendByAuthor/locale/es_ES/locale.xml
- plugins/generic/webFeed/locale/es_ES/locale.xml
- plugins/importexport/crossref/locale/es_ES/locale.xml
- plugins/importexport/native/locale/es_ES/locale.xml
- plugins/importexport/sample/locale/es_ES/locale.xml
- plugins/importexport/users/locale/es_ES/locale.xml
- plugins/pubIds/urn/locale/es_ES/locale.xml
- plugins/reports/articles/locale/es_ES/locale.xml
- plugins/reports/views/locale/es_ES/locale.xml
- plugins/themes/default/locale/es_ES/locale.xml
@mtub working with github web edition is very noisy (creates a PR for every change).
This time I forked all repos, worked locally and push to my forks.
Here you have a PR with all the changes... of this repo (more PR will be pushed to the pkp-lib and plugins soon).
Hope this work better for you all.
Still "emergency" translations... Changing the basic stuff to make the UI usable.
To avoid showing missing chains, would be nice to include defaultTranslations plugin and enabled in the official relase. @asmecher what do you think?
> Translation es_ES

- classes/install/Upgrade.inc.php
s. https://github.com/pkp/pkp-lib/issues/3220
> pkp/pkp-lib#3220 fix migrateTimedViewsUsageStatistic

- classes/install/Upgrade.inc.php
s. https://github.com/pkp/pkp-lib/issues/3219
> pkp/pkp-lib#3219 fix repairSuppFilesFilestage if file exists

- locale/ar_IQ/locale.xml
- locale/de_DE/manager.xml
- locale/es_ES/manager.xml
- locale/ru_RU/locale.xml
- locale/ru_RU/manager.xml
- locale/ru_RU/submission.xml
cherry-picked from recent updates to `master` branch
> Locale updates

- locale/es_ES/manager.xml
fixing manager.setup.enableUserRegistration string in Spanish translation
> fix string translation in Spanish

- locale/es_ES/manager.xml
just a gender split... 
@mtub please commit the change to the next release... this was already talk with @marcbria
> gender split

- dbscripts/xml/upgrade/3.1.1_update.xml
s. https://github.com/pkp/pkp-lib/issues/3218
> pkp/pkp-lib#3218 fix user_group_id column drop from submission_files

- pages/search/SearchHandler.inc.php
- templates/frontend/pages/searchAuthorDetails.tpl
The site level author search at site.com/index.php/index/search/authors/ is giving an error because it is only designed to work within a context. This is the fix for it, if the code is planned to be maintained.
https://forum.pkp.sfu.ca/t/ojs-3-1-0-1-search-authors-interface-dead-code/37354
> fix site level author search

- plugins/blocks/subscription/locale/fi_FI/locale.xml
@mtub 
Finnish locale for the subscription block.
> Finnish locale for subscription block plugin

- pages/index/IndexHandler.inc.php
> pkp/pkp-lib#2291: Use the localized page title for the site, not the page header

- templates/frontend/objects/article_details.tpl
s. https://github.com/pkp/pkp-lib/issues/3329
> pkp/pkp-lib#3329 display copyright info with CC license badge

- locale/es_ES/locale.xml
some missing strings, and the new legacy strings section (I followed the guidelines)
> some missing strings Spanish translation

- plugins/blocks/user/block.tpl
s. https://github.com/pkp/pkp-lib/issues/2683
this is the cherry-pick from ojs-dev-2_4
> pkp/pkp-lib#2683: remove password value from user block

- dbscripts/xml/upgrade.xml
- locale/ar_IQ/emailTemplates.xml
- locale/da_DK/emailTemplates.xml
- locale/de_DE/emailTemplates.xml
- locale/en_US/emailTemplates.xml
- locale/es_ES/emailTemplates.xml
- locale/fa_IR/emailTemplates.xml
- locale/fi_FI/emailTemplates.xml
- locale/fr_CA/emailTemplates.xml
- locale/fr_FR/emailTemplates.xml
- locale/id_ID/emailTemplates.xml
- locale/pt_PT/emailTemplates.xml
- locale/ru_RU/emailTemplates.xml
- locale/sv_SE/emailTemplates.xml
s. https://github.com/pkp/pkp-lib/issues/3278
> revision upload notifications

- classes/install/Upgrade.inc.php
- dbscripts/xml/upgrade.xml
- plugins/generic/externalFeed/schema.xml
s. https://github.com/pkp/pkp-lib/issues/3416
I put everything in the PHP function instead of an XML file for the users to be able to manually change the new locale to sr_RS@cyrillic if wished so.
> pkp/pkp-lib#3416 migrate sr_SR to sr_RS@latin

- classes/workflow/EditorDecisionActionsManager.inc.php
s. https://github.com/pkp/pkp-lib/issues/3436
> pkp/pkp-lib#3436 consider recommendOnly for submission workflow stage decisions

- classes/article/ArticleGalleyDAO.inc.php
- classes/issue/IssueDAO.inc.php
s. https://github.com/pkp/pkp-lib/issues/1692
>  pkp/pkp-lib#1692 fix (generalize) parameter names for pub id plugin functions

- templates/common/header.tpl
ping @asmecher 
discussed in https://forum.pkp.sfu.ca/t/some-problems-with-subscriptions-after-upgrade-to-3-1-0-1/37347/4
> Add submenu to payments settings menu

- classes/install/Upgrade.inc.php
- dbscripts/xml/upgrade.xml
s. https://github.com/pkp/pkp-lib/issues/3302
Is this way to clear cache enough? -- when the order of the grid columns changed...
> pkp/pkp-lib#3302 clearCache needed after these changes 

- locale/sv_SE/api.xml
- locale/sv_SE/locale.xml
- locale/sv_SE/manager.xml
- locale/sv_SE/submission.xml
More to come in pkp-lib (and plugins).
> Updating sv_SE locale for 3.1.1

- classes/workflow/EditorDecisionActionsManager.inc.php
s. https://github.com/pkp/ojs/commit/79e9ccb3ae87be8310851d4b278fbbceb5aea5b3#r28214360
> pkp/pkp-lib#3436 change array_merge into + to keep the keys

- plugins/importexport/datacite/filter/DataciteXmlFilter.inc.php
s. https://github.com/pkp/pkp-lib/issues/3509
> pkp/pkp-lib#3509 fix article accepted date in DataCite export

- locale/fi_FI/api.xml
- locale/fi_FI/locale.xml
- locale/fi_FI/manager.xml
- locale/fi_FI/submission.xml
- plugins/generic/announcementFeed/locale/fi_FI/locale.xml
- plugins/generic/driver/locale/fi_FI/locale.xml
- plugins/generic/usageStats/locale/fi_FI/locale.xml
@asmecher Finnish locale for OJS 3.1.1
> Fi locale for 3.1.1

- classes/author/form/submit/AuthorSubmitStep3Form.inc.php
> pkp/pkp-lib#3529: Backport 3.x abstract word count to 2.4.x

- classes/install/Upgrade.inc.php
- dbscripts/xml/upgrade.xml
s. https://github.com/pkp/pkp-lib/issues/3563
> pkp/pkp-lib#3563 place sr_SR migration before files migration

- locale/sv_SE/manager.xml
> Fixing locale string in sv_SE locale

- locale/pt_PT/api.xml
- locale/pt_PT/editor.xml
- locale/pt_PT/locale.xml
- locale/pt_PT/manager.xml
- locale/pt_PT/submission.xml
- plugins/auth/ldap/locale/pt_PT/locale.xml
- plugins/blocks/subscription/locale/pt_PT/locale.xml
- plugins/generic/backup/locale/pt_PT/locale.xml
- plugins/generic/browse/locale/pt_PT/locale.xml
- plugins/generic/lucene/locale/pt_PT/locale.xml
- plugins/generic/openAIRE/locale/pt_PT/locale.xml
- plugins/generic/recommendBySimilarity/locale/pt_PT/locale.xml
- plugins/generic/usageStats/locale/pt_PT/locale.xml
- plugins/importexport/doaj/locale/pt_PT/locale.xml
- plugins/importexport/medra/locale/pt_PT/locale.xml
- plugins/importexport/native/locale/pt_PT/locale.xml
- plugins/paymethod/paypal/locale/pt_PT/locale.xml
- plugins/pubIds/doi/locale/pt_PT/locale.xml
- plugins/reports/subscriptions/locale/pt_PT/locale.xml
Added some localization texts. Is this the best way to submit them?
> Some pt localization

- dbscripts/xml/upgrade/3.0.0_postupgrade_metrics.xml
s. https://github.com/pkp/pkp-lib/issues/3597
> pkp/pkp-lib#3597 remove double SQL for metrics supp file migration

- classes/subscription/Subscription.inc.php
- plugins/importexport/pubmed/PubMedExportPlugin.inc.php
- plugins/importexport/pubmed/filter/ArticlePubMedXmlFilter.inc.php
- plugins/oaiMetadataFormats/rfc1807/OAIMetadataFormat_RFC1807.inc.php
- plugins/reports/articles/ArticleReportPlugin.inc.php
- templates/payments/subscriptionTypeForm.tpl
@asmecher, I found a few bugs, when working on another issue. May I make this PR without creating the corresponding issues? If yes, could you take a look and if OK I will cherry-pick to master as well... THANKS!
> a few fixes

- classes/subscription/IndividualSubscriptionDAO.inc.php
- classes/user/UserAction.inc.php
s. https://github.com/pkp/pkp-lib/issues/3664
> fix individual subscription dao

- plugins/importexport/native/filter/NativeXmlArticleFilter.inc.php
s. https://github.com/pkp/pkp-lib/issues/3679
> fix submission import issue identification match error

- classes/install/Upgrade.inc.php
s. https://github.com/pkp/pkp-lib/issues/3016
> pkp/pkp-lib#3016 fix repairSuppFilesFilestage

- locale/de_DE/api.xml
> pkp/pkp-lib#1922 de_DE translation of API string

- dbscripts/xml/upgrade/3.1.1_preupdate_citations.xml
s. https://github.com/pkp/pkp-lib/issues/3749
> pkp/pkp-lib#3749 fix wrong assoc_type in citations upgrade

- classes/security/RoleDAO.inc.php
Resolves pkp/pkp-lib#3754 for 2.4.x, plus adds a little extra sorting functionality for dates in the user table.
> pkp/pkp-lib#3754: Allow user sorting by dates; prevent DB error on malformed input.

- plugins/generic/tinymce/TinyMCEPlugin.inc.php
> pkp/pkp-lib#3727: Enable tinyMCE for registerUser op

- locale/sv_SE/locale.xml
Cherry-picking to 3.1.1-1 is appreciated.
> Updating sv_SE locale for 3.1.1-1

- locale/de_DE/manager.xml
> Fix word form of "verwenden" (=use) in de_DE

- docs/REPORTING-BUGS.md
- docs/UPGRADE-UNSUPPORTED.md
- docs/UPGRADE.md
> Convert some docs into markdown

- locale/de_DE/locale.xml
- plugins/importexport/native/locale/de_DE/locale.xml
- plugins/paymethod/manual/locale/de_DE/locale.xml
- plugins/pubIds/urn/locale/de_DE/locale.xml
* privacy & consent updates
* aligning de_DE with en_US
> de_DE locale updates

- templates/controllers/modals/submissionMetadata/form/issueEntrySubmissionReviewForm.tpl
s. https://github.com/pkp/pkp-lib/issues/3837
> pkp/pkp-lib#3837 do not display references textarea in the metadata modal, submission tab

- classes/security/form/AuthSourceSettingsForm.inc.php
- classes/subscription/form/UserIndividualSubscriptionForm.inc.php
- classes/subscription/form/UserInstitutionalSubscriptionForm.inc.php
- plugins/generic/externalFeed/ExternalFeedForm.inc.php
- plugins/generic/externalFeed/ExternalFeedSettingsForm.inc.php
Fixes part of pkp/pkp-lib#3578; may break some plugins.
> pkp/pkp-lib#3578: harmonizing Form::display() signatures

- plugins/importexport/crossref/CrossrefInfoSender.inc.php
> Fix typo in CrossrefInfoSender

- controllers/grid/issueGalleys/IssueGalleyGridRow.inc.php
- controllers/grid/issues/IssueGridRow.inc.php
- controllers/grid/toc/TocGridRow.inc.php
Fixes part of pkp/pkp-lib#3578.
> pkp/pkp-lib#3578: harmonizing GridRow::initialize() signatures

- classes/file/IssueFileManager.inc.php
- classes/file/JournalFileManager.inc.php
- classes/plugins/PubObjectsExportPlugin.inc.php
- controllers/grid/issueGalleys/IssueGalleyGridHandler.inc.php
- controllers/grid/issues/form/IssueGalleyForm.inc.php
- pages/article/ArticleHandler.inc.php
- pages/issue/IssueHandler.inc.php
- plugins/importexport/crossref/CrossrefInfoSender.inc.php
- plugins/importexport/datacite/DataciteExportPlugin.inc.php
- plugins/importexport/datacite/DataciteInfoSender.inc.php
- plugins/importexport/medra/MedraInfoSender.inc.php
- plugins/importexport/native/NativeImportExportPlugin.inc.php
- plugins/importexport/pubmed/PubMedExportPlugin.inc.php
Addresses part of pkp/pkp-lib#3578 as discussed on Slack. Will break some plugins.
> pkp/pkp-lib#3578: cleaning up FileManager signatures

- locale/fr_FR/emailTemplates.xml
cherry-picked from stable branch, thanks @forgive38
> fr_FR locale update, password reset email

- locale/es_ES/api.xml
- locale/es_ES/emailTemplates.xml
- locale/es_ES/locale.xml
- locale/es_ES/manager.xml
- locale/es_ES/submission.xml
- plugins/blocks/subscription/locale/es_ES/locale.xml
- plugins/generic/usageEvent/locale/es_ES/locale.xml
- plugins/generic/webFeed/locale/es_ES/locale.xml
- plugins/importexport/datacite/locale/es_ES/locale.xml
- plugins/importexport/doaj/locale/es_ES/locale.xml
- plugins/importexport/medra/locale/es_ES/locale.xml
- plugins/importexport/native/locale/es_ES/locale.xml
- plugins/importexport/users/locale/es_ES/locale.xml
- plugins/metadata/mods34/locale/es_ES/locale.xml
- plugins/paymethod/manual/locale/es_ES/emailTemplates.xml
- plugins/paymethod/paypal/locale/es_ES/locale.xml
- plugins/reports/counter/locale/es_ES/locale.xml
- plugins/reports/views/locale/es_ES/locale.xml
received by email from @marcbria
> es_ES locale updates

- classes/controllers/grid/issues/IssueGridHandler.inc.php
- classes/submission/form/SubmissionSubmitStep4Form.inc.php
- classes/subscription/form/PaymentTypesForm.inc.php
- controllers/api/file/ManageFileApiHandler.inc.php
- controllers/grid/admin/journal/JournalGridHandler.inc.php
- controllers/grid/articleGalleys/ArticleGalleyGridHandler.inc.php
- controllers/grid/articleGalleys/form/ArticleGalleyForm.inc.php
- controllers/grid/issueGalleys/IssueGalleyGridHandler.inc.php
- controllers/grid/issues/form/IssueAccessForm.inc.php
- controllers/grid/issues/form/IssueForm.inc.php
- controllers/grid/issues/form/IssueGalleyForm.inc.php
- controllers/grid/settings/sections/SectionGridHandler.inc.php
- controllers/grid/settings/sections/form/SectionForm.inc.php
- controllers/grid/subscriptions/IndividualSubscriptionsGridHandler.inc.php
- controllers/grid/subscriptions/InstitutionalSubscriptionsGridHandler.inc.php
- controllers/grid/subscriptions/SubscriptionTypesGridHandler.inc.php
- controllers/modals/editorDecision/form/InitiateExternalReviewForm.inc.php
- controllers/modals/submissionMetadata/form/IssueEntrySubmissionReviewForm.inc.php
- controllers/modals/submissionMetadata/form/SubmissionMetadataViewForm.inc.php
- controllers/tab/issueEntry/IssueEntryTabHandler.inc.php
- controllers/tab/issueEntry/form/IssueEntryPublicationMetadataForm.inc.php
- controllers/tab/pubIds/form/PublicIdentifiersForm.inc.php
- controllers/tab/settings/WebsiteSettingsTabHandler.inc.php
- pages/payments/PaymentsHandler.inc.php
Fixes part of pkp/pkp-lib#3578; may break some plugins.
> pkp/pkp-lib#3578: harmonizing Form::execute() signatures

- controllers/grid/issues/ExportableIssuesListGridHandler.inc.php
- controllers/grid/issues/FutureIssueGridHandler.inc.php
- controllers/grid/settings/plugins/SettingsPluginGridHandler.inc.php
- controllers/grid/subscriptions/IndividualSubscriptionsGridHandler.inc.php
- controllers/grid/subscriptions/InstitutionalSubscriptionsGridHandler.inc.php
- controllers/grid/subscriptions/PaymentsGridHandler.inc.php
- controllers/grid/subscriptions/SubscriptionTypesGridHandler.inc.php
- controllers/grid/subscriptions/SubscriptionsGridHandler.inc.php
- controllers/grid/toc/TocGridHandler.inc.php
- controllers/grid/users/subscriberSelect/SubscriberSelectGridHandler.inc.php
- controllers/tab/settings/JournalSettingsTabHandler.inc.php
Fixes part of pkp/pkp-lib#3578.
> pkp/pkp-lib#3578: harmonizing GridHandler signatures

- controllers/tab/issueEntry/IssueEntryTabHandler.inc.php
Fix https://github.com/pkp/pkp-lib/issues/3992
> Check that pubIdPlugins array is set before foreach

- controllers/grid/issues/BackIssueGridHandler.inc.php
- controllers/grid/issues/ExportableIssuesListGridHandler.inc.php
- controllers/grid/issues/FutureIssueGridHandler.inc.php
- controllers/grid/settings/sections/SectionGridHandler.inc.php
- controllers/grid/subscriptions/IndividualSubscriptionsGridHandler.inc.php
- controllers/grid/subscriptions/InstitutionalSubscriptionsGridHandler.inc.php
- controllers/grid/toc/TocGridHandler.inc.php
- controllers/tab/settings/JournalSettingsTabHandler.inc.php
- pages/article/ArticleHandler.inc.php
- pages/issue/IssueHandler.inc.php
Last set of PRs to fix pkp/pkp-lib#3578.
> pkp/pkp-lib#3578: harmonizing PKPHandler::initialize() signatures

- classes/article/SubmissionFileDAO.inc.php
Partly fixes pkp/pkp-lib#3578.
> pkp/pkp-lib#3578: harmonizing SubmissionFileDAO::fromRow()

- plugins/reports/views/locale/es_ES/locale.xml
Improved already existing translations and added missing ones
> Update locale.xml in es_ES lang

- classes/install/Upgrade.inc.php
- dbscripts/xml/upgrade.xml
- dbscripts/xml/upgrade/3.1.1_update.xml
See https://github.com/pkp/pkp-lib/issues/4131
> pkp/pkp-lib#4131 use function to update 531 assoc_id's in metrics table

- README.md
> pkp/pkp-lib#4146: Change composer syntax to --working-dir

- locale/da_DK/locale.xml
- plugins/pubIds/doi/locale/da_DK/locale.xml
Small update for 3.1.1-4.
Please cherry-pick to master as well.
> Translation update for the da_DK locale

- locale/fi_FI/default.xml
Fix contextName variable. @mtub
> Fix typo in fi_FI default.xml

- locale/fi_FI/emailTemplates.xml
Small correction to editor recommendation template in fi_FI
@mtub (still waiting for a comment from my organisation regarding the CLA...)
> Update emailTemplates.xml fi_FI

- locale/pt_PT/locale.xml
#4190, cherry-picked from `ojs-stable-3_1_1` branch
> Complete pt_PT translations

- plugins/importexport/doaj/filter/DOAJJsonFilter.inc.php
- plugins/importexport/doaj/filter/DOAJXmlFilter.inc.php
Resolves pkp/pkp-lib#4236 for master.
> pkp/pkp-lib#4236: Remove export of author email within DOAJ

- plugins/metadata/dc11/filter/Dc11SchemaArticleAdapter.inc.php
s. https://github.com/pkp/pkp-lib/issues/4242
This provides all the "subjects" via OAI in the same way it was in OJS 2.
> pkp/pkp-lib#4242 provide DC subjects via OAI

- plugins/importexport/users/locale/de_DE/locale.xml
fixed a decade-old translation that I never noticed
> de_DE update

- config.TEMPLATE.inc.php
s. https://github.com/pkp/pkp-lib/issues/3860
>  pkp/pkp-lib#3860 add DB socket and port config option 

- classes/journal/Section.inc.php
- classes/journal/SectionDAO.inc.php
- classes/submission/form/SubmissionSubmitStep1Form.inc.php
- controllers/modals/submissionMetadata/form/IssueEntrySubmissionReviewForm.inc.php
- controllers/modals/submissionMetadata/form/SubmissionMetadataViewForm.inc.php
- locale/de_DE/locale.xml
- locale/en_US/locale.xml
- plugins/themes/default/styles/pages/submissions.less
- registry/minifiedScripts.txt
- templates/submission/form/section.tpl
- templates/submission/form/sectionPolicy.tpl
- templates/submission/form/step1.tpl
see https://github.com/pkp/pkp-lib/issues/2638
> Section policies display

- config.TEMPLATE.inc.php
Noticed these when I was updating some documentation.
> Minor grammar/spelling changes in config

- classes/install/Upgrade.inc.php
Resolves pkp/pkp-lib#4287 for stable 3.1.1
> pkp/pkp-lib#4287: skip processing missing supplementary files for review

- controllers/modals/submissionMetadata/form/IssueEntrySubmissionReviewForm.inc.php
> pkp/pkp-lib#4215 Fixed missing submission parameter in issueentrysubmissionreviewform::execute hook call

- controllers/modals/submissionMetadata/form/IssueEntrySubmissionReviewForm.inc.php
- plugins/pubIds/doi/templates/doiAssign.tpl
- plugins/pubIds/doi/templates/doiSuffixEdit.tpl
- plugins/pubIds/urn/templates/urnAssign.tpl
- plugins/pubIds/urn/templates/urnSuffixEdit.tpl
> fix the function name and template path

- plugins/importexport/crossref/CrossrefInfoSender.inc.php
> pkp/pkp-lib#4350: Capture current Crossref deposit status before update.

- classes/article/ArticleDAO.inc.php
- classes/core/Application.inc.php
- controllers/tab/settings/JournalSettingsTabHandler.inc.php
- dbscripts/xml/install.xml
- dbscripts/xml/upgrade.xml
- locale/en_US/locale.xml
- pages/catalog/index.php
- pages/management/SettingsHandler.inc.php
- plugins/blocks/browse/BrowseBlockPlugin.inc.php
- plugins/blocks/browse/index.php
- plugins/blocks/browse/locale/ca_ES/locale.xml
- plugins/blocks/browse/locale/de_DE/locale.xml
- plugins/blocks/browse/locale/en_US/locale.xml
- plugins/blocks/browse/locale/es_ES/locale.xml
- plugins/blocks/browse/locale/pt_BR/locale.xml
- plugins/blocks/browse/locale/sl_SI/locale.xml
- plugins/blocks/browse/templates/block.tpl
- plugins/blocks/browse/version.xml
- plugins/themes/default/styles/sidebar.less
- templates/controllers/modals/submissionMetadata/form/issueEntrySubmissionReviewForm.tpl
- templates/frontend/components/articleList.tpl
- templates/frontend/components/breadcrumbs_catalog.tpl
- templates/frontend/objects/article_summary.tpl
- templates/frontend/pages/catalogCategory.tpl
- templates/management/settings/journal.tpl
Replaces https://github.com/pkp/ojs/pull/2225
> pkp/pkp-lib#4158 Add category support to OJS/pkp-lib

- dbscripts/xml/indexes.xml
setting_name = 'pub-id::publisher-id' should be included in the index
> pkp/pkp-lib#4370 Update submission_setting index

- config.TEMPLATE.inc.php
Add configuration option for pkp/pkp-lib#4204
> pkp/pkp-lib#4204: Add option to enforce hostname for ReCAPTACHA.

- api/v1/issues/IssueHandler.inc.php
s. https://github.com/pkp/pkp-lib/issues/4340
> pkp/pkp-lib#4340 Users in multicontext install are offered links to unprivileged contexts

- plugins/reports/articles/ArticleReportDAO.inc.php
- plugins/reports/articles/ArticleReportPlugin.inc.php
> additional data for the article report

- plugins/reports/articles/ArticleReportDAO.inc.php
- plugins/reports/articles/ArticleReportPlugin.inc.php
s. https://github.com/pkp/pkp-lib/issues/2820
> additional data for the article report 

- controllers/grid/settings/sections/form/SectionForm.inc.php
- locale/en_US/submission.xml
- templates/controllers/grid/settings/sections/form/sectionForm.tpl
s. https://github.com/pkp/pkp-lib/issues/3535
> pkp/pkp-lib#3535 Updating the Section settings heading

- registry/locales.xml
thanks to new translation provided by @rvdb
pkp/pkp-lib#4503
> updated registry of locales: nl_NL complete

- locale/el_GR/admin.xml
- locale/el_GR/api.xml
- locale/el_GR/author.xml
- locale/el_GR/default.xml
- locale/el_GR/editor.xml
- locale/el_GR/emailTemplates.xml
- locale/el_GR/locale.xml
- locale/el_GR/manager.xml
- locale/el_GR/submission.xml
- plugins/generic/recommendBySimilarity/locale/it_IT/locale.xml
Updating the commits from #2283 by @kstamatis
> el_GR locale updates

- classes/plugins/PubObjectsExportPlugin.inc.php
- controllers/grid/submissions/ExportPublishedSubmissionsListGridCellProvider.inc.php
- dbscripts/xml/upgrade/3.1.2_update.xml
- plugins/importexport/crossref/CrossRefExportPlugin.inc.php
- plugins/importexport/crossref/CrossrefInfoSender.inc.php
- plugins/importexport/crossref/locale/ar_IQ/locale.xml
- plugins/importexport/crossref/locale/cs_CZ/locale.xml
- plugins/importexport/crossref/locale/da_DK/locale.xml
- plugins/importexport/crossref/locale/de_DE/locale.xml
- plugins/importexport/crossref/locale/en_US/locale.xml
- plugins/importexport/crossref/locale/es_ES/locale.xml
- plugins/importexport/crossref/locale/fa_IR/locale.xml
- plugins/importexport/crossref/locale/fi_FI/locale.xml
- plugins/importexport/crossref/locale/pt_BR/locale.xml
- plugins/importexport/crossref/locale/pt_PT/locale.xml
- plugins/importexport/crossref/locale/ru_RU/locale.xml
- plugins/importexport/crossref/locale/sr_RS@latin/locale.xml
- plugins/importexport/crossref/locale/sv_SE/locale.xml
- plugins/importexport/crossref/templates/index.tpl
- plugins/importexport/crossref/templates/statusMessage.tpl
s. https://github.com/pkp/pkp-lib/issues/3803
> pkp/pkp-lib#3803 new crossref deposit API

- README.md
Noticed there was a new link there while doing my setup :)
> Update documentation’s URL

- config.TEMPLATE.inc.php
Since we are only supporting PHP7 now.
> Change default db driver

- classes/search/ArticleSearch.inc.php
- classes/search/ArticleSearchIndex.inc.php
Changes needed in OJS repo to make Subtitle searchable. Also one change in pkp-lib is necessary.
> #4647: make Subtitle searchable

- plugins/themes/default/DefaultThemePlugin.inc.php
- plugins/themes/default/locale/en_US/locale.xml
- plugins/themes/default/styles/pages/indexJournal.less
- templates/frontend/pages/indexJournal.tpl
[See issue #3817: Add option to display journal summary on homepage](https://github.com/pkp/pkp-lib/issues/3817)
> #3817 Added the journal summary in between header and announcements

- controllers/tab/issueEntry/form/IssueEntryPublicationMetadataForm.inc.php
Updating of search index must occur after call to $articleDao->updateObject($submission);
Because this call would clear the dirty state of the article and pull search indexing would never update the article in the search index.
> #4689: pull-indexing problem with schedule for publication

- plugins/importexport/crossref/templates/index.tpl
> pkp/pkp-lib#4693: Correct locale key plugins.importexport.crossref.settings.form.validation

- pages/search/SearchHandler.inc.php
Resolves pkp/pkp-lib#4713 for master.
Please also merge across stable_3_1_2.
> pkp/pkp-lib#4713: Update default search date for Smarty 3.

- templates/frontend/objects/article_details.tpl
- templates/frontend/objects/article_summary.tpl
- templates/frontend/objects/issue_summary.tpl
- templates/frontend/objects/issue_toc.tpl
- templates/frontend/pages/catalogCategory.tpl
- templates/frontend/pages/indexJournal.tpl
- templates/frontend/pages/indexSite.tpl
@NateWr: [see issue here](https://github.com/pkp/pkp-lib/issues/4557)
> #4557 Added null if there is no alt text to image

- plugins/themes/default/DefaultThemePlugin.inc.php
- plugins/themes/default/locale/en_US/locale.xml
- templates/frontend/pages/indexJournal.tpl
Hi @NateWr, here's the Pull Request for https://github.com/pkp/pkp-lib/issues/4683
> pkp/pkp-lib#4683 Added option to use homepage image as background

- plugins/themes/default/styles/objects/issue_toc.less
As per this issue https://github.com/pkp/pkp-lib/issues/4705
cc: @NateWr
> #4705 Added back code for .cover img

- plugins/themes/default/styles/objects/issue_toc.less
Hi @NateWr! Let me know if this looks good.
> #4705 Backporting .cover img code back into stable-3_1_2

- plugins/blocks/languageToggle/templates/block.tpl
See https://github.com/pkp/pkp-lib/issues/4798
To be added to other custom themes
> Add lang attribute to language selector

- locale/sl_SI/locale.xml
- locale/sl_SI/manager.xml
- locale/sl_SI/submission.xml
- plugins/generic/htmlArticleGalley/locale/sl_SI/locale.xml
- plugins/importexport/crossref/locale/sl_SI/locale.xml
@mtub This should now work. Please try
> sl_SI-3_1_2_update

- plugins/generic/usageStats/UsageStatsLoader.inc.php
fix pkp/pkp-lib#4820 for dev-2_4
> pkp/pkp-lib#4820: Fix optionalColumns variable type warning in UsageStats File Loader.

- plugins/generic/usageStats/UsageStatsLoader.inc.php
fix pkp/pkp-lib#4820 for stable 2.4.8
> pkp/pkp-lib#4820: Fix optionalColumns variable type warning in UsageStats File Loader

- plugins/themes/default/styles/objects/issue_toc.less
For this issue [4978](https://github.com/pkp/pkp-lib/issues/4978)
> pkp/pkp-lib#4978 Added galley links styles to issue_toc.less

- plugins/themes/default/styles/pages/register.less
For [this issue](https://github.com/pkp/pkp-lib/issues/4830), cc: @NateWr
> pkp/pkp-lib#4830 Removed extra space at bottom of page from tagit results

- locale/en_US/locale.xml
- templates/frontend/components/searchForm_simple.tpl
[For this issue](https://github.com/pkp/pkp-lib/issues/4948) (cc: @NateWr)
> pkp/pkp-lib#4948 Changed aria label for article search

- plugins/blocks/languageToggle/templates/block.tpl
From [issue](https://github.com/pkp/pkp-lib/issues/5015)
> pkp/pkp-lib#5015 Changed lang attribute for local keys

- locale/es_ES/api.xml
Added all missing texts for es_ES in api.xml
> Complete API es_ES locales

- plugins/generic/externalFeed/locale/es_ES/locale.xml
* from string #46
````
<message key="plugins.generic.externalFeed.settings">Settings</message>
<message key="plugins.generic.externalFeed.settings.description">Customize the display of external feed items.</message>
<message key="plugins.generic.externalFeed.settings.styleSheet">Display</message>
<message key="plugins.generic.externalFeed.settings.defaultStyleSheet">External Feed Style Sheet</message>
<message key="plugins.generic.externalFeed.settings.stylesheetDescription">A custom style sheet can be used to replace the default style sheet for this plugin. The default style sheet can be viewed here</message>
<message key="plugins.generic.externalFeed.settings.useStyleSheet">Custom style sheet</message>
<message key="plugins.generic.externalFeed.form.title">Title</message>
<message …
```
> Paragraphs not translated? Minor translation #43

- pages/gateway/GatewayHandler.inc.php
Draft changes to the GatewayHandler to enable addition of authorization policies from gateway plugins.
> allow gateway plugins to add authorization policies

- locale/pt_BR/emailTemplates.xml
Updated the "REVISED_VERSION_NOTIFY" email template; changed "{$EditorialContactName}" to "Editor(es)".
> Update pt_BR email template

- classes/oai/ojs/OAIDAO.inc.php
Adds trivial escaping to make this query work on Postgres.
> pkp/pkp-lib#5099 add escaping to fix Postgres SQL error

- plugins/themes/default/styles/objects/issue_toc.less
From this issue: https://github.com/pkp/pkp-lib/issues/4705
> pkp/pkp-lib#4705 Put code back to fix cover image issue

- locale/fr_CA/locale.po
> Updated fr_CA locale

- classes/article/ArticleGalleyDAO.inc.php
- classes/journal/JournalDAO.inc.php
The Reassign DOIs action is broken in master. These changes fix the issue.
> Fix Reassign DOIs action

- plugins/generic/driver/DRIVERDAO.inc.php
- plugins/generic/openAIRE/OpenAIREDAO.inc.php
Declaration of OpenAIREDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai)
Declaration of DRIVERDAO::setOAI(&$oai) should be compatible with PKPOAIDAO::setOAI($oai)
> resolve function signature warnings

- locale/pt_BR/manager.po
Adding three entries to the PT-BR locale file
> Adding three entries to the PT-BR locale file

- locale/pt_BR/manager.po
fully updating PT-BR translation
> fully updating PT-BR translation

- plugins/generic/externalFeed/simplepie/SimplePie.inc.php
tweaks to calls to new in the SimplePie class.
> pkp/pkp-lib#5439 fix calls to new for PHP7 compatibility

- .gitignore
> Prevent cypress files from being committed

- controllers/statistics/form/ReportGeneratorForm.inc.php
This is a fix for https://github.com/pkp/pkp-lib/issues/5451
@asmecher I think I got the logic here correct.  I've tested this on a hosted journal and reports generate correctly, but feel free to reject if you think there's a better way.
> pkp/pkp-lib#5451 swap continue for other options for PHP7 compatibility

- plugins/importexport/crossref/filter/ArticleCrossrefXmlFilter.inc.php
Typo in getData calls ping @asmecher
> Fix get licenseUrl

- classes/plugins/PubIdPlugin.inc.php
https://github.com/pkp/pkp-lib/issues/5473
> fix reassign DOIs

- plugins/themes/default/DefaultThemePlugin.inc.php
From this issue: https://github.com/pkp/pkp-lib/issues/5605
> pkp/pkp-lib#5605 Fixed invisible profile link

- plugins/blocks/developedBy/locale/en_US/locale.po
- plugins/blocks/developedBy/templates/block.tpl
- plugins/blocks/information/templates/block.tpl
- plugins/blocks/languageToggle/templates/block.tpl
- plugins/blocks/subscription/templates/block.tpl
- plugins/generic/announcementFeed/templates/block.tpl
- plugins/generic/webFeed/templates/block.tpl
- plugins/themes/default/styles/objects/article_summary.less
- plugins/themes/default/styles/sidebar.less
- templates/frontend/objects/article_summary.tpl
- templates/frontend/objects/issue_toc.tpl
For this issue: https://github.com/pkp/pkp-lib/issues/5176
> pkp/pkp-lib#5176 Changed spans to h2s for titles for accessibility

- templates/frontend/components/skipLinks.tpl
From issue: https://github.com/pkp/pkp-lib/issues/5240
> #5240 Added aria-label to nav tag

- config.TEMPLATE.inc.php
This is one side of the modification. The other side is in pkp-lib.
> add two lines to the config file to allow suppressing the SMTP authentication in PHPMailer

- locale/en_US/locale.po
- templates/frontend/objects/issue_toc.tpl
Addressing @israelcefrin's comments in here: https://github.com/pkp/pkp-lib/issues/5177
> i5177 headings issue

- templates/submission/submissionMetadataFormFields.tpl
(cherry picked from commit 46a5ba8538fbf836d6194d7c8f9913ee31a9ace8)
> [OJS][3.1.2] #5796 Re-order section titles and descriptions for submissionMetadataFormFields

- plugins/themes/default/styles/objects/issue_toc.less
- templates/frontend/objects/article_summary.tpl
- templates/frontend/objects/issue_toc.tpl
- templates/frontend/pages/catalogCategory.tpl
- templates/frontend/pages/indexJournal.tpl
- templates/frontend/pages/search.tpl
Replaces https://github.com/pkp/ojs/pull/2692
> pkp/pkp-lib#5178 Add headings to article titles

- templates/submission/submissionMetadataFormFields.tpl
(cherry picked from commit 46a5ba8538fbf836d6194d7c8f9913ee31a9ace8)
> [OJS][3.2.0] #5796 Re-order section titles and descriptions for submissionMetadataFormFields submission metadata field

- controllers/grid/users/stageParticipant/form/StageParticipantNotifyForm.inc.php
(cherry picked from commit 27aba3d45b51cda898876f7dc26f9cfb905cc50f)
> [OJS][3.2.0] #5095 Suppress stage assignment notification email, if the user email succeeds

- controllers/grid/users/stageParticipant/form/StageParticipantNotifyForm.inc.php
… user email succeeds
(cherry picked from commit 27aba3d45b51cda898876f7dc26f9cfb905cc50f)
> [OJS][3.1.2] #5095 Suppress stage assignment notification email, if the user email succeeds

- classes/handler/Handler.inc.php
https://github.com/pkp/pkp-lib/issues/5784
> Move getTargetContext to pkp-lib #5784

- locale/en_US/locale.po
- pages/article/ArticleHandler.inc.php
- plugins/themes/default/styles/objects/article_details.less
- templates/frontend/objects/article_details.tpl
- templates/frontend/pages/catalogCategory.tpl
From this issue: https://github.com/pkp/pkp-lib/issues/4991
> #4991 category article page

- classes/plugins/PubObjectsExportPlugin.inc.php
(cherry picked from commit 7e432172447987983a27cc6b2596a6e54a94f889)
> [OJS][3.2.0] #5961 Use the Schema::get:: hook for registering PubObjectsExportPlugin additional schema fields

- classes/plugins/PubObjectsExportPlugin.inc.php
(cherry picked from commit 7e432172447987983a27cc6b2596a6e54a94f889)
> [OJS][3.2.1] #5961 Use the Schema::get:: hook for registering PubObjectsExportPlugin additional schema fields

- plugins/importexport/crossref/filter/ArticleCrossrefXmlFilter.inc.php
(cherry picked from commit 6e35d45927ae7bd9fd15898f1f661da89e8d9272)
> [OJS][3.2.1] #6021 $submission changed to $publication for title data

- classes/submission/Submission.inc.php
- templates/frontend/objects/article_details.tpl
Fix the display of the copyright statement when a custom copyright holder is configured.
> pkp/pkp-lib#6041 Fix copyright statement display

- package-lock.json
see https://github.com/pkp/pkp-lib/issues/6069
> pkp/pkp-lib#6069 updated version in package-lock.json to 3.2.1

- docs/UPGRADE.md
Since the file  _README-GIT.md_ not longer exists, I updated it to the main _README.md_
> Fix page not found

- api/v1/issues/IssueHandler.inc.php
- classes/components/listPanels/SubmissionsListPanel.inc.php
- classes/services/IssueService.inc.php
- classes/services/SubmissionService.inc.php
- classes/services/queryBuilders/IssueQueryBuilder.inc.php
- docs/dev/swagger-source.json
- locale/en_US/editor.po
For this issue: https://github.com/pkp/pkp-lib/issues/6054
> i6054 issue filter

- templates/payments/subscriptionPolicyForm.tpl
Add email and tel type for the templates.
> Update input type

- index.php
Since currently the development is 3.x, I thought that this might help.
> Remove the version number from OJS

- docs/README-CSV.md
Since LibreOffice is currently more active than Apache OpenOffice, I see it as a good replacement.
> doc: Replace OpenOffice with LibreOffice

- plugins/pubIds/urn/classes/form/URNSettingsForm.inc.php
Add urn:nbn:fi to form settings.
> Add Finnish Namespace for URN's

- templates/frontend/objects/article_details.tpl
Issue:
https://github.com/pkp/pkp-lib/issues/5912
> ROR Id support for default template

- plugins/reports/counter/classes/reports/CounterReportAR1.inc.php
s. https://github.com/pkp/pkp-lib/issues/6414
> pkp/pkp-lib#6414 fix the type, cast to required type

- plugins/importexport/medra/MedraExportPlugin.inc.php
- plugins/importexport/medra/classes/MedraWebservice.inc.php
- plugins/importexport/medra/classes/form/MedraSettingsForm.inc.php
- plugins/importexport/medra/filter/ArticleMedraXmlFilter.inc.php
- plugins/importexport/medra/filter/IssueMedraXmlFilter.inc.php
- plugins/importexport/medra/filter/O4DOIXmlFilter.inc.php
- plugins/importexport/medra/locale/en_US/locale.xml
- plugins/importexport/medra/locale/it_IT/locale.xml
- plugins/importexport/medra/templates/crDepositErrors.tpl
- plugins/importexport/medra/templates/index.tpl
Here are the changes of the medra plugin to support another mEDRA service, the DOI Crossref deposit.
The PR contains the contribution of @njikonga-med provided in the PR https://github.com/pkp/ojs/pull/2597, as well as some further changes and fixes.
> Medra test

- plugins/importexport/medra/MedraExportPlugin.inc.php
- plugins/importexport/medra/classes/MedraWebservice.inc.php
- plugins/importexport/medra/classes/form/MedraSettingsForm.inc.php
- plugins/importexport/medra/filter/ArticleMedraXmlFilter.inc.php
- plugins/importexport/medra/filter/O4DOIXmlFilter.inc.php
- plugins/importexport/medra/locale/en_US/locale.po
- plugins/importexport/medra/locale/it_IT/locale.po
- plugins/importexport/medra/templates/crDepositErrors.tpl
- plugins/importexport/medra/templates/index.tpl
Here are the changes of the medra plugin to support another mEDRA service, the DOI Crossref deposit.
The PR contains the contribution of @njikonga-med provided in the PR #2597, as well as some further changes and fixes.
> mEDRA plugin modification to enable also the Crossref deposit

- classes/article/ArticleGalleyDAO.inc.php
- classes/issue/IssueDAO.inc.php
- plugins/importexport/datacite/DataciteExportPlugin.inc.php
- plugins/importexport/datacite/classes/form/DataciteSettingsForm.inc.php
- plugins/importexport/datacite/filter/DataciteXmlFilter.inc.php
- plugins/importexport/datacite/locale/en_US/locale.po
- plugins/importexport/datacite/templates/settingsForm.tpl
s. https://github.com/pkp/pkp-lib/issues/6411
there is `catch (GuzzleHttp\Exception\RequestException $e)`. should there be `catch (Exception $e)` too?
> pkp/pkp-lib#6411 add datacite test account settings and consider datacite test api 

- plugins/importexport/datacite/DataciteExportPlugin.inc.php
- plugins/importexport/datacite/filter/DataciteXmlFilter.inc.php
strange... but i discovered these errors just now...
> datacite plugin fixes

- classes/search/ArticleSearch.inc.php
- classes/search/ArticleSearchIndex.inc.php
> pkp/pkp-lib#5388 Submission keywords are not indexed/searchable

- classes/migration/upgrade/OJSv3_3_0UpgradeMigration.inc.php
s. https://github.com/pkp/pkp-lib/issues/6566 (pkp/ojs@f32d0e2)
> pkp/pkp-lib#6566 remove mEDRA dependencies from the DB

- cypress/tests/data/60-content/AmwandengaSubmission.spec.js
- cypress/tests/data/60-content/CcorinoSubmission.spec.js
* pkp/pkp-lib#6387 Restoring tests for keywords input at file `AmwandengaSubmission`, test `Editor can edit publication details` and file `CcorinoSubmission`, test `Create a submission`.
> pkp/pkp-lib#6387 Restoring tests for keywords input

- config.TEMPLATE.inc.php
- docs/release-notes/README-3.4.0
Added new setting to the config
> Closes pkp/pkp-lib#6539 Extended reCaptcha to the login page.

- plugins/generic/usageEvent/UsageEventPlugin.inc.php
s. https://github.com/pkp/pkp-lib/issues/4904
> pkp/pkp-lib#4904 fix usage stats 

- classes/migration/upgrade/OJSv3_3_0UpgradeMigration.inc.php
s. https://github.com/pkp/pkp-lib/issues/6956
> pkp/pkp-lib#6956 fix medra upgrade for ojs 3.3.0

- config.TEMPLATE.inc.php
Resolves pkp/pkp-lib#6994 for OJS.
> Remove implicit_auth

- config.TEMPLATE.inc.php
> remove commercial URLs

- classes/controllers/grid/issues/IssueGridHandler.inc.php
- classes/issue/Collector.inc.php
- classes/issue/Repository.inc.php
- classes/journal/JournalDAO.inc.php
- pages/gateway/GatewayHandler.inc.php
Hi @asmecher, thanks for reviewing these!
This addresses a typo in the collector, removing the "current issue" status from an issue when its unpublished, and updating the CLOCKSS refactor to match that of LOCKSS.
> pkp/pkp-lib#7247 Fix bugs introduced in Issue EntityDAO refactor

- classes/controllers/grid/issues/IssueGridHandler.inc.php
See https://github.com/pkp/pkp-lib/issues/7292
> pkp/pkp-lib#7292 Consider also published submissions when publishing a new issue

- templates/controllers/grid/settings/sections/form/sectionForm.tpl
Issue: pkp/pkp-lib#5266
Signed-off-by: Pedro Marinho <pedro@lepidus.com.br>
Signed-off-by: João Vitor <joaovitor@lepidus.com.br>
> Remove arbitrary character limit in section title

- locale/ja_JP/admin.po
- locale/ja_JP/api.po
- locale/ja_JP/emails.po
- locale/ja_JP/manager.po
- locale/ja_JP/submission.po
- fix bug: "ガレ刷り" sholud be "ゲラ刷り"
- fix bug: "読期間終了（最終案内）" sholud be "購読期間終了（最終案内）"
- translate some untranslated messages
> Update ja_JP locale

- classes/migration/upgrade/v3_4_0/I7014_DoiMigration.inc.php
Expansion on #3314 to include galleys and issues.
> pkp/pkp-lib#7737 DOI migration failure

- plugins/generic/dublinCoreMeta/DublinCoreMetaPlugin.inc.php
- templates/frontend/pages/article.tpl
Related issue: pkp/pkp-lib#7864
> pkp/pkp-lib#7864 Use full title in page title and "DC.Title" metadata

- classes/controllers/grid/issues/IssueGridHandler.inc.php
This PR aims to fix pkp/pkp-lib#7957 .
> pkp/pkp-lib#7957 Issue publishing feature is not working properly

- api/v1/dois/DoiHandler.php
- classes/doi/Repository.php
- classes/issue/Repository.php
- classes/submission/Repository.php
- cypress/tests/integration/Doi.spec.js
- locale/en_US/locale.po
- templates/management/dois.tpl
Expand error messaging and make DOI exception generic
> pkp/pkp-lib#7518 Expand DOI bulk actions

- classes/migration/install/OJSMigration.php
https://forum.pkp.sfu.ca/t/change-table-publication-settings-setting-value-datatype-from-text-to-mediumtext/73916
pkp/ojs:
classes/migration/install/OJSMigration.inc.php
pkp/pkp-lib:
lib/pkp/classes/migration/install/AnnouncementsMigration.inc.php
lib/pkp/classes/migration/install/CategoriesMigration.inc.php
lib/pkp/classes/migration/install/CommonMigration.inc.php
lib/pkp/classes/migration/install/ControlledVocabMigration.inc.php
lib/pkp/classes/migration/install/DoiMigration.inc.php
lib/pkp/classes/migration/install/GenresMigration.inc.php
lib/pkp/classes/migration/install/LibraryFilesMigration.inc.php
lib/pkp/classes/migration/install/LogMigration.inc.php
lib/pkp/classes/migration/install/MetadataMigration.inc.php
lib/pkp/classes/migration/install/NavigationMenusMigration.inc.php …
> pkp/pkp-lib#8157 Change tables ..._settings > setting_value datatype from TEXT to MEDIUMTEXT

- pages/search/SearchHandler.inc.php
Issue
- https://github.com/pkp/pkp-lib/issues/7310
> pkp/pkp-lib#7310 Adding reviewer does not include required country field for created user.

- plugins/generic/htmlArticleGalley/HtmlArticleGalleyPlugin.inc.php
s. https://github.com/pkp/pkp-lib/issues/7330
>  pkp/pkp-lib#7330 consider version in the HTML image download URL 

- plugins/generic/htmlArticleGalley/HtmlArticleGalleyPlugin.php
s. https://github.com/pkp/pkp-lib/issues/7330
> pkp/pkp-lib#7330 consider version in the HTML image download URL

- plugins/reports/articles/ArticleReportPlugin.php
s. https://github.com/pkp/pkp-lib/issues/7691
> pkp/pkp-lib#7691 add first date published to the article report 

- classes/migration/upgrade/v3_4_0/I7796_UpdateCrossrefSchema.php
- dbscripts/xml/upgrade.xml
s. https://github.com/pkp/pkp-lib/issues/7796
> pkp/pkp-lib#7796 update crossref schema to 5.3.1 

- api/v1/issues/IssueHandler.php
- api/v1/stats/issues/StatsIssueHandler.php
- api/v1/stats/sushi/StatsSushiHandler.php
s. https://github.com/pkp/pkp-lib/issues/6781
> pkp/pkp-lib#6781 Opt-out for public SUSHI API

- classes/issue/DAO.php
- classes/issue/Repository.php
- controllers/grid/subscriptions/InstitutionalSubscriptionForm.php
s. https://github.com/pkp/pkp-lib/issues/8240
> pkp/pkp-lib#8240 Consider parent object ID in DAO exists and get functions

- classes/issue/DAO.php
this is part of the issue https://github.com/pkp/pkp-lib/issues/8240.
It fixes the docblock summary of the trait abstract method implementation
> pkp/pkp-lib#8240 fix method summary 

- dbscripts/xml/upgrade.xml
- registry/emailTemplates.xml
This aims to provide solution to https://github.com/pkp/pkp-lib/issues/4789
> pkp/pkp-lib#4789 Permit declined reviews to be reinitiated

- locale/en_US/manager.po
Changed text to indicate the plugin is available and can be used.
> Updated PKP|PN text

- api/v1/stats/issues/StatsIssueHandler.php
- locale/en_US/manager.po
- pages/stats/StatsHandler.php
s. https://github.com/pkp/pkp-lib/issues/7318
This PR contains only a fix (removal of the unused namespace) and the pkp-lib submodule update
> a fix and submodule update

- api/v1/stats/issues/StatsIssueHandler.php
s. https://github.com/pkp/pkp-lib/issues/8328
> timeline report download possibility

- schemas/galley.json
This PR aims to solve pkp/pkp-lib#8327
> pkp/pkp-lib#8327 Locale regex validation rules update to support 2 character locale code

- classes/controllers/grid/issues/IssueGridHandler.php
This PR just adds a missing use of a class...
> add missing class namespace

- locale/ar_IQ/manager.po
- locale/bg_BG/manager.po
- locale/cs_CZ/manager.po
- locale/da_DK/manager.po
- locale/hy_AM/manager.po
- locale/id_ID/manager.po
- locale/lv_LV/manager.po
- locale/nb_NO/manager.po
- locale/pl_PL/manager.po
- locale/pt_BR/manager.po
- locale/pt_PT/manager.po
- locale/sl_SI/manager.po
- locale/sv_SE/manager.po
- locale/tr_TR/manager.po
- locale/uz_UZ@latin/manager.po
- locale/zh_TW/manager.po
s. https://github.com/pkp/pkp-lib/issues/7318
> pkp/pkp-lib#7318 fix locale keys 

- docs/dev/swagger-source.json
s. https://github.com/pkp/pkp-lib/issues/8014
> pkp/pkp-lib#8014 swagger stats API documentation

- plugins/generic/htmlArticleGalley/HtmlArticleGalleyPlugin.php
- plugins/generic/htmlArticleGalley/templates/display.tpl
s. https://github.com/pkp/pkp-lib/issues/6849
> pkp/pkp-lib#6849 Tool to convert old and apache log files into new format, further considerations

- dbscripts/xml/upgrade.xml
s. https://github.com/pkp/pkp-lib/issues/8508
> pkp/pkp-lib#8508 convert current usage stats log file at upgrade 

- templates/frontend/objects/article_details.tpl
Added ul/li to structure the author list
Removed H3 heading from the list accordingly to https://github.com/pkp/pkp-lib/issues/6901
Removed span tag from affiliation to keep the black color for the name and institution.
This PR is related to https://github.com/pkp/ojs/pull/3702 which will be closed.
> pkp/pkp-lib#5726 Use lists for authors and author biographies (fixed)

- .travis.yml
s. https://github.com/pkp/pkp-lib/issues/8490
> pkp/pkp-lib#8490 consider mariaDB in Travis 

- plugins/importexport/doaj/DOAJExportPlugin.php
This PR aims to provide solution for pkp/pkp-lib#8609
> pkp/pkp-lib#8609 Fixed DOAJSettingsForm namespace return path

- plugins/generic/dublinCoreMeta/DublinCoreMetaPlugin.php
s. https://github.com/pkp/pkp-lib/issues/8406
> pkp/pkp-lib#8406 Improve DublinCoreMetaPlugin

- classes/template/TemplateManager.php
- cypress/tests/data/60-content/AmwandengaSubmission.cy.js
- cypress/tests/integration/Z_ArticleViewDCMetadata.cy.js
- plugins/blocks/languageToggle/LanguageToggleBlockPlugin.php
This PR introduce update/patch for pkp/pkp-lib#7352
> pkp/pkp-lib#7352 Locale presentation update

- templates/frontend/objects/article_details.tpl
- https://github.com/pkp/orcidProfile/issues/232
> pkp/orcidProfile#232  Display Orcid Icon only for authenticated users

- plugins/importexport/native/filter/IssueNativeXmlFilter.php
- plugins/importexport/native/filter/NativeXmlIssueFilter.php
- plugins/reports/counter/classes/reports/CounterReportAR1.php
s. https://github.com/pkp/pkp-lib/issues/8369
> pkp/pkp-lib#8369 Consider new DOI implementation in other parts of the code

- config.TEMPLATE.inc.php
- controllers/grid/submissions/ExportPublishedSubmissionsListGridCellProvider.php
- controllers/grid/submissions/ExportPublishedSubmissionsListGridHandler.php
- cypress/tests/data/60-content/AmwandengaSubmission.cy.js
- cypress/tests/integration/Z_ArticleViewDCMetadata.cy.js
- plugins/generic/datacite/filter/DataciteXmlFilter.php
- plugins/generic/htmlArticleGalley/templates/display.tpl
- plugins/importexport/doaj/filter/DOAJJsonFilter.php
- plugins/importexport/doaj/filter/DOAJXmlFilter.php
- plugins/importexport/native/templates/index.tpl
- plugins/importexport/pubmed/filter/ArticlePubMedXmlFilter.php
- plugins/importexport/pubmed/templates/index.tpl
- plugins/reports/articles/ArticleReportPlugin.php
- templates/frontend/objects/article_details.tpl
- templates/frontend/objects/article_summary.tpl
- templates/frontend/pages/article.tpl
This PR aims to add enhancement for pkp/pkp-lib#2564
> pkp/pkp-lib#2564 Minimal HTML editor for submission title

- classes/section/DAO.php
- classes/section/Repository.php
s. https://github.com/pkp/pkp-lib/issues/7128
> pkp/pkp-lib#7128 fix customSectionOrdering

- plugins/importexport/crossref/CrossRefExportPlugin.inc.php
s. https://github.com/pkp/crossref-ojs/issues/30
> Fix crossref deposit file name

- api/v1/stats/editorial/StatsEditorialHandler.php
- api/v1/stats/publications/StatsPublicationHandler.php
- classes/services/OJSServiceProvider.php
- classes/subscription/InstitutionalSubscriptionDAO.php
- classes/sushi/IR.php
- plugins/generic/htmlArticleGalley/HtmlArticleGalleyPlugin.php
- plugins/reports/counter/classes/reports/CounterReportAR1.php
s. https://github.com/pkp/pkp-lib/issues/8851
> pkp/pkp-lib#8851 fixes for stats, sections, institutions 

- templates/frontend/objects/article_details.tpl
- https://github.com/pkp/orcidProfile/issues/232
> pkp/orcidProfile#232 Display Orcid Icon only for authenticated users

- classes/plugins/DOIPubIdExportPlugin.php
s. https://github.com/pkp/pkp-lib/issues/8838
This PR also contains crossref submodule update, because of another fix
> pkp/pkp-lib#8838 Display index page for Tools > Import/Export > any DOI plugin

- classes/plugins/PubIdPlugin.php
s. https://github.com/pkp/pkp-lib/issues/8940
> pkp/pkp-lib#8940 fix checkDuplicate

- plugins/importexport/doaj/DOAJExportPlugin.php
s. https://github.com/pkp/pkp-lib/issues/8987
> pkp/pkp-lib#8987 adapt DOAJ API base URL

- plugins/importexport/doaj/DOAJExportPlugin.inc.php
s. https://github.com/pkp/pkp-lib/issues/8987
> pkp/pkp-lib#8987 adapt DOAJ API base URLs

- plugins/importexport/doaj/filter/DOAJJsonFilter.inc.php
s. https://github.com/pkp/pkp-lib/issues/8462
> pkp/pkp-lib#8462 consider ORCID in DOAJ JSON export

- plugins/generic/datacite/filter/DataciteXmlFilter.php
s. https://github.com/pkp/pkp-lib/issues/9020
> pkp/pkp-lib#9020 rename not existing function getSize into fileSize

- plugins/generic/datacite/DatacitePlugin.php
- plugins/generic/datacite/filter/DataciteXmlFilter.php
s. https://github.com/pkp/pkp-lib/issues/9044
> pkp/pkp-lib#9044 fix DataCite galleys export and deposit

- plugins/generic/datacite/filter/DataciteXmlFilter.php
s. https://github.com/pkp/pkp-lib/issues/9054
> pkp/pkp-lib#9054 fix DataCite issue export

- plugins/importexport/datacite/filter/DataciteXmlFilter.inc.php
s. https://github.com/pkp/pkp-lib/issues/9068
> pkp/pkp-lib#9068 consider ROR in DataCite affiliation element

- plugins/importexport/crossref/CrossrefExportDeployment.inc.php
- plugins/importexport/crossref/filter/ArticleCrossrefXmlFilter.inc.php
Resolves pkp/pkp-lib#9126 for 3.3.x; backport of https://github.com/pkp/crossref-ojs/pull/38
> pkp/pkp-lib#9126: backport for multilingual crossref metadata

- plugins/generic/datacite/classes/DataciteSettings.php
s. https://github.com/pkp/pkp-lib/issues/9161
> pkp/pkp-lib#9161 fix testDOIPrefix setting type in DataciteSettings form

- dbscripts/xml/upgrade.xml
- plugins/generic/usageEvent/settings.xml
s. https://github.com/pkp/pkp-lib/issues/9136
> pkp/pkp-lib#9136 introduce new and migrate old uniqueSiteId

- classes/sushi/IR.php
- plugins/generic/datacite/filter/DataciteXmlFilter.php
- plugins/generic/dublinCoreMeta/DublinCoreMetaPlugin.php
- plugins/importexport/doaj/filter/DOAJJsonFilter.php
- plugins/importexport/doaj/filter/DOAJXmlFilter.php
- plugins/metadata/dc11/filter/Dc11SchemaArticleAdapter.php
- plugins/oaiMetadataFormats/dc/tests/expectedResult.xml
- plugins/oaiMetadataFormats/marc/templates/record.tpl
- plugins/oaiMetadataFormats/marcxml/templates/record.tpl
s. https://github.com/pkp/pkp-lib/issues/9184
> pkp/pkp-lib#9184 fix getFullName, make dc:creator multilingual

- js/load.js
Component registration for AdvancedSearchReviewerContainer
linked to:
https://github.com/pkp/ui-library/pull/275
> Register component AdvancedSearchReviewerContainer

- plugins/generic/announcementFeed/AnnouncementFeedGatewayPlugin.php
s. https://github.com/pkp/pkp-lib/issues/9226
> pkp/pkp-lib#9226 use isActive filter in AnnouncementFeedGatewayPlugin 

- cypress/tests/integration/SubmissionWizard.cy.js
- plugins/metadata/dc11/filter/Dc11SchemaArticleAdapter.php
- plugins/oaiMetadataFormats/dc/tests/OAIMetadataFormat_DCTest.php
- Remove Languages option from Workflow Settings > Submission > Metadata
> Remove separate Dublin Core Language metadata field and only use Submission Locale to define the language

- dbscripts/xml/upgrade.xml
- registry/userGroups.xml
s. https://github.com/pkp/pkp-lib/issues/9552
> pkp/pkp-lib#9552 add masthead option to user roles 

- classes/migration/install/MetricsMigration.php
- dbscripts/xml/upgrade.xml
- jobs/statistics/CompileUsageStatsFromTemporaryRecords.php
s. https://github.com/pkp/pkp-lib/issues/9627
> pkp/pkp-lib#9627 Add indexes to usage stats temporary tables 

- plugins/importexport/datacite/filter/DataciteXmlFilter.inc.php
s. https://github.com/pkp/pkp-lib/issues/9623
> pkp/pkp-lib#9623 fix creating an ULR when running from CLI

- classes/components/forms/counter/CounterReportForm.php
- classes/sushi/IR.php
- classes/sushi/IR_A1.php
- classes/sushi/PR.php
- classes/sushi/PR_P1.php
- classes/sushi/TR.php
- classes/sushi/TR_J3.php
- js/load.js
s. https://github.com/pkp/pkp-lib/issues/8248
> pkp/pkp-lib#8248 COUNTER R5 TSV reports 

- classes/migration/install/MetricsMigration.php
- dbscripts/xml/upgrade.xml
- jobs/statistics/CompileUsageStatsFromTemporaryRecords.php
s. https://github.com/pkp/pkp-lib/pull/9640
> pkp/pkp-lib#9627 Add indexes to usage stats temporary tables, decrease the column ip to 64 characters

- tools/deleteIncompleteSubmissions.php
Issue: https://github.com/pkp/pkp-lib/issues/7495
> Delete incomplete submissions tool compatible for 3.3

- classes/migration/upgrade/v3_4_0/I9813_QuickSubmitSubmissionProgressType.php
- dbscripts/xml/upgrade.xml
s. https://github.com/pkp/pkp-lib/issues/9813
> pkp/pkp-lib#9813 upgrade script to fix frong submission progress values inserted by QuickSubmit plugin

- classes/migration/upgrade/v3_4_0/I9813_QuickSubmitSubmissionProgressType.php
- dbscripts/xml/upgrade.xml
s. https://github.com/pkp/pkp-lib/issues/9813
> pkp/pkp-lib#9813 upgrade script to fix wrong submission progress values inserted by QuickSubmit plugin

- cypress/tests/integration/Pubmed.cy.js
- cypress/tests/integration/Z_ArticleViewDCMetadata.cy.js
- pages/user/index.php
- plugins/blocks/languageToggle/LanguageToggleBlockPlugin.php
- plugins/blocks/languageToggle/templates/block.tpl
- plugins/generic/datacite/DataciteExportPlugin.php
- plugins/generic/datacite/filter/DataciteXmlFilter.php
- plugins/generic/dublinCoreMeta/DublinCoreMetaPlugin.php
- plugins/generic/recommendByAuthor/templates/articleFooter.tpl
- plugins/generic/recommendBySimilarity/RecommendBySimilarityPlugin.php
- plugins/generic/recommendBySimilarity/templates/articleFooter.tpl
- plugins/importexport/doaj/filter/DOAJJsonFilter.php
- plugins/importexport/doaj/filter/DOAJXmlFilter.php
- plugins/importexport/pubmed/PubMedExportPlugin.php
- plugins/metadata/dc11/filter/Dc11SchemaArticleAdapter.php
- plugins/oaiMetadataFormats/dc/tests/OAIMetadataFormat_DCTest.php
- plugins/oaiMetadataFormats/marc/templates/record.tpl
- plugins/oaiMetadataFormats/marcxml/templates/record.tpl
- plugins/oaiMetadataFormats/rfc1807/OAIMetadataFormat_RFC1807.php
- Show the current locale in the url in multilingual contexts.
- Old links without the locale are redirected to include the current locale.
- Monolingual contexts do not have the locale
> pkp/pkp-lib#699 Show locale in url in multilingual contexts

- controllers/grid/articleGalleys/ArticleGalleyGridCellProvider.php
- controllers/grid/articleGalleys/ArticleGalleyGridHandler.php
https://github.com/pkp/pkp-lib/issues/9976
> pkp/pkp-lib#9976 Display Galley language in Galleys Grid

- classes/article/ArticleGalleyDAO.inc.php
- classes/article/AuthorDAO.inc.php
- classes/issue/IssueDAO.inc.php
- classes/services/queryBuilders/GalleyQueryBuilder.inc.php
- classes/services/queryBuilders/IssueQueryBuilder.inc.php
- classes/submission/SubmissionDAO.inc.php
- classes/subscription/IndividualSubscriptionDAO.inc.php
- classes/subscription/InstitutionalSubscriptionDAO.inc.php
- classes/subscription/SubscriptionTypeDAO.inc.php
> Feature/stable 3 3 0/8700 improve slow query

- classes/issue/Collector.php
Adds order by date published to fix error in API issue endpoint.
Related issue: pkp/pkp-lib#10012
> pkp/pkp-lib#10012 Adds ordering of issues by date published

- api/v1/invitations/index.php
- dbscripts/xml/upgrade.xml
- pages/reviewer/ReviewerHandler.php
- registry/emailTemplates.xml
Replaces https://github.com/pkp/ojs/pull/4244
> [OJS][main] #9887 Invitation API Support

- .github/workflows/schedule.yml
Issue
-
https://github.com/pkp/pkp-lib/issues/9214
> OJS schedule for 3.3

- api/v1/stats/issues/StatsIssueController.php
s. https://github.com/pkp/pkp-lib/issues/10145
only submodule update
> pkp/pkp-lib#10145 submodule update ##bozana/10145##

- locale/es_ES/locale.po
Chains added:
- user.authorization.journalDoesNotPublish
- installer.updatingInstructions
Full list of changes detailed here:
https://hackmd.io/x34g_qFOSoGHDvdfrOnE0Q?edit
> Missing translations in es_ES: "Updating instructions..."

- api/v1/submissions/SubmissionController.php
- locale/en/api.po
For https://github.com/pkp/pkp-lib/issues/10336
> pkp/pkp-lib#10336 Expose publication forms

- docs/dev/swagger-source.json
>  pkp/pkp-lib#10465 Improve GET submissions/{submissionId}/decisions endpoint

- docs/dev/swagger-source.json
> pkp/pkp-lib#10130 Add ORCID endpoint documentation

- api/v1/emails/index.php
- docs/dev/swagger-source.json
> pkp/pkp-lib#10412 Add API endpoints for emailLogEntry

- api/v1/submissions/SubmissionController.php
> pkp/pkp-lib#10508 Apply getLocalizedForm method to TitleAbstractForm form

- api/v1/stats/sushi/StatsSushiController.php
- classes/components/forms/counter/CounterReportForm.php
- classes/sushi/IR.php
- classes/sushi/IR_A1.php
- classes/sushi/PR.php
- classes/sushi/PR_P1.php
- classes/sushi/TR.php
- classes/sushi/TR_J3.php
- js/load.js
s.https://github.com/pkp/pkp-lib/issues/9666
> pkp/pkp-lib#9666 COUNTER R5 TSV reports 

- cypress.config.js
- package.json
> Support  cypress iframes , Restrict limits for redirecion

- locale/en/invitation.po
- https://github.com/pkp/pkp-lib/issues/9658
-
> pkp/pkp-lib#10575 Create app-specific locale strings for user invitation workflow

- classes/notification/managerDelegate/ApproveSubmissionNotificationManager.php
> I10636 main

- js/load.js
- https://github.com/pkp/pkp-lib/issues/9658
> Submodule update

- plugins/generic/datacite/DatacitePlugin.php
- plugins/generic/driver/DRIVERPlugin.php
- templates/frontend/objects/article_summary.tpl
s. https://github.com/pkp/pkp-lib/issues/10653
> fix deprecated submission functions

- classes/issue/Collector.php
- classes/submission/Collector.php
> pkp/pkp-lib#10178 Allow search by DOI in DOI manager

- plugins/generic/announcementFeed/AnnouncementFeedGatewayPlugin.php
- plugins/generic/announcementFeed/templates/rss.tpl
- plugins/generic/announcementFeed/templates/rss2.tpl
s. https://github.com/pkp/pkp-lib/issues/9910
> pkp/pkp-lib#9910 Use UI Language in Announcement Feeds

- pages/submission/index.php
For https://github.com/pkp/pkp-lib/issues/8350
> pkp/pkp-lib#8350 Allow authors to cancel submission

- classes/issue/DAO.php
- classes/journal/JournalDAO.php
- classes/plugins/PubIdPlugin.php
- plugins/pubIds/urn/URNPubIdPlugin.php
- plugins/pubIds/urn/js/FieldTextUrn.js
s. https://github.com/pkp/pkp-lib/issues/10821
>  pkp/pkp-lib#10821 fix checkDuplicate, anyPubIdExists, pubIdExists, syntax fix for FieldTextUrn.js 

- pages/article/ArticleHandler.php
- templates/frontend/objects/article_details.tpl
> update ORCiD branding

- api/v1/rors/index.php
- cypress/tests/data/60-content/CmontgomerieSubmission.cy.js
- cypress/tests/data/60-content/EostromSubmission.cy.js
- cypress/tests/data/60-content/KalkhafajiSubmission.cy.js
- dbscripts/xml/install.xml
- dbscripts/xml/upgrade.xml
- pages/article/ArticleHandler.php
- plugins/generic/datacite/filter/DataciteXmlFilter.php
- plugins/importexport/doaj/filter/DOAJJsonFilter.php
- plugins/importexport/doaj/filter/DOAJXmlFilter.php
- plugins/importexport/native/README.md
- plugins/importexport/pubmed/filter/ArticlePubMedXmlFilter.php
- plugins/oaiMetadataFormats/dc/tests/OAIMetadataFormat_DCTest.php
- plugins/oaiMetadataFormats/marc/templates/record.tpl
- plugins/oaiMetadataFormats/marcxml/templates/record.tpl
- plugins/oaiMetadataFormats/rfc1807/OAIMetadataFormat_RFC1807.php
- plugins/reports/articles/ArticleReportPlugin.php
- plugins/themes/default/styles/objects/article_details.less
- templates/frontend/objects/article_details.tpl
s. https://github.com/pkp/pkp-lib/issues/7135
and 
the original PR: https://github.com/pkp/ojs/pull/4469
> pkp/pkp-lib#7135 Multiple author affiliations (Ror)

- classes/migration/install/MetricsMigration.php
- dbscripts/xml/upgrade.xml
- jobs/statistics/CompileUniqueInvestigations.php
- jobs/statistics/CompileUniqueRequests.php
s. https://github.com/pkp/pkp-lib/issues/9822
> pkp/pkp-lib#9822 Increase timeout and improve DB table indexes for usage stats jobs

- plugins/generic/announcementFeed/AnnouncementFeedGatewayPlugin.php
- plugins/generic/datacite/filter/DataciteXmlFilter.php
- plugins/generic/dublinCoreMeta/DublinCoreMetaPlugin.php
s. https://github.com/pkp/pkp-lib/issues/10795
> pkp/pkp-lib#10795 introduce LocaleConversion::toBcp47()

- plugins/themes/default/styles/objects/article_details.less
- templates/frontend/objects/article_details.tpl
https://github.com/pkp/pkp-lib/issues/10902
> pkp/pkp-lib#10902 vertical-align ROR SVG in the middle

- cypress/tests/integration/Z_ArticleViewDCMetadata.cy.js
> pkp/pkp-lib#10948 Submodule Update ##touhidurabir/i10948_main##

- classes/controllers/grid/issues/IssueGridHandler.php
- classes/publication/Repository.php
- controllers/grid/issues/IssueGridRow.php
- controllers/grid/issues/form/IssueForm.php
- locale/en/editor.po
- templates/controllers/grid/issues/form/issueForm.tpl
s. https://github.com/pkp/pkp-lib/issues/7165
> 7165 3 5 0

- classes/submission/maps/Schema.php
- schemas/submission.json
> pkp/pkp-lib#11025 Include issue info on submission API data

- dbscripts/xml/upgrade.xml
- pages/article/ArticleHandler.php
s. https://github.com/pkp/pkp-lib/issues/11238
> pkp/pkp-lib#11238 prepare DB for structured citations

- cypress/support/commands.js
- cypress/tests/data/60-content/ZzeddSubmission.cy.js
> pkp/pkp-lib#10993 Reviewer Suggestion E2E test

- classes/controllers/grid/issues/IssueGridHandler.php
- controllers/grid/articleGalleys/ArticleGalleyGridHandler.php
- cypress/tests/data/60-content/AmwandengaSubmission.cy.js
- cypress/tests/data/60-content/VkarbasizaedSubmission.cy.js
- locale/en/submission.po
for [issue##10263](https://github.com/pkp/pkp-lib/issues/10263)
> pkp/pkp-lib#10263 Relax editing metadata on published/posted materials

- plugins/pubIds/urn/URNPubIdPlugin.php
s. https://github.com/pkp/pkp-lib/issues/11260
> pkp/pkp-lib#11260 fix context abbrev in publication URN to be lower case, as it is for all other objects

- classes/migration/upgrade/v3_4_0/I7725_DecisionConstantsUpdate.php
- classes/migration/upgrade/v3_5_0/I11241_MissingDecisionConstantsUpdate.php
- dbscripts/xml/upgrade.xml
> pkp/pkp-lib#11241 Fix missing decisions

- api/v1/announcements/index.php
- api/v1/categories/index.php
- classes/components/forms/publication/IssueEntryForm.php
- classes/migration/upgrade/v3_6_0/I10404_UpdateCategoryImageNameFields.php
- cypress/tests/data/10-ApplicationSetup/50-CreateCategories.cy.js
- cypress/tests/integration/SubmissionWizard.cy.js
- dbscripts/xml/upgrade.xml
- docs/dev/swagger-source.json
- templates/management/context.tpl
> pkp/pkp-lib#10404 Allow nested categories

- locale/en/invitation.po
https://github.com/pkp/pkp-lib/issues/11265#issuecomment-2898507284
> change in invitation locales

- classes/mail/variables/ContextEmailVariable.php
- classes/migration/upgrade/v3_4_0/I7264_UpdateEmailTemplates.php
- classes/migration/upgrade/v3_5_0/I11125_UpdateEmailTemplateVariables.php
- dbscripts/xml/upgrade.xml
For https://github.com/pkp/pkp-lib/issues/11125
> pkp/pkp-lib#11125 Fix: Copyediting Stage, Discussion tags do not populate  [main]

- plugins/importexport/users/sample.xml
s. https://github.com/pkp/pkp-lib/issues/11479
> pkp/pkp-lib#11479 update user import/export sample.xml

- api/v1/stats/issues/StatsIssueController.php
s. https://github.com/pkp/pkp-lib/issues/11485
> pkp/pkp-lib#11485 allow ROLE_ID_SUB_EDITOR access to context stats

- cypress/tests/integration/Subscriptions.cy.js
> pkp/pkp-lib#11474 Allow search by role in Users & Roles search (stable3.5)

- cypress/tests/integration/Subscriptions.cy.js
> pkp/pkp-lib#11474 Allow search by role in Users & Roles search (main)

- api/v1/comments/index.php
- dbscripts/xml/install.xml
- dbscripts/xml/upgrade.xml
> pkp/pkp-lib#11326 Implement backend infrastructure for managing and moderating public comments

- classes/tasks/SubscriptionExpiryReminder.php
- jobs/notifications/IssuePublishedNotifyUsers.php
> pkp/pkp-lib#11303 Submodule Update ##touhidurabir/i11303_stable_3_4_0##

- plugins/generic/datacite/DataciteExportPlugin.php
- plugins/generic/datacite/DatacitePlugin.php
s. https://github.com/pkp/pkp-lib/issues/11621
> pkp/pkp-lib#11621 save DataCite deposit errors

- classes/search/ArticleSearchDAO.php
for [#10139](https://github.com/pkp/pkp-lib/issues/10139)
> pkp/pkp-lib#10139 Fix author search returning keyword matches

- classes/search/ArticleSearchDAO.inc.php
fix for [#10139](https://github.com/pkp/pkp-lib/issues/10139)
> pkp/pkp-lib#10139 fix Author search pulls in keywords too

- dbscripts/xml/upgrade.xml
> pkp/pkp-lib#11603 Missing email template for role assignment invitation

- classes/doi/Repository.php
s. https://github.com/pkp/pkp-lib/issues/10553
> pkp/pkp-lib#10553 getDoisForPublication() 

- docs/dev/swagger-source.json
> pkp/pkp-lib#11824 Add API documentation for public user comments

- classes/core/Application.php
> pkp/pkp-lib#9968 Blade templating engine integration

- classes/submission/DAO.php
s. https://github.com/pkp/pkp-lib/issues/11589
> pkp/pkp-lib#11589 consider EXPORT_STATUS_DEPOSITABLE in submission DAO
