pkp/ojs

plugins/generic/pln/classes/tasks/Depositor.inc.php

Make PLN plugin checks for the curl and zip extensions, rather than checking for the curl extension twice.
Fixes pkp/pkp-lib#266

Check that the zip extension is installed in PHP.

---

plugins/generic/pln/PLNPlugin.inc.php
plugins/generic/pln/classes/tasks/Depositor.inc.php

Check for the presence of the Archive_Tar extension, included with PECL.... the BagIt library requires it, but does not check for its presence.
Fixes bugzilla 8976.

Check for Archive_Tar

---

plugins/generic/pln/classes/DepositPackage.inc.php

Report upload file sizes in 1000 byte units (kB) instead of 1024 byte units (KB), as that's what SWORD expects.
Fixes pkp/pkp-lib#268

Report upload sizes in 1000 byte units

---

plugins/generic/pln/classes/DepositPackage.inc.php

Instead of exporting to the bag directory, use PHP's built-in temporary file support. This prevents duplicate files in the bag. The temp files are automatically cleaned up by PHP and the host OS.
Fixes pkp/pkp-lib#269

Export to temporary files in the pkp pln plugin

---

templates/manager/setup/step5.tpl

This allows taking advantage of the available space.
I also added id's to identify assign to left, right or unselected column. Those are not strictly nececceary, but could be useful for styling/scripting purposes.

*8990* Make cells in step5 (assign blocks to sidebars) have relative widths

---

plugins/generic/pln/PLNPlugin.inc.php
plugins/generic/pln/classes/DepositPackage.inc.php
plugins/generic/pln/classes/form/PLNSettingsForm.inc.php
plugins/generic/pln/classes/form/PLNStatusForm.inc.php
plugins/generic/pln/locale/de_DE/locale.xml
plugins/generic/pln/locale/en_US/locale.xml
plugins/generic/pln/locale/ru_RU/locale.xml
plugins/generic/pln/xml/settings.xml

*9016* PLN plugin fix update - Settings are not created for plugins during an upgrade installation. This work around supplies defaults for any setting that isn't found. 
(cherry picked from commit 5700ede93bf52baa79d554c14b2db966e7fad865)
(cherry picked from commit 9c59d866df64be8041e9b473f9cba73bb5b2a088)
Fixes bugzilla 9016.

*9016* PLN plugin now checks for null settings and applies defaults.

---

plugins/generic/dataverse/DataversePlugin.inc.php

Some markup accepted in dataset metadata in Dataverse 3, but not in 4.

pkp/pkp-lib#282 Dataverse plugin: remove markup from dataset metadata

---

plugins/generic/pln/PLNPlugin.inc.php

Let's make this function available more broadly.  Also fix the UUID v4 generation to appropriately set the reserved bits (http://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_.28random.29).

Move UUID generation function from PLN plugin to PKP Library (String).  ##ulsdevteam/add-uuid-string-creation##

---

plugins/generic/browse/BrowsePlugin.inc.php
templates/about/editorialPolicies.tpl
templates/about/submissions.tpl

Previously, it was not possible to select the li items seperately for formatting. Now, each has its own id that can be used.

Added li-ids for better css formatting in about subpages

---

styles/lib.css

This PR fixes the path to load the CSS file for the jQuery library tag-it library. This file is required to properly display the "Reviewing Interests" input field in the user details section.

* Fix path to tag-it jQuery lib CSS file in pkp-lib

---

classes/article/ArticleDAO.inc.php
classes/article/ArticleGalleyDAO.inc.php
classes/article/SuppFileDAO.inc.php
classes/issue/IssueDAO.inc.php
classes/plugins/PubIdPlugin.inc.php
classes/plugins/PubIdPluginHelper.inc.php
pages/editor/IssueManagementHandler.inc.php
plugins/pubIds/doi/DOIPubIdPlugin.inc.php
plugins/pubIds/doi/classes/form/DOISettingsForm.inc.php
plugins/pubIds/doi/locale/en_US/locale.xml
plugins/pubIds/doi/templates/doiSuffixEdit.tpl
plugins/pubIds/urn/URNPubIdPlugin.inc.php
plugins/pubIds/urn/classes/form/URNSettingsForm.inc.php
plugins/pubIds/urn/locale/en_US/locale.xml
plugins/pubIds/urn/templates/urnSuffixEdit.tpl

This is a rebase of the original pull request for bug 6625, rebased against ojs-dev-2_4. 
Original pull request:  https://github.com/pkp/ojs/pull/217

*6625* refactor 'exclude and clear for single objects and exclude all issue object...'

---

plugins/generic/pln/PLNPlugin.inc.php
plugins/generic/pln/classes/DepositPackage.inc.php
plugins/generic/pln/classes/form/PLNSettingsForm.inc.php
plugins/generic/pln/templates/settings.tpl

Make the terms_of_use_agreement plugin setting a date (or null) instead of a boolean. Use the date in the terms of use XML with the deposit package.
Fixes pkp/pkp-lib#375

Include terms of use agreement date in deposit xml

---

pages/issue/IssueHandler.inc.php
templates/issue/archive.tpl

Set Issue Cover's locale to the Site's primary locale if no cover information is available for the locale.

pkp/pkp-lib#384: make issue cover locale function consistent with article locale handling

---

plugins/generic/alm/output.tpl

Fix pkp/pkp-lib#523
The solution that I found to the problem is to disassociate $ from jQuery 1.10 before loading the tooltip plugin. It is important that the jQuery variable has jQuery 1.10 at line 46, because the tooltip plugin registers the plugin on the jQuery found in the variable "jQuery" . After the plugin is loaded, we can also disassociate the jQuery variable (line 53).
This hack solves the problem with pdf viewing. But it is not a generic solution because the jQuery var remains associated to the jQuery 1.10 until the tooltip plugin is loaded.

pkp/pkp-lib#523 Solve jQuery conflict in the ALM plugin

---

locale/en_US/locale.xml
pages/user/RegistrationHandler.inc.php

This ensures no confusion when a user needs to verify their email address in order to proceed with registration for a journal.  Previously, OJS simply redirected the user home, with no indication at all as to what happened.  This now presents the user with a page explaining what to do next -- eg check and validate the email in their inbox.

Present user email validation notification when registering

---

.gitmodules

The ``git://`` protocol is unencrypted so the suggested way of accessing GitHub repositories is via https:// (Git's Smart HTTP transport protocol).  This change will not affect or change the way this repo is cloned, just that the submodules' code is delivered securely.
In addition, in rare cases, the ``git://`` protocol may be blocked by some firewalls since it operates on an unusual port.  In the case of HTTPS, this is far less likely to be affected by such a firewall.

Switch to encrypted submodule URLs

---

plugins/generic/translator/locale.tpl

Pull key from common.xml in pkp-lib.

Correct Translator Plugin's Email Templates header "subject".

---

pages/user/RegistrationHandler.inc.php

Without this change, attempting to login on the Registration form with standard authentication (eg ``ImplicitAuth = Off``) & a validated account will always result in the "Email Validation Required" message appearing, preventing login.  This is because the new "is logged in" check from my PR #500 happens before login is tried.
This change resolves this by attempting login with the user's submitted credentials.  If that fails, we know they're registering for the first time so prompt them to validate their email address.
Apologies for missing this in the original PR.

Attempt login first during registration before checking email validation

---

plugins/blocks/languageToggle/LanguageToggleBlockPlugin.inc.php

c.f. Error message in http://forum.pkp.sfu.ca/t/error-creating-new-issue-in-ojs-2-4-6/1206
$templateManager->addStyleSheet() resolves to PKPTemplateManager::addStyleSheet(), which has no second parameter:
https://github.com/pkp/pkp-lib/blob/ojs-dev-2_4/classes/template/PKPTemplateManager.inc.php#L259
Constant STYLE_SEQUENCE_CORE does not exist in the 2.4 codebase.

Remove invalid second parameter from TemplateManager::addStyleSheet() call.

---

plugins/importexport/quickSubmit/index.tpl
templates/author/submit/step3.tpl
templates/editor/issues/createIssue.tpl
templates/editor/issues/issueData.tpl
templates/submission/metadata/metadataEdit.tpl

Arbitrary maxlengths on article and section titles are a source of client complaints.  Let's get rid of them.

Remove arbitrary maxlengths from article titles and section titles.

---

plugins/generic/pln/PLNPlugin.inc.php
plugins/generic/pln/classes/DepositPackage.inc.php
plugins/generic/pln/classes/tasks/Depositor.inc.php
plugins/generic/pln/locale/en_US/locale.xml
plugins/generic/pln/pages/PLNHandler.inc.php

* Add logging to Depositor task, to log process as the task runs.
* Pass the scheduled task to DepositPackage, so its errors can be
logged to the scheduledTaskLogs directory.
* Add a task member to DepositPackage. If the object was created by a
scheduled task, it will send log messages to the scheduledTaskLogs
directory. Otherwise they are sent to error_log().
* Add a bunch of error logging to DepositPackage.
* Make sure that the plugin uses network error messages or HTTP
response codes as appropriate.
* Create locale keys for log messages.
closes pkp/pkp-lib#599

Add error logging (and some general logging) to the pln plugin.

---

plugins/generic/pln/locale/en_US/locale.xml
plugins/generic/pln/pages/PLNHandler.inc.php

* Remove unused variable
* Add error logging
* Return 404 errors when deposits aren't available or the UUID looks
bogus.
* Add locale keys for error messages in the error log.
Fixes pkp/pkp-lib#612

Clean up the deposits page handler a little.

---

plugins/generic/pln/templates/settings.tpl

Makes the labels clickable.
fixes pkp/pkp-lib#611

Add ID attributes to the checkboxes in the pln settings form.

---

plugins/generic/pln/classes/DepositPackage.inc.php

Remove hardcoded 'bag' and use UUID in its place.
Closes pkp/pkp-lib#621

Use deposit UUID as name of working directory when creating deposit

---

locale/en_US/emailTemplates.xml

emailTemplates for EDITOR_DECISION_whatever don't include the decision taken.
This file need to keep sync with the decision status defined in editor.xml:
<message key="editor.article.decision.accept">Accept Submission</message>
<message key="editor.article.decision.pendingRevisions">Revisions Required</message>
<message key="editor.article.decision.resubmit">Resubmit for Review</message>
<message key="editor.article.decision.decline">Decline Submission</message>
PD: Editing directly from github (tabs, 8, no wrapp) to test if this also works fine to pull a request.

EDITOR_DECISION_* don't include the decision taken

---

plugins/themes/default/styles/pages/viewPdf.less

Full screen, no double scrollbars, etc. Probably needs some cross-browser testing.

Style the PDF.js viewer galley page

---

plugins/metadata/dc11/filter/Dc11SchemaArticleAdapter.inc.php

//This PR is here to be discussed, since the devteam may disagree with my considerations and I may be wrong because I've only worked with VuFind and don't know if OHS would have this same problem.
The format of the DC for creator generated for OJS was 'authorname;affiliation', this causes stranges harvests from Vufind.
For example, same authors will be treated differently in VuFind if it harvest some articles from DSpace and others from OJS because the OJS's ones will have its creators declared as 'authorname;affiliation' instead of only 'authorname'.
We've also had problems with users writing wrongs affiliations and then causing a mess in everyone who harvest from us without considering the different creator tag with ';', but this kind of problem is not meant to be a proof of concept …

Change DC11SchemaArticleAdapter to "proper" format creator's tag

---

plugins/generic/pln/classes/DepositPackage.inc.php
plugins/generic/pln/classes/form/PLNSettingsForm.inc.php

Fix pkp/pkp-lib#676
* Use $this instead of $task (undefined) when logging messages in
DepositPackage.
* Log the HTTP status of an error when available in DepositPackage.
* Check that $parts['fragment'] is set explicitly in PLNSettingsForm,
to prevent an error in the logs.
* Accept staging server URLs that include paths.

small bug fixes from making the screen cast.

---

templates/about/index.tpl
templates/about/submissions.tpl

Now, when the user doesn't have the ability to self registration, the user doesn't have access to the Online Submissions (index of about template). 
I think that users should have access to it. In "Online Submissions" template the only thing that should be cutted is the Self-Registration, but the other information could be relevant (Submission Preparation Checklist, Privacy statement ...) because the user could be registered by the Journal Manager.

fix - access to submission information even self registration is disabled

---

plugins/generic/customBlockManager/CustomBlockPlugin.inc.php

Fetch of block content can be empty at:
https://github.com/ulsdevteam/ojs/blob/090c3f257077d9057c17c44efb0266bf16640e0a/plugins/generic/customBlockManager/CustomBlockPlugin.inc.php#L192
Don't use `array_key_exists()` if $blockContent isn't an array.

Suppress warning from custom block plugin when new custom block has no content

---

plugins/generic/googleAnalytics/GoogleAnalyticsPlugin.inc.php
plugins/generic/googleAnalytics/GoogleAnalyticsSettingsForm.inc.php
plugins/generic/googleAnalytics/locale/en_US/locale.xml
plugins/generic/googleAnalytics/settingsForm.tpl

See http://forum.pkp.sfu.ca/t/google-analytics-homepage/3561
This allows the Site Admin, when looking at a journal's Google Analytics settings, to enable those settings within the Site context as well.

pkp/pkp-lib#741 Enable Google Analytics to extend the journal settings to the site level

---

classes/submission/editAssignment/EditAssignment.inc.php
classes/submission/editAssignment/EditAssignmentDAO.inc.php
classes/submission/editor/EditorAction.inc.php

Currently, the date_assigned field in edit_assignments is always null and the date_notified field is set regardless if the SectionEditor is emailed or not about an edit assignment.  This change corrects this behavior by adding get/set methods for dateAssigned to the EditAssignment class and using them in the EditorAction class.

Correctly set date_assigned and date_notified in EditAssignments

---

plugins/importexport/datacite/classes/DOIExportDom.inc.php
plugins/importexport/datacite/classes/DataciteExportDom.inc.php

Addresses https://github.com/pkp/pkp-lib/issues/798, in a way that I think avoids the unset array and uses the cache when available.

pkp/pkp-lib#798: Ensure cached objects are returned if available in DOIExportDom / DataciteExportDom.

---

pages/sitemap/SitemapHandler.inc.php

When a journal uses custom identifiers for articles URL, this URL must
be used for sitemap generation; otherwise search engine harvest
non-canonical URLs.

Use canonical URLs in sitemap

---

plugins/generic/usageStats/UsageStatsOptoutBlockPlugin.inc.php

S. https://github.com/pkp/pkp-lib/issues/685
This is a fix: the opt-out block plug-in should be only displayed on the journal pages.

pkp/pkp-lib#685 the opt-out block is not a site plugin

---

plugins/importexport/native/NativeExportDom.inc.php

Resolves https://github.com/pkp/pkp-lib/issues/818

pkp/pkp-lib#818: check return of $article->getCopyrightHolder() before iterating in Native export

---

plugins/importexport/crossref/CrossRefExportPlugin.inc.php
plugins/importexport/crossref/templates/articles.tpl
plugins/importexport/crossref/templates/issues.tpl

Resolves the first noted problem in https://github.com/pkp/pkp-lib/issues/808 .
Does not address the second issue of whether to display the registered issues or fix the "No issues" message.
Also abstracts the check on the "*pluginname*::registeredDoi" setting so that plugins which extend this plugin will be able to function correctly.

pkp/pkp-lib#808: In Crossref Issue export page, make update/register link issue-dependent

---

plugins/importexport/crossref/CrossRefExportPlugin.inc.php
plugins/importexport/datacite/classes/DOIExportPlugin.inc.php

Resolves https://github.com/pkp/pkp-lib/issues/845, though we have to pass a disposable `$errors` array for each call.

pkp/pkp-lib#845: Reuse canBeExported() for DOIExportPlugin and CrossRefExportPlugin

---

locale/en_US/admin.xml
tools/copyAccessLogFileTool.php

Prevent report of success after shell failure.   Also, align `glob` syntax for cross-platform use, including Solaris.

Check copyAccessLogFileTool exec status

---

plugins/generic/pln/PLNPlugin.inc.php
plugins/generic/pln/locale/en_US/locale.xml
plugins/generic/pln/templates/settings.tpl

The PLN plugin requires the Acron plugin, in order to check the service document, make deposits, and check the status of the deposits in the PLN.
Check if the Acron plugin is enabled, and show a warning on the settings form if it isn't.
Closes pkp/pkp-lib#875

warn if the acron plugin is not enabled.

---

plugins/generic/pln/PLNPlugin.inc.php
plugins/generic/pln/locale/en_US/locale.xml

Check for prerequisites in the PKP PLN plugin, and refuse to enable it unless they are all met. Prevents the WSOD on the plugin manager page when the plugin is enabled before the requirements are satisfied.
Fixes pkp/pkp-lib#948

Prevent WSOD in plugin manager

---

plugins/generic/pln/locale/en_US/locale.xml

OJS journal managers don't need to create an account or login to
it. In general, they won't be able to do that at all.

Update the message about the PLN Staging URL

---

plugins/generic/pln/classes/DepositObjectDAO.inc.php

Fixes pkp/pkp-lib#1038
max() seems to be the right aggregate function to use here, using the most recently modified date in a comparison later.

Silence MySQL error 1055 (42000) warning about non-aggregated columns.

---

locale/de_DE/manager.xml
locale/en_US/manager.xml
plugins/reports/counter/locale/de_DE/ar1.xml
plugins/reports/counter/locale/de_DE/jr1.xml
plugins/reports/counter/locale/de_DE/locale.xml
templates/controllers/statistics/form/reportGeneratorForm.tpl

@beghelli, https://github.com/pkp/ojs/commit/9841786edc150436d57f0f338685cfdaa54c8eee introduced a typo in a key name: `manager.statistics.reports.optinoalColumns.description` instead of `manager.statistics.reports.optionalColumns.description`
Changed this in `locale/en_US/manager.xml` and `templates/controllers/statistics/form/reportGeneratorForm.tpl`
Also updated the de_DE locale according to these latest statistics plugin's updates.

Removed typo in statistics plugin (+ updated de_DE locale)

---

plugins/generic/acron/locale/ar_IQ/locale.xml
plugins/generic/acron/locale/ca_ES/locale.xml
plugins/generic/acron/locale/cs_CZ/locale.xml
plugins/generic/acron/locale/de_DE/locale.xml
plugins/generic/acron/locale/en_US/locale.xml
plugins/generic/acron/locale/es_ES/locale.xml
plugins/generic/acron/locale/eu_ES/locale.xml
plugins/generic/acron/locale/fr_CA/locale.xml
plugins/generic/acron/locale/fr_FR/locale.xml
plugins/generic/acron/locale/pt_BR/locale.xml
plugins/generic/acron/locale/pt_PT/locale.xml
plugins/generic/acron/locale/ru_RU/locale.xml
plugins/generic/acron/locale/tr_TR/locale.xml
plugins/generic/acron/locale/zh_CN/locale.xml
plugins/generic/acron/locale/zh_TW/locale.xml

acron plugin referred to "OCS" instead of "OJS"

fixed: acron plugin language, s/OCS/OJS

---

plugins/importexport/crossref/classes/CrossRefExportDom.inc.php

We are primarily interested in:
>   4.3.5, 4.3.6 (PDF) 5/14/2015 added text/rtf as mime type
[Source](http://doi.crossref.org/schemas/common4.3.6.xsd)
There are a number of backwards compatible changes in 4.3.3 -> 4.3.6, and some *not* backwards compatible changes in the updated Common reference of 4.3.2 -> 4.3.6.
The only change we found in the common include that affected our export was depositor/name -> depositor/depositor_name, but others may exist.

pkp/pkp-lib#1087: Update Crossref schema for export to 4.3.6

---

plugins/generic/pln/PLNGatewayPlugin.inc.php
plugins/generic/pln/ping.dtd
plugins/generic/pln/templates/ping.tpl

Some journals seem to stop contacting the PLN once they've been whitelisted. It's probably a problem of missing prerequisites, but we have no way to tell without asking the journal manager to look for log files, check the prerequisites, or do other things.
This PR will add the prerequisites to the ping response, so we can check directly.
/cc @mjordan

Report plugin prerequisites in the ping response.

---

plugins/importexport/crossref/classes/CrossRefExportDom.inc.php
plugins/importexport/pubmed/PubMedExportDom.inc.php

Resolves https://github.com/pkp/pkp-lib/issues/1097 by stripping HTML from the abstract.  A superior solution could perform a transform (as applicable) to JATS elements, but that is for https://github.com/pkp/pkp-lib/issues/1098.

pkp/pkp-lib#1097: remove HTML and HTML entities from abstracts exported via CrossRef and PubMed plugins.

---

config.TEMPLATE.inc.php
docs/release-notes/README-2.4.8
plugins/generic/pln/PLNPlugin.inc.php
plugins/generic/pln/classes/form/PLNStatusForm.inc.php
plugins/generic/pln/locale/en_US/locale.xml
plugins/generic/pln/templates/status.tpl

The URL defaults to $PLN_URL/docs/status.html where $PLN_URL is the
config setting locks:pln_network, and can be overridden with
locks:pln_status_docs.
Usually, that URL will be http://pkp-pln.lib.sfu.ca/docs/status (which
is 404 at the moment).
Closes pkp/pkp-lib#1045.

Add a configurable URL pointing to documentation for the PLN status page

---

plugins/generic/pln/PLNPlugin.inc.php
plugins/generic/pln/classes/DepositPackage.inc.php
plugins/generic/pln/classes/form/PLNSettingsForm.inc.php
plugins/generic/pln/locale/en_US/locale.xml
plugins/generic/pln/templates/settings.tpl

* Refactor checking for acron/scheduled tasks into a plugin method.
* Check and report acron and the other prerequisites in a unified
manner.
* Add a locale key for bagit loading errors.
* Be more careful about how the bagit library is imported, to prevent
WSOD when Archive_Tar isn't available. Only import bagit as needed.
Fixes pkp/pkp-lib#1105
I'll add some notes to the commit below.

Check for missing prerequisites and report them in the plugin settings page

---

plugins/pubIds/urn/js/checkNumber.js

This issue was cleaned by PhpStorm.
Replace also a tab character by blanks.

Add missing semicolon in JavaScript

---

plugins/generic/translator/TranslatorAction.inc.php

Switch Translator plugin processing of plugin locale files from ordered array assumption to calculated names.
The `str_replace` is a weak assumption, but not as weak as the assumption of a consistently ordered list.

pkp/pkp-lib#1175: allow variable locale file lists in Translator

---

plugins/generic/pln/pages/PLNHandler.inc.php

When streaming a download in the PLN plugin, check if the
mime_content_type function is available, fall back to finfo_open if
it's available, or fall back even further to no mime type.
Fixes pkp/pkp-lib#1242

Check for mime_content_type in the PLN plugin before download.

---

plugins/oaiMetadataFormats/nlm/OAIMetadataFormat_NLM.inc.php

Our journals happens to not export the pagerange through NLM.
It happens that ojs's regex is catching  hyphen-minus instead of normal hyphen.
PS.: Could you please cherry pick it to ojs-dev-2_4?

Broaden regex to get pages info [NLM_OAI]

---

plugins/generic/googleViewer/locale/ar_IQ/locale.xml
plugins/generic/googleViewer/locale/ca_ES/locale.xml
plugins/generic/googleViewer/locale/cs_CZ/locale.xml
plugins/generic/googleViewer/locale/da_DK/locale.xml
plugins/generic/googleViewer/locale/de_DE/locale.xml
plugins/generic/googleViewer/locale/en_US/locale.xml
plugins/generic/googleViewer/locale/es_AR/locale.xml
plugins/generic/googleViewer/locale/es_ES/locale.xml
plugins/generic/googleViewer/locale/eu_ES/locale.xml
plugins/generic/googleViewer/locale/fr_CA/locale.xml
plugins/generic/googleViewer/locale/fr_FR/locale.xml
plugins/generic/googleViewer/locale/it_IT/locale.xml
plugins/generic/googleViewer/locale/nl_NL/locale.xml
plugins/generic/googleViewer/locale/pt_BR/locale.xml
plugins/generic/googleViewer/locale/ru_RU/locale.xml
plugins/generic/googleViewer/locale/sr_SR/locale.xml
plugins/generic/googleViewer/locale/tr_TR/locale.xml
plugins/generic/googleViewer/locale/uk_UA/locale.xml
plugins/generic/googleViewer/locale/zh_CN/locale.xml

* Google Doc Viewer web page/description does not exist anymore
* but service is still up
* see <http://googlesystem.blogspot.de/2015/02/google-docs-viewer-page-no-longer.html>

removed (dead) link to Google Doc Viewer

---

templates/issue/archive.tpl

if $issue->getShowCoverPage($coverLocale) decides whether or not to print the Issue cover page, should it also decide whether to print the image in archives list? It seems !$issue->getHideCoverPageArchives($coverLocale) is responsible for that.

Enable Issues images in archives only

---

pages/admin/AdminLanguagesHandler.inc.php

Resolves https://github.com/pkp/pkp-lib/issues/1303
Clearing the old default data is already handled by `installEmailTemplateData()`.
Reloading missing templates will be handled by `installEmailTemplates()`

pkp/pkp-lib#1303: fix Reload Default Email Templates: only erase main email templates, reload any missing templates

---

plugins/reports/counter/CounterReportPluginUnsupported.inc.php
plugins/reports/counter/index.php

Resolves pkp/pkp-lib#1326.
Instanciate an empty, hidden ReportPlugin if PHP doesn't support objects and namespaces.

pkp/pkp-lib#1326: Prevent PHP errors/warnings when bypassing counter plugin load for old PHP versions

---

classes/comment/form/CommentForm.inc.php
classes/user/form/RegistrationForm.inc.php

Partially resolves https://github.com/pkp/pkp-lib/issues/1507 (see also shared library PR)
Allows backwards compatibility in the unlikely case of SSL being forced, but the request coming in over HTTP (a proxy perhaps?) but primarily ensures if the Request is HTTPS, then SSL should be used.

pkp/pkp-lib#1507: Use SSL for RECAPTCHA if protocol is HTTPS or if config requires SSL

---

plugins/generic/pln/classes/DepositObjectDAO.inc.php

* The `DISTINCT pdo.deposit_object_id` is useless, since the query is
grouped by the deposit_object_id column.
* Make the last_modified column of the result aggregated to prevent
database query errors.
Fixes pkp/pkp-lib#1533

Clean up the SQL in markHavingUpdatedContent().

---

plugins/generic/pln/classes/DepositPackage.inc.php

tempnam() creates a temp file but doesn't automatically remove it, unlike tmpfile(). 
Fixes pkp/pkp-lib#1545

Clean up temporary files after processing in the PLN plugin.

---

classes/submission/sectionEditor/SectionEditorAction.inc.php

This pull request moves that status update outside of the $send test, so it happens every time.  Issue here:
https://github.com/pkp/pkp-lib/issues/1564

pkp/pkp-lib#1564 Move status update outside of email send test

---

plugins/importexport/crossref/classes/CrossRefExportDom.inc.php

S. https://github.com/pkp/pkp-lib/issues/1204
This was missing for the stable branch :-(

pkp/pkp-lib#1204 no mime_type for remote galleys in crossref export

---

classes/submission/author/AuthorSubmission.inc.php
classes/submission/sectionEditor/SectionEditorAction.inc.php

After discussion with Co Action, they'd prefer to not have the submission actually archived, but simply display a different submission status to the author.  This removes the previous fix to archive without sending, but also lets the _DECLINE decision fall through and return a _REVIEW status for the author instead.

revert archive send commit, adjust author submission status check

---

plugins/importexport/crossref/CrossrefInfoSender.inc.php

Resolves https://github.com/pkp/pkp-lib/issues/1585

pkp/pkp-lib#1585: Check if an article can be exported before attempting CrossRef update/registration.

---

plugins/generic/pln/locale/en_US/locale.xml

Adjust wording for the preamble to the terms of use for the plugin.

---

plugins/generic/thesis/locale/en_US/locale.xml

'seperate' should be 'separate'

Fix typo in thesis abstracts plugin

---

plugins/generic/pln/PLNGatewayPlugin.inc.php

It is never available if it isn't included or required. Strangely, some journals report it as available even if it isn't included. Perhaps it's a PHP caching issue, or another plugin that requires it somewhere.

pkp/pkp-lib#1517 include() Archive/Tar before checking if Archive/Tar is available.

---

plugins/generic/pln/classes/DepositPackage.inc.php

The PLN staging server was tossing HTTP 500 errors for deposit XML that contained HTML entities like `&copy;` (which isn't well-formed XML anyway, so it's probably the right thing to do, although maybe it should be HTTP 400 since it isn't an internal error but a bad request).
This patch encodes all the metadata fields which might have entities as UTF-8, and also filters out an invalid UTF-8 sequences at the same time. 
Fixes pkp/lib-pkp#1607

convert html entities to UTF-8

---

locale/en_US/default.xml

Is "AcqE" an abbreviation for "Guest Editor"? "GE" sounds better for us.

Wrong abbreviation?

---

plugins/blocks/navigation/block.tpl
templates/about/index.tpl

Recently, we have been applying complex CSS to an OJS about page. As most `li` items did not have ids, it was necessary to use pseudo classes such as nth-child. This resulted in very complex and fragile css, which was not working well in all browsers.
The attached commit contains those changes which allow for much easier and human-readable css files to be used for OJS themes. We have more of this kind of changes, but we'd like to see first whether you are interested in reusing it.
Also, this commit allows to style the searchField select field's label separately from the field, which was not possible on all browsers (as the select box was part of the label, styles or visibility settings were applied to both with no reliable way of limiting it only to the label wording).

Easier CSS application without pseudo classes

---

templates/controllers/grid/pubIds/form/assignPublicIdentifiersForm.tpl

@bozana Can your code review this small change to the DOI presentation template? Just something I noticed when scheduling an article for publication.

Don't add empty divs if no doi confirmation text is present

---

plugins/importexport/crossref/locale/pt_BR/locale.xml
plugins/importexport/crossref/locale/pt_PT/locale.xml
plugins/importexport/datacite/locale/pt_BR/common.xml
plugins/importexport/datacite/locale/pt_PT/common.xml

OJS 2.4.8-1 introduced some big changes on the crossref plugin strings and it looks like no translation were made at all, OJS should warns about this because it is seriously breaking the usability of 2.4.8-1 to every journal editor that doesn't uses en_US.
I made a patch that updates the translation for pt_BR and pt_PT.
@mtub Can you have a look at this?
Thanks!

[crossref] Update pt-br and pt-pt translation

---

tools/mergeUsers.php

The script 'mergeUsers.php' was relying on a removed function from pkp-lib (pkp/pkp-lib@3c09b12)
and its description was implying a limitation to OJS v2.

Resurrect the OJS CLI tool for merging users

---

plugins/importexport/crossref/CrossRefExportPlugin.inc.php

Well, my test submission still failed, but I think this fixes the status query, at least.

pkp/pkp-lib#1910: use Crossref test API for status checks when appropriate

---

plugins/citationFormats/endNote/citation.tpl

Addresses the issue pkp/pkp-lib#1966 of correcting and cleaning up EndNote citation export. This has been tested on our journal (haujournal.org), and user confirmed it works for them on EndNote. However, someone else may want to confirm the exporting of page numbers works properly for other journal setups.

pkp/pkp-lib#1966 Update EndNote citation format

---

plugins/generic/acron/AcronPlugin.inc.php

Comes closer to resolving pkp/pkp-lib#1905 by giving the semaphore only one method's worth of execution time to be out of sync.  It is still possible to have a duplicate run, but it needs to be outside of the same second (or on a database which doesn't support the "affected rows" query) and must have both processes executing somewhere between the new `$this->_getTasksToRun()` call and the `$taskDao->updateLastRunTime($className, time())` simultaneously.

pkp/pkp-lib#1905: Add check in acron to (re)validate scheduled task immediately before run

---

plugins/generic/acron/AcronPlugin.inc.php

s.  https://github.com/pkp/pkp-lib/issues/1905
This is a cherry-pick to ojs-stable-2_4_8

pkp/pkp-lib#1905 A more reliable semaphore for Acron Plugin 

---

plugins/citationFormats/bibtex/citation.tpl

Added a comma delimiting pages from doi. JabRef and other managers reported import problems without this comma.

Add missing comma to `pages` in bibtex citation

---

plugins/importexport/datacite/classes/DOIExportPlugin.inc.php

pkp/pkp-lib#2068: Change DOIExportPlugin assertion to !isempty() instead of passing "register" value directly.

---

plugins/importexport/crossref/filter/ArticleCrossrefXmlFilter.inc.php
plugins/importexport/crossref/filter/IssueCrossrefXmlFilter.inc.php
plugins/importexport/datacite/filter/DataciteXmlFilter.inc.php
plugins/importexport/doaj/filter/DOAJXmlFilter.inc.php
plugins/importexport/medra/filter/ArticleMedraXmlFilter.inc.php
plugins/importexport/medra/filter/IssueMedraXmlFilter.inc.php
plugins/importexport/medra/filter/O4DOIXmlFilter.inc.php
plugins/importexport/native/filter/ArticleNativeXmlFilter.inc.php
plugins/importexport/native/filter/ArtworkFileNativeXmlFilter.inc.php
plugins/importexport/native/filter/IssueGalleyNativeXmlFilter.inc.php
plugins/importexport/native/filter/IssueNativeXmlFilter.inc.php
plugins/importexport/native/filter/NativeFilterHelper.inc.php
plugins/importexport/native/filter/SupplementaryFileNativeXmlFilter.inc.php

Specifically, for XML contexts with user-sourced data to escape the data.
Our XML output is UTF-8 regardless of the selected locale, correct?
This is essentially a find-and-replace change and requires vetting.  I have not tested the changes against a live dataset.

pkp/pkp-lib#2074: Update use of createElement and createElementNS escaping

---

plugins/citationFormats/refWorks/citation.tpl

My log was clogging up with smarty errors from the RefWorks citation plugin. Only real change was on line 31, the rest was just indentation to be able to locate the error.

Fix error in RefWorks export (misplaced {if})

---

plugins/importexport/crossref/filter/ArticleCrossrefXmlFilter.inc.php
plugins/importexport/crossref/filter/IssueCrossrefXmlFilter.inc.php

I forgot to remove htmlspecialchars for URLs after using the "escape" parameter for the request URL function, so that URLs are escaped double and thus incorrect :-(

pkp/pkp-lib#2074 remove double escape for Crossref URLs

---

docs/README
docs/UPGRADE

Update README to note the GeoLiteCity database option.  Update UPGRADE to clarify the Full Package install process.
Resolves pkp/pkp-lib#2156 for stable 3.x

pkp/pkp-lib#2156: install/upgrade doc cleanup

---

docs/README
docs/UPGRADE

Update README to note the GeoLiteCity database option.  Update UPGRADE to clarify the Full Package install process.
Resolves pkp/pkp-lib#2156 for stable 2.4.8

pkp/pkp-lib#2156: cleanup install/upgrade docs

---

classes/article/Article.inc.php
plugins/citationFormats/endNote/citation.tpl
plugins/importexport/medra/filter/ArticleMedraXmlFilter.inc.php

Resolves pkp/pkp-lib#2076.
Deprecates `Article::getStartPage()` and `Article::getEndPage()` which were introduced for loose page counting.
Depends on https://github.com/pkp/pkp-lib/issues/2196

Replace page counting with ranges

---

registry/locales.xml

Following the completion of pkp/pkp-lib#1906, we can add the already completed Arabic translation to the registry.
Thanks, @vormia, for the translation, and @NateWr for the RTL support.

add ar_IQ locale to OJS registry

---

classes/article/Article.inc.php
plugins/citationFormats/bibtex/citation.tpl
plugins/importexport/doaj/filter/DOAJXmlFilter.inc.php
plugins/importexport/pubmed/PubMedExportDom.inc.php

Remove faulty Article::getStartingPage() and Article::getEndingPage() in favor of implementations in Submission.  Allow bibtext citation to use page ranges.
Depends on pkp/pkp-lib#2207; Jointly resolves pkp/pkp-lib#2075.

pkp/pkp-lib#2075: Cleanup first and last page parsing

---

plugins/generic/htmlArticleGalley/HtmlArticleGalleyPlugin.inc.php
plugins/generic/usageEvent/UsageEventPlugin.inc.php

HtmlArticleGalleyPlugin uses ArticleHandler::download hook and eventually blocks it for others, so it should create a new one, that can be then used by others.

pkp/pkp-lib#2134 add article download hook in HTMLArticleGalleyPlugin

---

locale/pt_PT/locale.xml

Add several key / values to pt-pt locale.xml file, which didn't displayed correctly.	
modified:   locale/pt_PT/locale.xml

type: localization - Add missing strings to pt-pt translation.

---

classes/install/Upgrade.inc.php
dbscripts/xml/upgrade/3.0.0_preupdate_commentsToEditor.xml

s. https://github.com/pkp/pkp-lib/issues/1873
This PR considers the situation when no author is assigned to a submission with a comment for the editors -- which is possible in OJS 3.x -- in that situation the first JM found will be used.

pkp/pkp-lib#1873 comments_to_ed migration if no author is assigned

---

classes/plugins/PubObjectsExportPlugin.inc.php
locale/en_US/manager.xml
plugins/importexport/crossref/CrossRefExportPlugin.inc.php
plugins/importexport/crossref/templates/index.tpl
plugins/importexport/datacite/DataciteExportPlugin.inc.php
plugins/importexport/datacite/filter/DataciteXmlFilter.inc.php
plugins/importexport/datacite/templates/index.tpl
plugins/importexport/doaj/DOAJExportPlugin.inc.php
plugins/importexport/doaj/templates/index.tpl
plugins/importexport/medra/filter/IssueMedraXmlFilter.inc.php
plugins/importexport/medra/templates/index.tpl

s. https://github.com/pkp/pkp-lib/issues/1955
this PR introduces the option not to validate XML when exporting... 
The native exports are not considered -- they have local schema and they are good to be validated in any case.
Also CLI exports are not considered for now, because it would mean change of the usage parameters and thus locales files.

pkp/pkp-lib#1955 no XML validation option for the export plugins

---

classes/install/Upgrade.inc.php
dbscripts/xml/upgrade/3.0.0_reviewer_files.xml

considers that reviewer files could have revisions and that it could happen that there is no such reviewer file with ID = reviewer_file_id in the submission_files table

pkp/pkp-lib#2173 (2) consider revision for reviewer files

---

classes/install/Upgrade.inc.php
dbscripts/xml/upgrade/3.0.0_reviewer_files.xml

considers that reviewer files could have revisions and that it could happen that there is no such reviewer file with ID = reviewer_file_id in the submission_files table

pkp/pkp-lib#2173 (2) consider revision for reviewer files migration

---

plugins/citationFormats/bibtex/citation.tpl

Some line breaks were missing, and some lines were included as blanks when fields were missing.

Fix line-breaks in bibtex citation template

---

classes/submission/sectionEditor/SectionEditorSubmissionDAO.inc.php

pkp/pkp-lib#1979: Remove unused tables from WHERE clause of SectionEditorSubmissionDAO::getReviewersForArticle().

---

templates/controllers/grid/articleGalleys/form/articleGalleyForm.tpl

HI @asmecher 
Based on you suggestion here http://forum.pkp.sfu.ca/t/artwork-files-for-xml-galleys/29587 I made a pr concerning the artwork files XML galleys. Allowing these is crucial for the implementation of XML workflows.
However, I started to think that should the `templates/controllers/grid/articleGalleys/form/articleGalleyForm.tpl` actually check for file type at all? I mean, why not allow artwork files for ANY galley? I realize that many usual galleys do not need or support separate artwork (like pdf), but still.
I am also preparing support for the XML artwork files both in my embedGalley plugin and the lensGalley plugin. However, I noticed that you have decided to stick with the old version of lens because it is missing support for mobile layouts. I have, however, used the latest …

Allow artwork files for XML galleys

---

templates/frontend/objects/article_summary.tpl

@asmecher, an addition to: https://github.com/pkp/ojs/pull/1345
The original pr changed only the url for the cover image, the title link was unaffected. oops.

Fix article title link in article_summary.tpl

---

plugins/citationFormats/endNote/citation.tpl

*Le sigh*, not happy with this one.

pkp/pkp-lib#2496: Ensure newline between %P and %V in EndNote Citation format plugin

---

locale/en_US/manager.xml
plugins/importexport/native/NativeImportExportPlugin.inc.php

Ensure NativeImportExportPlugin only checks file permissions as needed for import and export from the CLI; add support for NativeXMLSumbissionFileFilter filehandling via lib/pkp update.
Resolves pkp/pkp-lib#2500 for OJS.

pkp/pkp-lib#2500: Correct filehandling for Native Import/Export

---

plugins/importexport/native/filter/NativeXmlArticleFilter.inc.php
plugins/importexport/native/locale/en_US/locale.xml

Resolves a part of pkp/pkp-lib#2516.
Raises an error if the import has a `<issue>` element which contains `<article>` elements which do not have a `date_published` attribute.  Articles cannot be added to an issue without a published date.

pkp/pkp-lib#2516: Flag an error in Native Import if article has no date_published, but is a member of an issue

---

plugins/importexport/doaj/DOAJExportPlugin.inc.php

Hi @bozana 
If a journal is SSL the DOAJ API returns 301 error when trying to export articles. This can be fixed by chancing the API address to https.
However, I do not know whether you want to use `//doaj.org/api/v1/` instead? @asmecher? But if so, note that most of the export plugins define the API protocoll at the moment.

Change DOAJ API protocol to https

---

templates/sectionEditor/submissionEventLogEntry.tpl

Resolves pkp/pkp-lib#2547; should be cherry-picked to stable 2.4.8.

pkp/pkp-lib#2547: translate event log message in event details page

---

pages/article/ArticleHandler.inc.php

@asmecher, there is an extra print_r command left probably from debugging which is causing headers already sent errors.

Remove unnecessary print_r from ArticleHander

---

plugins/importexport/doaj/filter/DOAJJsonFilter.inc.php

Hi @bozana 
While working with this https://github.com/pkp/pkp-lib/issues/2543, I noticed that the journal article url's depend on the journal that triggers the export. The pr fixes that, but does not solve the issue linked.

Fix DOAJ export article URL's when using Acron

---

plugins/importexport/native/NativeImportExportDeployment.inc.php
plugins/importexport/native/NativeImportExportPlugin.inc.php
plugins/importexport/native/filter/NativeXmlArticleFilter.inc.php
plugins/importexport/native/filter/NativeXmlIssueFilter.inc.php
plugins/importexport/native/locale/en_US/locale.xml

This pull resolves pkp/pkp-lib#2462 by checking if a matching issue_identification is found before creating a brand new issue.
Some problems with this:
* The entire import process is far too dependent on reporting errors based on imported object id; IMHO this should be based on the XML input (node lineage? line/char?).  Here I've just reported the raw XML.
* There is an unfortunate dependency throughout the import process on the magic of the `$deployment`'s shared variables for context, issue, submission, etc.  I'm unhappy with the `$addProcessedObject` parameter in `setIssue()` as a workaround for this.
* Reusing an existing issue based on issue_identification means that the issue will be updated, with no path to rollback possible in the event of error!

Prevent duplicate load of issue in Native Import with identical issue identification

---

locale/en_US/default.xml
locale/en_US/editor.xml

Hi, just to suggest two corrections (whitespace and duplicate line) found during the work with the Swedish translation.

Small corrections in en_US strings

---

classes/issue/IssueDAO.inc.php

Resolves pkp/pkp-lib#2663.
An alternate strategy could be to continue to wrap every call to `IssueDAO::resequenceCustomIssueOrders()` with a check, but that seems unnecessary.
Also considered was adding `i.date_published DESC` to the `$this->retrieve()` of 670 so that even if called it would at least order them correctly, but this also seems unnecessary.

pkp/pkp-lib#2663: Prevent IssueDAO::resequenceCustomIssueOrders() from creating a new arbitrary ordering where none existed

---

templates/submission/form/step1.tpl

OJS 2.4 automatically selects the section of a submission if there is a single journal section defined. This pull request replicate this behaviour with OJS 3.

Restore automatic selection of the section when submitting an article

---

templates/admin/index.tpl

There is a broken HTML on admin/index page. The confirm text needs to be escaped because there are double quotes returned from json_encode.

Escaping text in confirm on index/admin page

---

plugins/generic/dublinCoreMeta/DublinCoreMetaPlugin.inc.php
plugins/generic/googleScholar/GoogleScholarPlugin.inc.php
plugins/pubIds/doi/locale/ar_IQ/locale.xml
plugins/pubIds/doi/locale/cs_CZ/locale.xml
plugins/pubIds/doi/locale/da_DK/locale.xml
plugins/pubIds/doi/locale/de_DE/locale.xml
plugins/pubIds/doi/locale/en_US/locale.xml
plugins/pubIds/doi/locale/fi_FI/locale.xml
plugins/pubIds/doi/locale/fr_CA/locale.xml
plugins/pubIds/doi/locale/id_ID/locale.xml
plugins/pubIds/doi/locale/it_IT/locale.xml
plugins/pubIds/doi/locale/nl_NL/locale.xml
plugins/pubIds/doi/locale/pt_BR/locale.xml
plugins/pubIds/doi/locale/pt_PT/locale.xml
plugins/pubIds/doi/locale/ru_RU/locale.xml
plugins/pubIds/doi/locale/sr_RS@latin/locale.xml
plugins/pubIds/doi/locale/tr_TR/locale.xml
plugins/pubIds/doi/locale/uk_UA/locale.xml
plugins/themes/default/styles/objects/article_details.less
templates/frontend/objects/article_details.tpl

s. https://github.com/pkp/pkp-lib/issues/1828

pkp/pkp-lib#1828 consider keywords for display, DC and GoogleScholar indexing

---

tools/xmllint-exclusions.txt

Fixes issues with the tests running Guzzle tests and linting Guzzle XML files.

Exclude paypal plugin vendor dir from XML linting

---

classes/notification/NotificationManager.inc.php

Instead of testing the role of the recipient of the email, it was testing the role of the current user.
This resulted in a bad URL in the emails received by editors : for example `https://.../index.php/JOURNAL/reviewer/submissionReview/123#peerReview` in a notification email for an uploaded review file.

Fix the construction of the url in notification emails for editors.

---

classes/controllers/grid/issues/IssueGridHandler.inc.php
templates/controllers/grid/pubIds/form/assignPublicIdentifiersForm.tpl

Fix second issue in https://github.com/pkp/pkp-lib/issues/2561
Using the assignPublicIdentifiersForm.tpl is maybe a bit hacky, but it is used there even if no pubid's are being assigned.

Make new issue notifications optional

---

tools/buildpkg.sh

@asmecher This should fix the `buildpkg.sh`. Forgot to run `npm install` before building the JS. I've also excluded the `node_modules` directory from the package files.
When I compile, I get an error that `composer.phar` is not found. I usually just run `composer`. Any idea how I can get it so the `composer.phar` file itself can be run globally?

Install node dependencies in package build script

---

templates/article/article.tpl

Consider Harvard and ABNT citation styles as examples of why `strip_unsafe_html` should not be used.

pkp/pkp-lib#2570: Escape display of references rather than striping HTML-like tags.

---

classes/user/UserAction.inc.php

While attempting to merge two users, an error has occured because it tries to
invoke the "next()" method on an array. In this commit we suggest a possible fix
by invoking the next php array function, passing the array as argument.

pkp/pkp-lib#2954 Possible error on line 113 of UserAction.inc.php

---

tests/functional/plugins/importexport/medra/FunctionalMedraExportTestCase.php
tests/functional/plugins/pubIds/FunctionalDoiPubIdPluginTestCase.php

Resolves pkp/pkp-lib#3054 for OJS 2.4.x.

pkp/pkp-lib#1118, pkp/pkp-lib#3054: Catchup update on some String:: to PKPString:: test outliers

---

plugins/oaiMetadataFormats/marc/record.tpl

Replace instances of marcxml tags/attributes with oai_marc tags/attributes.  (ojs-dev-2_4)
See: pkp/pkp-lib#3062

Fix oai_marc template for schema compliance in dev-2_4

---

plugins/themes/default/locale/es_ES/locale.xml

Hi @mtub ,
As well as in "lib-pkp" also for "ojs"... a few chains still missing, but sending you what I made till now just in case I ran out of time.
Cheers,
m.

Missing 3.1.0 core chains in es_ES translations

---

locale/de_DE/emailTemplates.xml

All translations were provided by Bettina Kaldenberg.

Add missing German e-mail templates and update existing ones

---

classes/services/SubmissionService.inc.php

Back-porting fix to `ojs-stable-3_1_0`

pkp/pkp-lib#3070 Prevent author name from being exposed

---

pages/management/ToolsHandler.inc.php

Hi @asmecher 
At the moment if you output statistics that have issue information, the report generator will either show the issue title or just the id. This does not tell a lot for the editors.
Instead, getIssueIdentification should be used.

Instead of issue title, show issue identification in statistics output

---

templates/payments/subscriptionPolicyForm.tpl

@asmecher, the pull down menu for setting the embargo length for a journal was broken due to a small typo. https://forum.pkp.sfu.ca/t/some-problems-with-subscriptions-after-upgrade-to-3-1-0-1/37347

Fix delayedOpenAccessDuration settings pull down

---

pages/index/IndexHandler.inc.php

pkp/pkp-lib#2291: Add pageTitleTranslated to site index to display site title instead of default key

---

plugins/blocks/user/block.tpl

Resolves pkp/pkp-lib#2683.
Like the username, the password field should never be pre-populated in the block.

pkp/pkp-lib#2683: remove password value from user block

---

classes/services/SectionService.inc.php

The parameter should be @$section@ and not @$ection@ in @getSummaryProperties@.

Fixed parameter names in getSummaryProperties

---

classes/comment/form/CommentForm.inc.php
classes/user/form/RegistrationForm.inc.php

Cleans up usage of magic numbers for ReCAPTCHA, including the incorrect use of a ReCAPTCHA version of "1".
Resolves pkp/pkp-lib#3425

pkp/pkp-lib#3425: Fix ReCAPTCHA, correct magic numbers

---

templates/frontend/objects/article_details.tpl

The hook can then be used for Crossref reference linking or Google Scholar reference lookup

provide a hook for a parsed reference

---

plugins/themes/default/styles/pages/indexSite.less

Default theme did not consider links in journal description, but introduced a line break after the link. I think that this is an easy fix, but please correct me if I'm wrong.

Removing display:block on links in journal description (index) in default theme

---

controllers/tab/settings/permissions/form/OJSPermissionSettingsForm.inc.php
templates/controllers/tab/settings/permissions/form/permissionSettingsForm.tpl

Self archiving settings are at the moment under Payment settings, which does not make sense, because self archiving policies are not connected to subscription settings.
So, move settings concerning self archiving under settings=>distribution=>permissions

Move self archiving settings under distribution->permissions

---

plugins/blocks/subscription/locale/ca_ES/locale.xml
plugins/blocks/subscription/locale/cs_CZ/locale.xml
plugins/blocks/subscription/locale/el_GR/locale.xml
plugins/blocks/subscription/locale/es_AR/locale.xml
plugins/blocks/subscription/locale/es_ES/locale.xml
plugins/blocks/subscription/locale/eu_ES/locale.xml
plugins/blocks/subscription/locale/fr_CA/locale.xml
plugins/blocks/subscription/locale/fr_FR/locale.xml
plugins/blocks/subscription/locale/hr_HR/locale.xml
plugins/blocks/subscription/locale/id_ID/locale.xml
plugins/blocks/subscription/locale/it_IT/locale.xml
plugins/blocks/subscription/locale/ja_JP/locale.xml
plugins/blocks/subscription/locale/nl_NL/locale.xml
plugins/blocks/subscription/locale/no_NO/locale.xml
plugins/blocks/subscription/locale/pl_PL/locale.xml
plugins/blocks/subscription/locale/pt_BR/locale.xml
plugins/blocks/subscription/locale/ro_RO/locale.xml
plugins/blocks/subscription/locale/sr_RS@latin/locale.xml
plugins/blocks/subscription/locale/sv_SE/locale.xml
plugins/blocks/subscription/locale/tr_TR/locale.xml
plugins/blocks/subscription/locale/uk_UA/locale.xml
plugins/blocks/subscription/locale/vi_VN/locale.xml
plugins/blocks/subscription/locale/zh_CN/locale.xml

Noticed these were missing in our French and Spanish language journals, and thought it may be helpful to include them in all missing locale files as well.

Include institution name and IP range variables in subscription locales

---

locale/es_ES/emailTemplates.xml

In one update of Spanish translation this string were added (by mistake I think) after @asmecher remove it in this commits:
https://github.com/pkp/ojs/commit/0944a1b891358f3d669b8f77e5d0d7209ab3e93b#diff-91ce7dfd65a040e9e17689f6b0c4a880 
https://github.com/pkp/ojs/commit/6ab3e10254eee426fc33a3e5bb852ff76cb6bdcb#diff-91ce7dfd65a040e9e17689f6b0c4a880

Clean up zombie translations and gifts codes again

---

controllers/grid/subscriptions/IndividualSubscriptionsGridHandler.inc.php
controllers/grid/subscriptions/InstitutionalSubscriptionsGridHandler.inc.php
controllers/grid/subscriptions/SubscriptionsGridCellProvider.inc.php

This is a response to a long standing issue we've had which @neffe first brought up here:
https://forum.pkp.sfu.ca/t/show-reference-numbers-on-the-summary-page/13794

pkp/pkp-lib#3794 Add Reference Number column to subscription overview

---

templates/payments/institutionalSubscriptionForm.tpl

This adds the Reference Number field to the Institutional subscription form to have parity with Individual subscriptions and to correct a regression from OJS 2.
This should take care of https://forum.pkp.sfu.ca/t/no-reference-number-in-the-subscription-settings-in-ojs-3/41261

pkp/pkp-lib#3795 Link up reference_number field to institutional subscription form

---

plugins/blocks/subscription/locale/de_DE/locale.xml
plugins/reports/counter/locale/de_DE/locale.xml

The [main locale](https://github.com/pkp/ojs/blob/master/locale/de_DE/locale.xml) of ojs translates `plugin` as `Plugin` not as `Plug-In`.

Harmonize de_DE locale with the ojs locale

---

classes/install/Upgrade.inc.php
dbscripts/xml/upgrade.xml
dbscripts/xml/upgrade/3.0.0_update.xml

I noticed that there where hundreds of no_NO references still in the database after a test upgrade from 2.4.8.1 to 3.1.1-1.
This patch series attempts to fix this by using the code from pkp/pkp-lib#3416 to do a more complete migration.
In my testing this has converted all traces of no_NO to nb_NO as expected.

Proper migration of no_NO to nb_NO

---

dbscripts/xml/upgrade.xml
dbscripts/xml/upgrade/event_log_submissionid.xml

With OJS 2.4, the `log.author.submitted` events of submissions prior to 642fa8543782c3df69e2e0f77d08d6d43bbe753d are missing the `submissionId` param.

 Fix missing submission id event log parameters

---

controllers/grid/articleGalleys/ArticleGalleyGridCellProvider.inc.php

Fixes part of pkp/pkp-lib#3578; may break some plugins.

pkp/pkp-lib#3578: harmonizing GridCellProvider::getCellActions() signatures

---

plugins/generic/externalFeed/ExternalFeedBlockPlugin.inc.php
plugins/generic/lucene/LuceneFacetsBlockPlugin.inc.php

Fixes some of pkp/pkp-lib#3578. Some other specific plugins still have problems in `getContents()`, `getEnabled()`, and `register()`.

pkp/pkp-lib#3578: harmonizing Plugin signatures

---

plugins/generic/piwik/PiwikSettingsForm.inc.php

pkp/pkp-lib#4167: Allow arbitrary URL for piwik, not just http protocol

---

locale/es_ES/emailTemplates.xml

This RP is for reordering email templates according to the English version   (derived from https://github.com/pkp/ojs/pull/2119)
Lines 127 and 141 are both "SUBMISSION_ACK" (repeated)
this is the first step, @marcbria if you say me what of the options is the best I can edit the PR and delete one of them or make a new one like a fusion between both.
Something like this:
Gracias por enviarnos su manuscrito &quot;{$submissionTitle}&quot; a {$contextName}. Gracias al sistema de gestión de publicaciones en línea que utilizamos podrá seguir su progreso a través del proceso editorial, iniciando sesión en el sitio web de la revista:
Si tiene cualquier pregunta no dude en contactar con nosotros/as. Gracias por considerar esta revista para publicar su trabajo.
I thought it would be easier to detect …

reordering emailTemplate (new)

---

plugins/importexport/doaj/classes/DOAJExportDom.inc.php

For OJS 2.4.x; should cherry pick cleanly against ojs-stable-2_4_8

pkp/pkp-lib#4236: Remove export of author email within DOAJ

---

plugins/metadata/dc11/filter/Dc11SchemaArticleAdapter.inc.php

s. https://github.com/pkp/pkp-lib/issues/4242
This provides all the "subjects" via OAI in the same way it was in OJS 2. 
Shall maybe each "subject" be listed in its own dc element?

pkp/pkp-lib#4242 provide subjects via OAI

---

plugins/importexport/crossref/CrossrefInfoSender.inc.php

s. https://github.com/pkp/pkp-lib/issues/4350
this is a cherry-pick of https://github.com/pkp/ojs/pull/2231

pkp/pkp-lib#4350: Capture current Crossref deposit status before update.

---

classes/article/PublishedArticleDAO.inc.php

The exclusion of archived articles in the Published Articles DAO should probably be in all `get` methods, but this one in particular because of pkp/pkp-lib#4366.

pkp/pkp-lib#4366: Exclude archived Published Articles when fetching by setting.

---

plugins/importexport/crossref/CrossRefExportPlugin.inc.php
plugins/importexport/datacite/classes/DOIExportPlugin.inc.php

This change prevents the Crossref Export plugin from trying to register archived articles.  pkp/pkp-lib#4366

pkp/pkp-lib#4366: Check article publication status in DOI/Crossref Export plugins

---

plugins/generic/googleScholar/GoogleScholarPlugin.inc.php

Show unstructured citation_reference metatags with GoogleScholar Plugin. Also add a hook that allows other plugins dealing with references to add structured references if needed.
https://github.com/pkp/pkp-lib/issues/4619

Add citation_reference tags to GoogleSchorlaPlugin output

---

plugins/generic/htmlArticleGalley/HtmlArticleGalleyPlugin.inc.php

Implementation for the default CSS for HTML galleys (ojs-stable-3_1_1) alongside with corresponent commit to pkp-lib

pkp/pkp-lib#3691 default CSS for HTML galleys for stable-3.1.1

---

classes/manager/form/setup/JournalSetupStep5Form.inc.php

Hello
I'm running OJS 2.4.8-4 on Ubuntu 16.04, with PHP 7.0, and noticed that there is a call to split() in the code for step 5 of the setup page. It causes any changes to the existing configuration on that page to fail with a fatal error.
This change replaces the call to split() with a call to explode().

Replace call to deprecated split() function with explode() for PHP 7

---

controllers/grid/articleGalleys/ArticleGalleyGridHandler.inc.php

If I delete Galley file from Submission, it now get's deleted from search index. But I am not sure if this is the best position to inform the searchindexer that a file has been deleted. Maybe from within ArticleGalleyDAO->deleteObject?

#4666: Deleting galley does not remove it from search index

---

tools/rebuildSearchIndex.php

We are getting a PHP warning (PHP Warning:  Parameter 2 to rebuildSearchIndex::callbackBaseUrl() expected to be a reference, value given in/lib/pkp/classes/plugins/HookRegistry.inc.php on line 107
) when runing rebuildSearchIndex therefor I have removed the reference in the call to callbackBaseUrl  in tools/rebuildSearchIndex.php

Remove reference in call to callbackBaseUrl to avoid warning

---

templates/frontend/pages/search.tpl

@asmecher 
Hi Alec,
In order to be able to show Spellingsuggestion and  Additional Filters from facets, I added two call_hooks to search.tpl. Would be great if they could be added to OJS 3.1.2-1 release, so the Lucene Plugin could function from that release on when it gets released.

Added call_hooks for AdditionalFilters and PreResults

---

classes/manager/form/UserManagementForm.inc.php

Hello,
We are running OJS 2.4.8 on PHP7.2. When I go to either institutional or individual subscriptions and attempt to "create new user" (Subscription Manager > individual subscriptions OR institutional subscriptions > create new subscription > create new user), I get a Fatal error:
```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function UserManagementForm::initData(), 0 passed in /var/www/ojs/pages/subscriptionManager/SubscriptionManagerHandler.inc.php on line 368 and exactly 2 expected in /var/www/ojs/classes/manager/form/UserManagementForm.inc.php:141 Stack trace: #0 /var/www/ojs/pages/subscriptionManager/SubscriptionManagerHandler.inc.php(368): UserManagementForm->initData() #1 /var/www/ojs/lib/pkp/classes/core/PKPRouter.inc.php(362): …
```

Remove unused arguments from initData()

---

classes/subscription/form/UserInstitutionalSubscriptionForm.inc.php

This fix uses the form validator from the back end institution form, and correctly splits up the ip range that is passed in from the form submission.

pkp/pkp-lib#4788 fix Institutional form validation issues

---

templates/frontend/pages/search.tpl

Added block for SearchSyntaxInstructions

#4800: Allow Lucene Plugin to add Syntax-Instructions to search page

---

plugins/generic/dublinCoreMeta/DublinCoreMetaPlugin.inc.php
plugins/importexport/medra/filter/ArticleMedraXmlFilter.inc.php
plugins/metadata/dc11/filter/Dc11SchemaArticleAdapter.inc.php

Use full titles (including subtitles) for the following metadata extracts:
- DC.Title (DC meta tag plugin)
- Dublin Core title (OAI)
- DataCite/CrossRef

pkp/pkp-lib#4021 Use full titles in DC.Title (meta), Title (OAI DC), and title (DataCite/CrossRef) formats

---

templates/gateway/lockss.tpl

The verbiage in the LOCKSS permission template for non-CLOCKSS applications was copied from the template for CLOCKSS applications, with "CLOCKSS" replaced by "LOCKSS", resulting in invalid LOCKSS manifest pages (which do not grant permission to crawl).
We are submitting this pull request on the master branch; should we also submit one to other branches for bugfix releases?

Corrected invalid LOCKSS permission statement for non-CLOCKSS applications

---

plugins/generic/webFeed/templates/rss2.tpl

This addresses strict validation for RSS2: 
* RDF namespace was missing. (pkp/pkp-lib#3948)
* RSS `author` element should be an email or emails; `dc:creator` can be used for names; both should not be used together.

pkp/pkp-lib#3948: Ensure RSS2 validates with RDF namespace and author/creator distinction

---

templates/frontend/components/searchForm_simple.tpl
templates/frontend/pages/search.tpl

Resolves pkp/pkp-lib#2294 for the default theme, while considering the increasingly unlikely case of https://github.com/pkp/pkp-lib/issues/2300.  Other themes may need to be updated.

pkp/pkp-lib#2294: Update frontend search to use GET instead of POST

---

locale/en_US/emailTemplates.xml

Description text for "REVIEW_REINSTATE" email message should exchange places with the description text for "REVIEW_CANCEL" email message.

Correcting two emails' descriptions

---

classes/workflow/EditorDecisionActionsManager.inc.php

The (currently half-complete) Review Quality Collector generic plugin needs to hook into this operation.

add hook EditorAction::modifyDecisionOptions needed for future RQC plugin

---

plugins/importexport/crossref/CrossRefExportPlugin.inc.php
plugins/importexport/crossref/CrossrefInfoSender.inc.php

pkp/pkp-lib#5264: Correct Crossref temporary filename construction

---

classes/core/Application.inc.php

The function `Application::getRoleNames()` introduced with https://github.com/pkp/ojs/commit/35cb328da2d84723a40168fc1b543c054bc08ec7 can erroneously return the subscription manager role key.
As a result a lot of the email templates on the 'Prepared Email Templates' grid of OJS 3.1.2 have the subscription manager role as sender or recipient (also see [this comment](https://github.com/pkp/pkp-lib/issues/2724#issuecomment-347220421)).
It also applies to `master` even after the role ids of template emails have been fixed with pkp/pkp-lib#2906.

Fix mapping of role ids to role i18n keys.

---

pages/management/SettingsHandler.inc.php

OMP and OJS do not have app specific workflow settings, but PPS will have one tab. This change allows apps to extend the workflow settings if needed.
Also see https://github.com/pkp/omp/pull/731

Allow applications to extend the workflow settings

---

locale/en_US/locale.po

From this issue "Address alt text / link location confusion in the OJS/OMP branding image on themes" (just the alt text for now): https://github.com/pkp/pkp-lib/issues/5180

i5180 Made alt text for footer more descriptive

---

templates/frontend/pages/indexJournal.tpl

L. 26 is wrong – »$homepageImage.altText« is the right variable.
And `<div>` was missing.

Homepage Image Alt Text Missing

---

locale/en_US/emails.po

use gender neutral language in email description

---

classes/controllers/grid/issues/IssueGridHandler.inc.php

so that it can be used downstream (such as in NotificationManager::getNotificationMessage)

pkp/pkp-lib#5953: Add issue ID to NOTIFICATION_TYPE_PUBLISHED_ISSUE

---

plugins/importexport/crossref/filter/ArticleCrossrefXmlFilter.inc.php

I'm having the same problem as in the forum https://forum.pkp.sfu.ca/t/error-cvc-complex-type-2-4-d/62239
This error occurs when the "author" metadata is populated with multiple languages
The position of the "ORCID" schema must be above the "alt-name" schema, this is according to the instructions at http://data.crossref.org/reports/help/schema_doc/4.4.2/schema_4_4_2.html#person_name
I have tested the change in my ojs, author metadata, filled without and with multilingual, xml validation for deposit to crossref was successful

Fixed xml validation errors

---

docs/README.md

Since Geolite legacy databases aren't available anymore, I added cnet.
More info: [GeoLite Legacy Discontinuation Information](https://support.maxmind.com/geolite-legacy-discontinuation-notice/)

doc: Fix broken links

---

classes/issue/IssueAction.inc.php
locale/en_US/submission.po
pages/article/ArticleHandler.inc.php
pages/workflow/WorkflowHandler.inc.php
templates/frontend/objects/article_details.tpl
templates/workflow/workflow.tpl

Allows submission preview starting from a copyediting stage according to the initial implementation by @majaroenne. Note that this is for the stable-3_2_1 branch.

[stable-3_2_1] pkp#pkp-lib#5565 Submission preview feature implementation

---

cypress/tests/integration/Subscriptions.spec.js

Now that 5408 is fixed, we don't need to reload the page to see the sidebar change (and "Payments" to appear).

pkp/pkp-lib#5408 Remove reload after fix of 5408

---

pages/issue/IssueHandler.inc.php

This PR aims to address https://github.com/pkp/pkp-lib/issues/6310 ("Omit author names for section items from issues' table of contents" is ignored). It also address the second part of https://github.com/pkp/pkp-lib/issues/5955 (OJS should support author-less publications) but not the wider issue of author-less publications.
I have tested it on OJS 3.2.1-1 and it produces the desired result, i.e. author names no longer appear in the issue table of contents for sections where "Omit author names for section items from issues' has been ticked.
A couple of things to note:
- The author names still display on the full article details page. I think this is the intended behaviour? It would be good to have an option to also hide author names on article detail pages based on the parent section. …

assign hideAuthor for sections in issue TOC

---

classes/controllers/grid/issues/IssueGridHandler.inc.php
classes/services/SubmissionService.inc.php
controllers/grid/toc/TocGridHandler.inc.php

These changes centralize all of the tombstone handling into the `SubmissionService::updateStatus()` method. This should always be the method to update a submission's status, as it checks all assigned publications to determine whether it is published, scheduled or queued.

pkp/pkp-lib#6625 Fix tombstones when issue is published/unpublished

---

docs/UPGRADE.md

This provides a reworking of https://github.com/pkp/ojs/#using-git-development-source for upgrades
that are Git-based, avoiding errors caused by mismatches in submodules that are out of date or missing Composer-sourced libraries.
This also tidies a few trailing spaces and makes commands present in the file consistent (no leading `$`, which had to be previously explained).

Add dependency update steps to UPGRADE docs

---

templates/frontend/pages/indexSite.tpl

Journal descriptions are edited as rich text, meaning that they contain HTML by default and with TinyMCE as the editor, content will be wrapped in at least `<p>` tags.  Prior to this change, the use of `|nl2br` added a `<br>` tag after every newline, resulting in extra markup/spacing as a description with multiple paragraphs has its `<p>` tags on separate lines:
```html
<p>...</p><br>
<p>...</p><br>
<p>...</p>
```
This change outputs the description verbatim on the page, without conversion.
Whilst this change manifests as extra spacing between `<p>` tags, it's particularly important because the original code can create invalid HTML: `<br>` elements are injected where they shouldn't be.  I've applied this PR in our production system but an example of the issue can be seen at …

Display journal descriptions on site index page without adding <br>

---

dbscripts/xml/upgrade.xml

At Administration > Site Settings > Information tab, the About field now it's a rich text area field.
Evidences are attached at pkp/pkp-lib#5844

pkp/pkp-lib#5844 Changing site-wide about field to rich textarea. And creating a a migration to handle cases when old data has html special characters

---

templates/frontend/pages/indexSite.tpl

Same as #3043; but stems from https://github.com/pkp/pkp-lib/issues/5844
'About this Site' is now edited as rich text, meaning it contains HTML by default and with TinyMCE as the editor, content will be wrapped in at least `<p>` tags.  Prior to this change, the use of `|nl2br` added a `<br>` tag after every newline, resulting in extra markup/spacing as a description with multiple paragraphs has its `<p>` tags on separate lines:
```html
<p>...</p><br>
<p>...</p><br>
<p>...</p>
```
This change outputs the About information verbatim on the page, without conversion.

Display site description without adding <br>

---

controllers/grid/toc/TocGridHandler.inc.php

I just applied a fast fix, as I believe the grid classes are going to be replaced later.

pkp/pkp-lib#6828 Fixed the section ordering when a new section is added later into an already sorted TOC.

---

docs/UPGRADE.md

Also change from master to main
https://forum.pkp.sfu.ca/t/ojs-build-js-is-not-present-in-the-stable-branches/70034/2

Remove mention of precompiled js for stable branches

---

classes/oai/ojs/OAIDAO.inc.php

In an OJS 3.3.0-7 from where a harvest server, harvest the metadata of published articles, the harvest server doesn’t identify the updated articles in OAI-PMH because the datestamp isn’t updated to the date the article was updated.
My proposal to solve it, is to modify in the file classes/oai/ojs/OAI DAO.inc.php, adding p.last modified on the querys. With this change, the OAI already shows the datestamp with the date of the last_modified field of the publications table and vufind already identifies it as an updated article to re-harvest it.
There are more information in: https://forum.pkp.sfu.ca/t/ojs-3-3-0-7-oai-doesnt-update-the-datestamp-to-the-date-of-the-last-update-to-allow-metadata-harvest/69677
Regards

Add p.last_modified to update the last datestamp.

---

plugins/oaiMetadataFormats/marcxml/templates/record.tpl

We realized in our team that the MARC-XML of the OAI-API did not return the article's DOI. Hence, here is the fix.
Also there were two wrongly named subfields that were fixed.
All kudos to @j4lib.

Adding DOI field to MarcXML OAI output

---

classes/migration/upgrade/v3_4_0/I7014_DoiMigration.inc.php

**Problem**
When upgrading from ojs version 3.3.0.7 to the current main branch 3.4, we ran across the following error when running `upgrade.php` :
>2022-03-02 11:04:32 [downgrade for "PKP\migration\upgrade\v3_4_0\I7167_RemoveDuplicatedUserSettingsAndDep recatedFields" unsupported: Downgrade unsupported due to removed data] ERROR: Upgrade failed: DB: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'publication_id' in where clause is ambiguous (SQL: select `s`.`context_id`, `p`.`publication_id`, `p`.`doi_id`, `pss`.`setting_name`, `pss`.`setting_value` from `submissions` as `s` left join `publications` as `p` on `p`.`subm ission_id` = `s`.`submission_id` left join `publication_settings` as `pss` on `pss`.`publication_id` = `p `.`publication_id` where `pss`.`setting_name` = …

Fix upgrade error in I17014_DoiMigration.inc.php

---

cypress/tests/data/20-CreateContext.spec.js

fix to issue https://github.com/pkp/pkp-lib/issues/2169 which make the `Mailing address` as a non required field in the `Settings => Contact` section for `main` branch. A corresponding pull request to `pkp/pkp-lib` repo `main` branch for this has made at https://github.com/pkp/pkp-lib/pull/7865 . Also tests are updated according to this change .

pkp/pkp-lib#2169 Submodule Update ##touhidurabir/i2169_fix_main##

---

plugins/reports/subscriptions/SubscriptionReportPlugin.inc.php

adds a test to ensure that a user has set their country, otherwise just include the blank field in the report.

pkp/pkp-lib#8086 test for user country before using Countries library

---

templates/frontend/objects/issue_toc.tpl

This PR removes the link on the issue cover image from the _index_ and _issue_ pages : https://github.com/pkp/pkp-lib/issues/5195

pkp/pkp-lib#5195 Remove current issue link from the cover image 

---

plugins/themes/default/styles/objects/article_details.less
plugins/themes/default/styles/objects/article_summary.less
plugins/themes/default/styles/objects/issue_toc.less

Fix the duplicated announcement of link galleys by screenreaders removing the extra space between closing / opening list item tags, i.e.: `</li><li>`. The required visual gap is fixed via CSS/LESS.

pkp/pkp-lib#5196 CSS Pseudo selectors creating a duplicated link announcement on screenreaders

---

api/v1/stats/editorial/StatsEditorialHandler.php
api/v1/stats/publications/StatsPublicationHandler.php
classes/services/StatsPublicationService.php
classes/services/queryBuilders/StatsGeoQueryBuilder.php
classes/services/queryBuilders/StatsPublicationQueryBuilder.php
pages/stats/StatsHandler.php

s. https://github.com/pkp/pkp-lib/issues/7318

issues filter for stats article page

---

docs/UPGRADE.md

The existing UPGRADE.md document misleadingly structures the dependency requirements outside of the git workflow, and has poorly interpreted markdown surrounding legacy word wrapping.  This addresses those issues, deferring the comprehensive review this document needs.

Clarify packge/git upgrade flow

---

classes/plugins/PubIdPlugin.inc.php
js/load.js
plugins/pubIds/urn/URNPubIdPlugin.inc.php
plugins/pubIds/urn/classes/form/FieldPubIdUrn.inc.php
plugins/pubIds/urn/classes/form/FieldTextUrn.inc.php
plugins/pubIds/urn/js/FieldPubIdUrn.js
plugins/pubIds/urn/js/FieldTextUrn.js

s. https://github.com/pkp/pkp-lib/issues/6293

pkp/pkp-lib#6293 consider urnCheckNo setting, fix checkDuplicate in PubIdPlugin 

---

config.TEMPLATE.inc.php

Very minor change: in the new **Job Queues Settings** section of `config.TEMPLATE.inc.php`, the URL to the documentation was throwing a 404. I substituted what I understand is the correct URL.

Changed URL for jobs documentation

---

controllers/grid/issues/form/IssueForm.php

I decided to call the Hook in the end with the `parent` call instead of previous `Hook::call('issueform::execute', [$this, $issue]);`.
This may broke some plugins that rely on that `$issue` as an argument. However, I didn´t find any plugin using that Hook on my installation. Besides, nobody noticed it before... But we may change it if you prefer.

#9449 Attach the issue properly when calling issueform::execute

---

plugins/themes/default/styles/variables.less

This PR fixes this issue: https://github.com/pkp/pkp-lib/issues/9504 (OJS3.3 branch)
It increases the contrast ratio for elements, including asterisk (*) on required fields to 
OJS3.4 and main branch don't use this color, for this reason, not porting will be made or required.
This changes will cover WCAG 2.1 AA and AAA:

Fix low contrast ratio on no/error/off/stop color  and the background color

---

classes/section/Section.php

s. https://github.com/pkp/pkp-lib/issues/9557

 pkp/pkp-lib#9557 Section::getAbbrev() and PKPSection::getTitle() can return null 

---

plugins/importexport/crossref/filter/ArticleCrossrefXmlFilter.inc.php

Adaptation of pkp/crossref-ojs#6 for OJS 3.3.
Utilizes getLocalizedTitle() to incorporate the article prefix into the title tag.

Crossref OJS 3.3: Include article prefix in title tag

---

classes/issue/IssueGalley.php
classes/migration/install/JournalsMigration.php
classes/migration/install/OJSMigration.php
classes/migration/upgrade/v3_5_0/I9425_SeparateUIAndSubmissionLocales.php
classes/publication/Repository.php
classes/publication/maps/Schema.php
classes/submission/Repository.php
classes/submission/maps/Schema.php
controllers/grid/articleGalleys/form/ArticleGalleyForm.php
cypress/tests/data/10-ApplicationSetup/20-CreateContext.cy.js
cypress/tests/data/60-content/AmwandengaSubmission.cy.js
cypress/tests/integration/SubmissionWizard.cy.js
dbscripts/xml/upgrade.xml
pages/submission/SubmissionHandler.php
pages/workflow/WorkflowHandler.php
schemas/galley.json

- In Website Settings > Setup > Languages and in Administration > Hosted Journals > Settings Wizard > Journal Settings > Languages, separate Website Languages and Submission Languages settings. In the website languages are UI and Forms, and in the submission languages are submission and metadata.
- Submission metadata can be edited even if metadata isn't checked in that language in the settings.

Submission and metadata languages separated from UI and form languages

---

SECURITY.md

- Adding EOL for 3.5.
- Adding Released column (based on Archive page).
- Adding Support explanations.

Fix EOL dates in SECURITY.md. Extend with release datte and explanations.

---

.github/workflows/stable-3_3_0.yml
cypress/tests/data/60-content/AmwandengaSubmission.spec.js

- https://github.com/pkp/ojs/pull/4323

Add github ations for OJS 3.3

---

plugins/oaiMetadataFormats/marc/templates/record.tpl

according to official documentation of the marc bibliographic manual by loc.gov  The journal title and volume  must to be in 773 fields with subfield "t" and "g".  the 786 field is use for other purposes . 
This is important for journals imports by tools like Vufind.

Update marc record.tpl (change 786 marc field by 773 and subfields)  

---

controllers/grid/submissions/ExportPublishedSubmissionsListGridCellProvider.php
plugins/generic/datacite/filter/DataciteXmlFilter.php

s. https://github.com/pkp/pkp-lib/issues/10135

pkp/pkp-lib#10135 consider existance of htmlspecialchars_decode for publication title in text format

---

classes/install/Upgrade.php
classes/migration/install/JournalsMigration.php
classes/migration/install/MetricsMigration.php
classes/migration/install/OJSMigration.php
classes/migration/upgrade/v3_4_0/I6093_AddForeignKeys.php
classes/migration/upgrade/v3_4_0/I7901_Duplicate_OAI_IDs.php
classes/migration/upgrade/v3_4_0/I9231_FixMetricsIndexes.php
classes/migration/upgrade/v3_4_0/PreflightCheckMigration.php
classes/migration/upgrade/v3_5_0/I9892_FloatToDecimalColumnTypeUpdate.php
dbscripts/xml/upgrade.xml
plugins/oaiMetadataFormats/dc/tests/OAIMetadataFormat_DCTest.php
plugins/paymethod/paypal/composer.json
plugins/paymethod/paypal/composer.lock
tests/classes/search/ArticleSearchIndexTest.php
tests/classes/search/ArticleSearchTest.php

pkp/pkp-lib#9892 upgrade to laravel 11 and PHP 8.2+

---

classes/migration/upgrade/v3_5_0/I5885_RenameReviewRemainderSettingsName.php
classes/migration/upgrade/v3_5_0/I5885_RenameReviewReminderSettingsName.php
dbscripts/xml/upgrade.xml

pkp/pkp-lib#5885 Review remainder update

---

tests/jobs/doi/DepositIssueTest.php
tests/jobs/notifications/IssuePublishedNotifyUsersTest.php
tests/jobs/notifications/OpenAccessMailUsersTest.php
tests/jobs/statistics/CompileCounterSubmissionDailyMetricsTest.php
tests/jobs/statistics/CompileCounterSubmissionInstitutionDailyMetricsTest.php
tests/jobs/statistics/CompileIssueMetricsTest.php
tests/jobs/statistics/CompileSubmissionGeoDailyMetricsTest.php
tests/jobs/statistics/CompileUniqueInvestigationsTest.php
tests/jobs/statistics/CompileUniqueRequestsTest.php
tests/jobs/statistics/DeleteUsageStatsTemporaryRecordsTest.php
tests/jobs/statistics/ProcessUsageStatsLogFileTest.php

pkp/pkp-lib#9899 Job unit tests patch

---

classes/decision/types/traits/RequestPayment.php
jobs/notifications/IssuePublishedNotifyUsers.php
jobs/notifications/OpenAccessMailUsers.php
tests/jobs/.gitkeep
tests/jobs/doi/DepositIssueTest.php
tests/jobs/notifications/IssuePublishedNotifyUsersTest.php
tests/jobs/notifications/OpenAccessMailUsersTest.php
tests/jobs/statistics/CompileCounterSubmissionDailyMetricsTest.php
tests/jobs/statistics/CompileCounterSubmissionInstitutionDailyMetricsTest.php
tests/jobs/statistics/CompileIssueMetricsTest.php
tests/jobs/statistics/CompileSubmissionGeoDailyMetricsTest.php
tests/jobs/statistics/CompileUniqueInvestigationsTest.php
tests/jobs/statistics/CompileUniqueRequestsTest.php
tests/jobs/statistics/DeleteUsageStatsTemporaryRecordsTest.php
tests/jobs/statistics/ProcessUsageStatsLogFileTest.php

pkp/pkp-lib#10306 Queue jobs unit tests

---

classes/orcid/actions/SendReviewToOrcid.php
dbscripts/xml/install.xml
dbscripts/xml/upgrade.xml
jobs/orcid/DepositOrcidReview.php
jobs/orcid/ReconcileOrcidReviewPutCode.php

Added review_assignment_settings table

---

classes/controllers/grid/issues/IssueGridHandler.php
classes/publication/Repository.php
controllers/grid/issues/IssueGridRow.php
controllers/grid/issues/form/IssueForm.php
locale/en/editor.po
templates/controllers/grid/issues/form/issueForm.tpl

https://github.com/pkp/pkp-lib/issues/7165

pkp/pkp-lib#7165 Issue datePublished can be set when adding an issue

---

classes/submission/maps/Schema.php
schemas/submission.json

pkp/pkp-lib#11025 Include issue info on submission API data

---

classes/migration/upgrade/v3_4_0/I7725_DecisionConstantsUpdate.php
classes/migration/upgrade/v3_5_0/I11241_MissingDecisionConstantsUpdate.php
dbscripts/xml/upgrade.xml

pkp/pkp-lib#11241 Added missing decisions migration

---

api/v1/contexts/index.php
api/v1/reviewers/index.php
api/v1/reviewers/recommendations/ReviewerRecommendationController.php
api/v1/reviewers/recommendations/formRequests/AddReviewerRecommendation.php
api/v1/reviewers/recommendations/formRequests/EditReviewerRecommendation.php
api/v1/reviewers/recommendations/formRequests/UpdateStatusReviewerRecommendation.php
api/v1/reviewers/recommendations/resources/ReviewerRecommendationResource.php
classes/components/forms/context/ReviewerRecommendationForm.php
classes/components/listPanels/ReviewerRecommendationsListPanel.php
classes/core/Application.php
classes/facades/Repo.php
classes/migration/install/ReviewerRecommendationsMigration.php
classes/migration/upgrade/v3_6_0/I1660_ReviewerRecommendations.php
classes/security/authorization/RecommendationAccessPolicy.php
classes/security/authorization/RecommendationContextPolicy.php
classes/security/authorization/RecommendationRequiredPolicy.php
classes/services/ContextService.php
classes/submission/reviewer/form/ReviewerReviewStep3Form.php
controllers/grid/users/reviewer/ReviewerGridHandler.php
cypress/support/commands.js
cypress/tests/data/60-content/AmwandengaSubmission.cy.js
cypress/tests/integration/ReviewerRecommendation.cy.js
dbscripts/xml/install.xml
dbscripts/xml/upgrade.xml
locale/en/editor.po
locale/en/locale.po
locale/en/manager.po
pages/dashboard/DashboardHandler.php
pages/management/SettingsHandler.php
templates/reviewer/review/reviewerRecommendations.tpl

pkp/pkp-lib#1660 Customizable Reviewer Recommendations

---

cypress/support/commands.js
cypress/tests/data/60-content/AmwandengaSubmission.cy.js

To align with the migration script created in the backend, let's assign "Version of Record" publication stage on our cypress tests.

pkp/pkp-lib#11296 Cypress - Assign VoR instead of AO when publishing a version
